### ISSUE TITLE
Offline workers not being purged

### ISSUE THREAD

**Issue by v1sion** [mher/flower#1004]
**Description**

I'm running flower in a kubernetes pod, and I was trying to remove the offline workers from the flower dashboard but for some reason the offline workers are still showing up, even if i setup the flag `--purge_offline_worker`.

```
flower -A worker.celery --purge_offline_workers=10 --basic_auth=$FLOWER_USERNAME:$FLOWER_PASSWORD -l info
```

**Screenshots**

<img width="1399" alt="Screenshot 2020-07-20 at 10 06 55" src="https://user-images.githubusercontent.com/10966855/87920238-d6603a80-ca70-11ea-8b75-430ecf07378a.png">

**System information**
```
flower   -> flower:0.9.4 tornado:6.0.4 humanize:(0, 4)
software -> celery:4.4.2 (cliffs) kombu:4.6.11 py:3.7.7
            billiard:3.6.3.0 redis:3.5.2
platform -> system:Linux arch:64bit
            kernel version:4.14.177-139.253.amzn2.x86_64 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:rediss results:rediss://:**@redis01.**:6379/0
```

**Comment by mher** [comment]
`--purge_offline_worker` option was added to version `0.9.5`. Try to update your flower version to the latest.

**Comment by v1sion** [comment]
Ohh sorry for the spam then.
