### ISSUE TITLE
discussion: Potential code quality issues found

### ISSUE THREAD

**Issue by pnijhara** [mher/flower#1006]
I have forked this repo around a week ago and was going through the code. There I decided to run a static analysis by [DeepSouce](https://deepsource.io). In that analysis, I have found somewhat around 80 code quality issues in **flower**.

Those issues are categorized as:

- **Antipatterns:** 47
- **Bug-risks:** 13
- **Performance issues: 18**
- **Security issues: 2**

You can find the full report here &rarr; https://deepsource.io/gh/pnijhara/flower/issues/?category=recommended
Many of them can be autofixed by DeepSource in a single click such as usage of[ unnecessary literal](https://deepsource.io/gh/pnijhara/flower/issue/PTC-W0018/occurrences) which can be fixed by using literal syntax.

I would love to send a patch with some fix if you want. Also do let me know which of them you consider as false positives and which of them of high priority.

False positives or intentional violations can also be silenced by ignoring issues.

I have also added a config file as `.deepsouce.toml` for letting DeepSource run the analysis. You can find that file [here](https://github.com/pnijhara/flower/blob/master/.deepsource.toml) in my [forked repo](https://github.com/pnijhara/flower/).

**Comment by mher** [comment]
Thanks for running the analysis. Most of the issues mentioned in the report are false positives, except

- https://deepsource.io/gh/pnijhara/flower/issue/PYL-R1718/occurrences
- https://deepsource.io/gh/pnijhara/flower/issue/PYL-W1201/occurrences
- https://deepsource.io/gh/pnijhara/flower/issue/PYL-W0404/occurrences
- https://deepsource.io/gh/pnijhara/flower/issue/PYL-W0611/occurrences
- https://deepsource.io/gh/pnijhara/flower/issue/PTC-W0018/occurrences

Feel free to open a pull request for the issues above

**Comment by pnijhara** [comment]
Sure! I will send PRs for the above issues in the coming days.

**Comment by pnijhara** [comment]
@mher only one of the above-stated issue has been solved. Moreover, I would love to integrate DeepSource with **flower**.
