### ISSUE TITLE
QUESTION: How is it possible to have a worker with status=offline but active=1

### ISSUE THREAD

**Issue by tatitati** [mher/flower#1007]
First all, I love Flower!, great job guys.

In my case still I'm trying to understand something about it. Running long tasks (they take from 20 mins to 2 hours) I have a weird scenario in which my celery worker, after a while (15-20 mins) pass from status=online to offline, however they still have active=1. 

After this I see how the same task is started in another celery worker. Ant the process repeat. This happens again until I have the same task running three times at the same time in different workers. All of them offline with active=1 after a while

- What does it mean to have a celery worker status=offline with active=1?
- What can be the reason to have a worker on this state?

**Comment by mher** [comment]
Celery workers periodically send heartbeats. If flower doesn't receive heartbeat for some time it marks worker state as offline. 

active=1 means flower received a task received event and it is waiting for task success or task failure event.
