### ISSUE TITLE
Broker tab should allow to see messages in each queue

### ISSUE THREAD

**Issue by anudeepsamaiya** [mher/flower#1010]
**Is your feature request related to a problem? Please describe.**
I use flower to monitor the celery worker and redis queues. Flower's broker tab allows one to view the count of messages in each queue, but it does not allow to view the messages.

For instance, I feel like it would be a good ux, when I see around 10000 messages in one of my queue, then to be able to see what kind of messages are in the queue.

**Describe the solution you'd like**
- A Queue detail page. It will lists the messages in a particular queue. The list will grouped by the message type and sorted by count of messages in each group.
- Another QueueMessage detail page for each message group.

Thanks for the such a wonderful library. @mher If you consider this, I would be happy to raise a pr.

**Comment by mher** [comment]
Not all brokers support viewing enqueued messages. It will not possible to implement the same functionality for RabbotMQ.

**Comment by anudeepsamaiya** [comment]
@mher can't it be a redis specific feature?
