### ISSUE TITLE
flower UI broker and monitor tab not working

### ISSUE THREAD

**Issue by abiwill** [mher/flower#1016]
Flower UI Broker tab display "redis broker is not supported" and monitor tab does not display any information. However the dashboard and task tab are showing the celery worker named and tasks information.

Flower Version -- 0.9.3
Redis Version -- 5
Deployed on Docker engine -- 19.03.9 

**Screenshots**
![image](https://user-images.githubusercontent.com/5870370/89427870-5d8ffc80-d759-11ea-9fe6-0b77ee01ae9f.png)
![image](https://user-images.githubusercontent.com/5870370/89427938-70a2cc80-d759-11ea-871a-fbc72cec669b.png)
![image](https://user-images.githubusercontent.com/5870370/89428000-844e3300-d759-11ea-83a4-25511684f706.png)
![image](https://user-images.githubusercontent.com/5870370/89428029-8d3f0480-d759-11ea-804b-e5520c7510b5.png)
![image](https://user-images.githubusercontent.com/5870370/89428785-646b3f00-d75a-11ea-805a-f24e368269d3.png)

**System information**
Flower Version -- 0.9.3
Redis Version -- 5
Deployed on Docker engine -- 19.03.9 
Redis is deployed with sentinel and authentication enabled.

**Comment by mher** [comment]
Try to update flower version to latest/master. The support of redis sentinel was added recently https://github.com/mher/flower/pull/955
