### ISSUE TITLE
Issue in building, a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by gauravmarkan** [mher/flower#1022]
ERROR: for celery-flower-docker_etcd_1  a bytes-like object is required, not 'str'
Creating celery-flower-docker_rabbitmq_1 ... done
ERROR: for etcd  a bytes-like object is required, not 'str'

I have used the entire the code from this repo. I see this is some python error but not sure on how can i proceed, can someone please help in this.

**Comment by mher** [comment]
Please fill the bug report template when opening issues
