### ISSUE TITLE
Prometheus exporter Content-Type header does not fit prometheus exporter specification

### ISSUE THREAD

**Issue by timjohncurtis** [mher/flower#1024]
**Describe the bug**
prometheus exporter endpoint does not match the prometheus spec: https://prometheus.io/docs/instrumenting/exposition_formats/

**To Reproduce**
1. run flower
2. `curl -s -D - -o /dev/null http://localhost:5555/metrics`

**Expected behavior**
`Content-Type: text/plain` is shown

**Screenshots**
n/a

**System information**
Any system

**Comment by timjohncurtis** [comment]
[https://github.com/mher/flower/pull/1025](Pull Request)

**Comment by mher** [comment]
Fixed by https://github.com/mher/flower/pull/1025
