### ISSUE TITLE
bad_header GET /api

### ISSUE THREAD

**Issue by yinbiao** [mher/flower#1026]
**Describe the bug**
when i click "Broker" Link，has errors in  rabbitmq log file:

{bad_header,<<"GET /api">>}

**To Reproduce**
1. Go to 'http://localhost:5555/broker/'
2. See error in rabbitmq log file:
{bad_header,<<"GET /api">>}

**Expected behavior**

**Screenshots**

**System information**
flower   -> flower:0.9.5 tornado:6.0.4 humanize:2.6.0
software -> celery:4.4.7 (cliffs) kombu:4.6.11 py:3.6.12
            billiard:3.6.3.0 py-amqp:2.6.1
platform -> system:Linux arch:64bit, ELF
            kernel version:3.10.0-862.el7.x86_64 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

**Comment by pinoatrome** [comment]
Hi,
I managed to solve the issue changing configuration of flower site see [https://github.com/mher/flower/issues/1036#issuecomment-743676825](https://github.com/mher/flower/issues/1036#issuecomment-743676825)

HTH
GG
