### ISSUE TITLE
Inspect method time out and unknown worker error

### ISSUE THREAD

**Issue by vliu18** [mher/flower#1027]
I am running flower on a docker container as a separate deployment / service (from my workers) on my kubernetes cluster. When I click on any woker on the Dashboard, I would get an "unknown worker" error (see screenshot). When I go to the logs for the flower pod, I see: 
```
[E 200918 16:28:46 control:45] Inspect method timed out
[W 200918 16:28:46 web:1667] 404 GET /worker/celery@test-app-75f7d849cf-gvpxk (10.0.50.148): Unknown worker
 'celery@test-app-75f7d849cf-gvpxk'
```
The Dashboard otherwise works correctly, and I can see tasks / statuses on the broker (Redis)

<img width="1260" alt="Untitled" src="https://user-images.githubusercontent.com/8345625/93623492-d3b88d80-f9ac-11ea-8765-102ec4c773d1.png">

**Comment by mher** [comment]
This is not a flower bug. Inspect methods can timeout because of busy workers or other reasons. Try to increase the inspect timeout in your config. You can debug your celery setup using `celery inspect` command
