### ISSUE TITLE
flower .9.5 is truncating task kwargs

### ISSUE THREAD

**Issue by alkupe** [mher/flower#1030]
**Describe the bug**
I tried upgrading from 0.9.3 to 0.9.5 and now in the UI my kwargs look like `kwargs: { 'hosts': [...`
**To Reproduce**
1 run flower with redis backend/broker
2. send a task with kwargs
3. look in flower UI, kwargs are truncated.

**Expected behavior**
Expect full kwargs printed out readably (as it was in 0.9.3)

**Screenshots**
![Screen Shot 2020-09-25 at 3 03 08 PM](https://user-images.githubusercontent.com/1372441/94306196-81ddad80-ff40-11ea-8ae7-aaf3b652ef18.png)

**System information**
Output of `python -c 'from flower.utils import bugreport; print(bugreport())'` command
flower   -> flower:0.9.5 tornado:6.0.4 humanize:2.6.0
software -> celery:4.3.0 (rhubarb) kombu:4.6.3 py:3.7.7
            billiard:3.6.3.0 py-amqp:2.6.1
platform -> system:Linux arch:64bit
            kernel version:4.15.0-115-generic imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

**Comment by mher** [comment]
flower doesn't truncate args/kwargs. The behavior change you observe probably comes from changes in celery setup/version.

**Comment by alkupe** [comment]
if you say so, celery is pinned to 4.3 in both cases
