### ISSUE TITLE
when using function of pagination with the api/tasks?limit=2&offset=2 ,the params of the 'offset' is invalid

### ISSUE THREAD

**Issue by chaasse** [mher/flower#1039]
**Describe the bug**
when using function of pagination with the api/tasks?limit=2&offset=2 ,the params of the 'offset' is invalid

**To Reproduce**
you can create several tasks then,you can try to use the api/tasks?limit=2&offset=2 to see that nothing changed compared with the
api/tasks?limit=2

**Expected behavior**
This should be changed when using the params of the offset,the result will be changed foward

**Comment by mher** [comment]
Flower contains a test for limit and offset params. It correctly handles limit=2&offset=2. https://github.com/mher/flower/blob/30b5a975b763843bc7ff27d5515f33f97f986bce/tests/unit/api/test_tasks.py#L150

If you believe there is still a bug, please provide a simple test case to demonstrate it.
