### ISSUE TITLE
pip install flower gives 0.9.7 instead of 1.0.x

### ISSUE THREAD

**Issue by liuzheng1990** [mher/flower#1052]
Dear committee. Really enjoy using flower. On the documentation page (https://flower.readthedocs.io/en/latest/install.html) it seems the current official released version of `flower` is `1.0.0`, and the master branch is `1.0.x` (x > 0). However, when doing `pip install flower`, it still installs `0.9.7`. Just to check whether `1.0.0` has really been released? If so, wouldn't it be nice if that's the version available on pypi? Sounds to me that `1.0.0` is more official (judging from this version number only :)

**Comment by mher** [comment]
The latest release version is `0.9.7`. `1.0.0` is the development version.

**Comment by liuzheng1990** [comment]
I see. But appears from the documentation page https://flower.readthedocs.io/ that 1.0.0 is official. Maybe I was mistaken by it.
