### ISSUE TITLE
Vine pinned == 1.3.0 in 0.9.7 is it necessary since it breaks dependencies

### ISSUE THREAD

**Issue by campbellmc** [mher/flower#1053]
**Describe the bug**
It seems vine was pinned to 1.3.0 in requirements/defaults.txt in this PR; "Add healthcheck endpoint (#1012)"

There is no real explanation to why it was pinned - there was an issue with vine at the time with vine/amqp which affected celery.

Seems like this is dependency that should not really be pinned here.

**To Reproduce**
Start a project with the following requirements.txt:
celery[redis]==5.0.5   
flower==0.9.7
amqp==5.0.2
vine==5.0.0 

This won't resolve dependencies for installation.
Pinning flower to 0.9.5 will allow the build and everything works fine.

**Expected behavior**
Should be able to resolve dependencies and build image with vine==5.0.0

**Screenshots**
n/a

**System information**
n/a

**Comment by mher** [comment]
Thanks for opening the issue @campbellmc. Feel free to open a pull request to remove it.

**Comment by hakamadare** [comment]
@mher it looks like #1056 that fixes this issue has been merged, do you have an idea of when you'll publish an updated package that contains this fix?

**Comment by bmyrtil-fsns** [comment]
I dont believe that merge actually fixed it. the vine dependency is pinned twice for some reason but only one of the lines were removed... unless im looking at the file wrong.

**Comment by hackslashX** [comment]
> I dont believe that merge actually fixed it. the vine dependency is pinned twice for some reason but only one of the lines were removed... unless im looking at the file wrong.

You're right. It's mentioned there twice. Both entries have to be removed.

**Comment by mher** [comment]
Fixed in the master
