### ISSUE TITLE
404 error on 0.9.5 or higher with nginx proxy

### ISSUE THREAD

**Issue by hrsk-tony** [mher/flower#1069]
**Describe the bug**
After update to 0.9.5 flower return 404 page and suggested fix doesn't work. It seems that issue was introduced by this PR: https://github.com/mher/flower/pull/766 and in this comment the suggested solution arise https://github.com/mher/flower/pull/766#issuecomment-655769717. Which is to remove the `rewrite` rule for nginx that was used as reverse proxy to serve flower on non root URL. 
In my setup I use nginx to reverse proxy a bunch of services, not only flower, and I had no rewrite rule.

**To Reproduce**
My nginx config is following:
```
location /worker/ {
        proxy_pass http://flower:8888/;
        proxy_set_header Host $host;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
```
Note that there is no `rewrite` rule.
and following docker-compose config:
```
  flower:
    image: mher/flower:0.9.5
    environment:
      - FLOWER_URL_PREFIX=worker
      - FLOWER_PORT=8888
    expose:
      - 8888
```

**Expected behavior**
When using 0.9.4 when I type `http://localhost/worker/` in my browser everything works, but on 0.9.5 and higher I get 404 page instead. 

Could someone explain how `url_prefix` works now? And what config should I use for nginx and flower to be able to serve flower under `localhost/worker/` path with bunch of other services? I tried to remove `FLOWER_URL_PREFIX`  from docker-compose service definition but that don't work because all flower links are not prefixed with `worker` anymore.
I also tried  to use  `proxy_pass http://flower:8888/worker/;` but that don't work either, requests for all the static files fails with 404 and only plain html page with navbar is shown

**Comment by hrsk-tony** [comment]
There is an open issue  https://github.com/mher/flower/issues/1015 with similar problem where the suggested fix is just to pin 0.9.4 version for flower, which is not an options I'm willing to take. If someone could help with finding a solution I could submit a PR with documentation about this particular setup

**Comment by boomshadow** [comment]
Is this still a problem @hrsk-tony ? I'm running Flower 0.9.7 with an Nginx reverse proxy, with no problems.

**Comment by mher** [comment]
Version 0.9.7 doesn't require nginx config
