### ISSUE TITLE
django-flower how to see dashboard

### ISSUE THREAD

**Issue by GarridoM** [mher/flower#1070]
Hi! 

I have installed django-flower (https://pypi.org/project/django-flower/ ) but I do not how to see the dashboard or how to execute it. I have followed the instructions and this framework it is an fork of this repository. Anyone knows how to do it? Is it necessary to install flower?

**Comment by mher** [comment]
Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use StackOverflow.com for general usage questions instead.
