### ISSUE TITLE
Flower DB getting filled very quickly

### ISSUE THREAD

**Issue by rtgudz45** [mher/flower#1075]
Hi,
I have kept max_tasks as default ie 10000. But still my db which has volume of 47GB fills very quickly(within a day).
My configuration is as below:

--broker=amqp://rabbitmq:user@rabbitmq:5672//
--broker_api=http://rabbitmq:user@rabbitmq:15672/api/
--basic_auth=user:password
--loglevel=INFO
--persistent=True
--db=/data/flower/flower.db
--state_save_interval=5
--log_file_prefix=/data/flower/flower.log

What can be done to resolve the space issue?

**Comment by eavilesmejia** [comment]
You may use logrotate

**Comment by paskalnikita** [comment]
If you are using flower:0.9.7
--state_save_interval=5 <--- 5 milliseconds 
increase  5 to 5000 (5 seconds)

**Comment by kodless** [comment]
**LEEK: a new celery tasks monitoring tool!**

Repository: https://github.com/kodless/leek

Website: https://tryleek.com/
