### ISSUE TITLE
Allow to configure Prometheus Histogram buckets for flower_task_runtime_seconds

### ISSUE THREAD

**Issue by cdessez** [mher/flower#1076]
The prometheus exporter exposes a `Histogram` of tasks runtime which is very useful to monitor the distribution of runtime.  
However it uses the default buckets provided by the `prometheus_client` package, which has `10.0` seconds as the biggest bucket. While this default bucketing might be enough for most use cases, it is not fit for projects where tasks commonly take more than 10s to run.
  
I would like to be able to configure those buckets via the flower configuration. 

---

For reference, here are the default buckets:
```python
(.005, .01, .025, .05, .075, .1, .25, .5, .75, 1.0, 2.5, 5.0, 7.5, 10.0, INF)
```

**Comment by kodless** [comment]
**LEEK: a new celery tasks monitoring tool!**

Repository: https://github.com/kodless/leek

Website: https://tryleek.com/

**Comment by toothstone** [comment]
@cdessez I think #1134 implemented exactly this? Unfortunately it can't be easily used as it hasn't been released...

**Comment by cdessez** [comment]
Nice, thanks for the heads-up @toothstone! It is indeed exactly what I need.

I'm happy to wait a little longer for a release to be able to use it. I have a workaround in place in the meantime.
