### ISSUE TITLE
Flower py2 breaks on 0.9.7

### ISSUE THREAD

**Issue by babinos87** [mher/flower#1079]
**Describe the bug**
We are using flower inside docker, installing version <1.0.0, so it automatically upgrades when there is a new minor version released.

With the 0.9.7 version, we get some errors like this:
```
flower stdout | Traceback (most recent call last):
flower stdout |   File "/usr/local/bin/flower", line 6, in <module>
flower stdout |      flower stdout | from flower.__main__ import main
flower stdout |   File "/usr/local/lib/python2.7/site-packages/flower/__main__.py", line 11
    print(bugreport(app=flower.app), file=sys.stderr)
                       flower stdout |                    ^
SyntaxError: invalid syntax
```
debugging this, I found this commit for 0.9.7: https://github.com/mher/flower/commit/26d19a816a362cdce32fd125596ed3bd238b40b4#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485L6

which indicates that py2 support has been dropped in 0.9.7???

I understand why you want to do that, but in this case you should have done a MAJOR version release where this feature would be introduced, as it contains breaking changes.

I would recommend to fix versions <1.0.0 to support py2 and drop py2 support in version 1.x.x .

**To Reproduce**
Install flower version 0.9.7 using python 2.7

**Expected behavior**
Flower works

**System information**
```
$ python --version
Python 2.7.16

$ python -c 'from flower.utils import bugreport; print(bugreport())'
Unknown Celery version
```

When I downgrade to 0.9.5 all work fine, as before.

**Comment by mher** [comment]
0.9.7 doesn't support python 2

**Comment by babinos87** [comment]
@mher I knew that already, all I am saying is that they way you are introducing backwards incompatible changes is not according to best practices.
