### ISSUE TITLE
`load` unit test fails when run with `setup.py test`

### ISSUE THREAD

**Issue by pabs3** [mher/flower#1095]
**Description**

The `load` unit test fails when run with `setup.py test`.

**To Reproduce**

1. Run `python3 setup.py test`
4. See error with the `load` test.

**Expected behavior**

The load test should pass if it is present.

**Traceback**
```
load (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: load (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: load
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "tests/load.py", line 4, in <module>
    from tasks import add, sleep, error
ModuleNotFoundError: No module named 'tasks'
```

**System information**
```
python3 -c 'from flower.utils import bugreport; print(bugreport())'
flower   -> flower:0.9.7 tornado:6.1 humanize:3.4.1
software -> celery:4.4.7 (cliffs) kombu:4.6.11 py:3.9.2
            billiard:3.6.4.0 py-amqp:2.6.1
platform -> system:Linux arch:64bit
            kernel version:5.10.0-6-amd64 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled
```

**Analysis**

The tasks module appears to be in the examples directory. I'm not sure if the tasks module should be moved into the test directory, or if the load unit test should import the examples.tasks module instead, or if the examples directory should be added to `sys.path` somehow, or if the `load` test should be removed entirely.

**Comment by kodless** [comment]
**LEEK: a new celery tasks monitoring tool!**

Repository: https://github.com/kodless/leek

Website: https://tryleek.com/

**Comment by mher** [comment]
Tests expect `examples` directory to be in `PYTHONPATH`.

Try ```PYTHONPATH=./examples python setup.py test```

**Comment by pabs3** [comment]
Thanks, I'll add `examples` to `sys.path` for the `load` test, so that it works out of the box.
