### ISSUE TITLE
Flower does not collect shared tasks within Django project

### ISSUE THREAD

**Issue by Real-Gecko** [mher/flower#1097]
**Describe the bug**
I have a Django project with lot of shared tasks scattered across `tasks.py` modules. With celery 4 Flower was able to collect them all and show 'em in tasks tab, but after upgrading to Celery 5.0.5 I see nothing there:
![image](https://user-images.githubusercontent.com/2231969/115832564-da245180-a434-11eb-9ff1-c8bfb4ffa6cd.png)

I also noticed that when I run `celery -A myproj flower` in console list of registered tasks
```shell
[I 210423 10:06:31 command:142] Registered tasks:
```

does not shall all those `@shared_tasks`s

**To Reproduce**
1. Create a Django project with an app and add usual `shared_task` to the app.
2. Start celery as usual `celery -A proj worker -E -B -l DEBUG`
3. Notice the list of tasks registered by Celery, it contains `shared_task`s
4. Start Flower `celery -A proj flower`
5. Notice that no `shared_task`s is registered.

**Expected behavior**
See the list of all tasks with statuses.

**System information**
Python 3.8.9
Celery 5.0.5
Flower https://github.com/mher/flower/commit/780bc43ce0c9545b25b3cee987fe31a5a465e0fd

**Comment by mher** [comment]
Fixed by #1108
