### ISSUE TITLE
Broker tab 500 error - Airflow Celery

### ISSUE THREAD

**Issue by sakkammadam** [mher/flower#1099]
**Describe the bug**
We setup Flower in conjunction with Celery Worker for Airflow cluster. We are using Redis (with Token/Password and SSL) as celery backend. On connecting to flower UI - all tabs and links work as expected EXCEPT the broker tab.

**To Reproduce**
1. Go to Flower UI
2. Click on Broker tab
3. See error

**Expected behavior**
Not 500 error and graphs of workers

**Screenshots**

![image](https://user-images.githubusercontent.com/10201590/117204832-b1da1280-ada5-11eb-89ac-8d3c683befe8.png)

**System information**
Libraries - 
celery==4.4.7
flower==0.9.7
kombu==4.6.11

flower   -> flower:0.9.7 tornado:6.1 humanize:3.4.1
software -> celery:4.4.7 (cliffs) kombu:4.6.11 py:3.6.8
            billiard:3.6.4.0 py-amqp:2.6.1
platform -> system:Linux arch:64bit, ELF
            kernel version:3.10.0-1160.21.1.el7.x86_64 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

**Comment by mher** [comment]
Please provide the stack trace and the command line you are using to launch flower
