### ISSUE TITLE
Instructions to contributions? CSS Upgrade?

### ISSUE THREAD

**Issue by lowercase00** [mher/flower#1100]
Hi there.
I'm a heavy user of Flower, monitoring a production application using celery.
I do have a few ideas to an improved frontend though, a bit of CSS, nothing much, nothing structural, but I would like to try a few things. 
Would you guys have more detialed information to contribute? and maybe post PR?
Thanks a lot.

**Comment by johanvergeer** [comment]
I'm picking up the CSS upgrade in #1078
