### ISSUE TITLE
Number of currently executing tasks at worker metric causes key error

### ISSUE THREAD

**Issue by Tomasz-Kluczkowski** [mher/flower#1104]
**Describe the bug**

Occassionally, only when starting flower I get this:

```
[E 210512 10:43:07 ioloop:761] Exception in callback functools.partial(<bound method EventsState.event of <State: events=5 tasks=0>>, {'hostname': 'celery@decomp', 'utcoffset': -1, 'pid': 43637, 'clock': 763, 'freq': 5, 'sw_ident': 'py-celery', 'sw_ver': '4.4.7', 'sw_sys': 'Darwin', 'timestamp': 1620812587.100968, 'type': 'worker-heartbeat', 'local_received': 1620812587.2165608})
    Traceback (most recent call last):
      File "/Users/tomaszkluczkowski/envs/celery-test/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
        ret = callback()
      File "/Users/tomaszkluczkowski/envs/celery-test/lib/python3.7/site-packages/flower/events.py", line 77, in event
        self.metrics.worker_number_of_currently_executing_tasks.labels(worker_name).set(event['active'])
    KeyError: 'active'
```

This does not stop flower completely though - it still works.

It appears that initial `worker-heartbeat` event sent from celery may have `active` key missing in it - later on it all works fine but looks ugly on boot.

**To Reproduce**

I cannot do it reliably (it happens only sometimes) and the documentation in celery specifies that the `worker-heartbeat` will have `active` key in it so really it is celery's bug...

1. Start all your workers and broker, get some tasks running.
2. Start flower.
3. It probably will report key error 'active' - it is intermittent though. Sometimes celery event comes with it sometimes not.

**Expected behavior**

No key error on boot of flower.

**Screenshots**

**System information**
Output of `python -c 'from flower.utils import bugreport; print(bugreport())'` command

**Comment by Tomasz-Kluczkowski** [comment]
@mher since I introduced this metric I will fix this (just put a guard when getting the `active` from event and possibly report in the celery project.

**Comment by mher** [comment]
Fixed by https://github.com/mher/flower/pull/1105
