### ISSUE TITLE
Has the monitor tab of the navbar been deleted?

### ISSUE THREAD

**Issue by walirt** [mher/flower#1107]
https://github.com/mher/flower/blob/2674b221be97ae9221118847837266af54392a55/flower/templates/navbar.html#L1-L23
I checked the code in the template and found that the monitor tab was gone, but I didn't find any update logs

**Comment by mher** [comment]
Monitor tab is deprecated and replaced with prometheus

**Comment by walirt** [comment]
> Monitor tab is deprecated and replaced with prometheus

ok, thx

**Comment by otterbotter** [comment]
Is there any docs or any links to follow to figure out how to set up Prometheus with Flower?

One of the big reasons for setting up Flower was to use monitoring but it took some digging to figure out that it's been removed, but not being familiar with Prometheus I am not sure where to begin.

Any help would be appreciated

**Comment by mher** [comment]
https://github.com/mher/flower/blob/master/docs/prometheus-integration.rst

**Comment by caleb15** [comment]
The flower monitor used to show the "time in queue". Was this referring to the prefetch queue or the broker queue? We want to know how many tasks are waiting in the broker queue, but it looks like that statistic is not present in the prometheus metrics.

**Comment by benbenbuhben** [comment]
> Monitor tab is deprecated and replaced with prometheus

If the Monitor tab has been removed then it'd be worthwhile to update the screenshots in the documentation to reflect this. I was also wondering why the Monitor tab wasn't showing up.

**Comment by f3ndot** [comment]
I liked Flower for its turn-key monitoring solution for our Celery setup. It would be nice to have even just basic rudimentary graphs without having to configure and stand up additional services like Prometheus and Grafana
