### ISSUE TITLE
Latest docker tag not working

### ISSUE THREAD

**Issue by madoke** [mher/flower#1122]
**Describe the bug**
Hi, First of all thanks for this project. I tried to use the latest image published to dockerhub, a day ago (with the 'latest' tag) and got an error related to the flower executable not being in the path

**To Reproduce**
```
docker run -p 5555:5555 mher/flower                                                                                                    127 ↵  6262  18:03:17 
Unable to find image 'mher/flower:latest' locally
latest: Pulling from mher/flower
5843afab3874: Already exists
2dfaacf7024e: Already exists
2dbba127c6aa: Already exists
1a467efa2204: Already exists
865369a531d5: Already exists
02e86a34420f: Already exists
8a0b1a030473: Already exists
9ace7ab41c23: Already exists
362efc2abf29: Already exists
Digest: sha256:da4c47ffc22a3df81d39a2df5366ac51405600e385835e16506a1b3155e9898e
Status: Downloaded newer image for mher/flower:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "flower": executable file not found in $PATH: unknown.
```
Is this a known issue ? Let me know if i can help

**Comment by fredcohen-aa** [comment]
Same problem here. The Dockerfile needs a little reworking. 
The main issue is that entrypoint needs to be "celery" instead of flower.  You'll need to pass "flower" as an argument like this -

```
$ docker run -p 5555:5555  -it --entrypoint "celery" mher/flower  flower
```

**Comment by fredcohen-aa** [comment]
PR #1121 should help address this problem.

**Comment by madoke** [comment]
Hey team i have tested this and its working. Thanks a lot for the quick support !
