### ISSUE TITLE
Only tasks that are in their final result / tombstone state are visible 

### ISSUE THREAD

**Issue by rightisleft** [mher/flower#1127]
**Describe the bug**

As a user of flower,
When I am viewing the "Tasks" page,
Then I should see a list of tasks that are awaiting execution AND OR completion.

Actually: I ONLY see tasks that are InFinalState (IE: SUCCESS)  

**To Reproduce**
Generate 100 long-running jobs with 3 workers

**Expected behavior**
I should see "Pending" and "Started" Jobs

**Screenshots**

<img width="1674" alt="Screen Shot 2021-07-19 at 5 56 10 PM" src="https://user-images.githubusercontent.com/3611930/126232632-4784644f-6e77-4ade-bb7f-c963c8cafd07.png">

**System information**

```
celery -A main worker --hostname=annotate_@%h --pool=solo --task-events --concurrency=1 -l DEBUG
```

Output of `python -c 'from flower.utils import bugreport; print(bugreport())'` command
```
flower   -> flower:1.0.0 tornado:6.1 humanize:3.10.0
software -> celery:5.1.0 (sun-harmonics) kombu:5.1.0 py:3.10.0b1
            billiard:3.6.4.0 py-amqp:5.0.6
platform -> system:Linux arch:64bit, ELF
            kernel version:5.4.0-1051-azure imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

deprecated_settings: None
```

worker configuration:

```
app = Celery(broker='redacted',
    backend='redis://redacted'
)
app.autodiscover_tasks()
app.conf.task_default_queue = 'redacted'
app.conf.task_track_started = True
app.conf.task_send_sent_event = True
app.conf.worker_send_task_events = True
app.conf.worker_hijack_root_logger = False
app.conf.worker_prefetch_multiplier = 1
app.conf.worker_enable_remote_control = True
app.conf.result_expires = 60 * 60 * 2 # 2 hour TTL in seconds
```

**Comment by mher** [comment]
Tasks that are waiting to be executed have a `RECEIVED` state and they are available in tasks page. 

Your Celery configuration includes `worker_prefetch_multiplier=1`, which disables task prefetching. This means that workers will receive tasks one at a time, and no tasks will be waiting for execution in the worker's queue. Instead, the worker will wait to receive a task directly from the broker before starting to process it.
