### ISSUE TITLE
AMQPS certificates for broker connection

### ISSUE THREAD

**Issue by mic159** [mher/flower#113]
How can I set the cacertfile, certfile, and keyfile options for an SSL AMQP connection to the broker?

I tried setting the URI to `amqp://user:pass@my-rabbit-server.example.com/?ssl=1&cacertfile=/etc/rabbitmq/ssl/certs/cacert.pem&certfile=/etc/rabbitmq/ssl/certs/client-cert.pem&keyfile=/etc/rabbitmq/ssl/private/client-key.pem`
But that didnt work, Kombu complains that `_init_params() got an unexpected keyword argument 'certfile'`

I then tried setting `BROKER_USE_SSL` in `flower/settings.py` to a dict with those parameters in it, but that didnt work either.

The error im getting is
`[E 130806 06:46:19 events:94] Failed to capture events: '[Errno 1] _ssl.c:504: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure', trying again in 2 seconds.`

**Comment by YitianSusanLinLime** [comment]
What is cacert and client-cert? I looked at the documentation but they didn't explain this.
