### ISSUE TITLE
HTTP Basic Authentication implementation may be susceptible to timing attacks

### ISSUE THREAD

**Issue by benjamin-jones** [mher/flower#1131]
The implementation of `get_current_user()` in the `BaseHandler` definition uses a non-constant time string comparison to validate HTTP basic authentication credentials:

```
  basic, credentials = auth_header.split()
  credentials = b64decode(credentials.encode()).decode()
  if basic != 'Basic' or credentials not in basic_auth:
```
This could potentially improve the chances of an attacker guessing the authentication credentials beyond a naive bruteforce or dictionary attack via a [timing attack](https://ropesec.com/articles/timing-attacks/).

Consider a constant-time string comparison or hashing the given credentials against a salted hash of the configured credentials.

**Comment by mher** [comment]
Fixed by https://github.com/mher/flower/pull/1166
