### ISSUE TITLE
Where is flower 1.0.1?

### ISSUE THREAD

**Issue by BoPeng** [mher/flower#1144]
The latest version on pypi is 1.0.0, and the README says 

> Please note that from version 1.0.1 Flower uses Celery 5 and has to be invoked in the same style as celery commands do.

So 1.0.0 does not yet support Celery 5, and we should wait for a 1.0.1 version, right?

**Comment by Achilles0509** [comment]
Yes, it's really pain.
When will be released 1.0.1 version ?

**Comment by GitRon** [comment]
@mher Any update on the issue? Releasing the version won't take that long, right? 😇

**Comment by JunPengGuo** [comment]
@mher The flower 1.0.0 is not compatible with Celery 5.+. How to solve this problem？ Any update？

**Comment by GitRon** [comment]
If at least one contributor could tag the current version in git as v1.0.1 then the import would look less ugly 😟

**Comment by CodePint** [comment]
It appears that the docs are incorrect. I've tested it and flower v1.0.0 does require celery 5.
It would be odd for a patch release to introduce breaking changes...

You can find the original issue here along with a comment announcing the release from @mher 
https://github.com/mher/flower/issues/1029#issuecomment-873243638

The docs need updating.

**Comment by mher** [comment]
`1.0.1` is a typo in readme. It should be 1.1.0
