### ISSUE TITLE
/api/workers 404 if refresh is used along with status

### ISSUE THREAD

**Issue by vladimirtiukhtin** [mher/flower#1148]
Workers obtained through
```
requests.get(self.base_url + '/api/workers', auth=requests.auth.HTTPBasicAuth(self.username, self.password), params={'refresh': True, 'status': True})
```
result in 404 in any other call like '/api/worker/shutdown', while
```
requests.get(self.base_url + '/api/workers', auth=requests.auth.HTTPBasicAuth(self.username, self.password), params={'refresh': True})
```
works as expected

**Comment by alienr** [comment]
@vladimirtiukhtin not clear, pls share the exact code

**Comment by nicolascedilnik** [comment]
I can reproduce this bug too.

`GET /api/workers` then `POST /api/worker/shutdown/xxx` works

`GET /api/workers?status=1` then `POST /api/worker/shutdown/xxx` returns 404.

Apparently returning only the workers' online status does something weird!

**Comment by mher** [comment]
https://github.com/mher/flower/commit/7a3fc904c126e7d2caac46a0a4819bfe8de7d689 should fix the issue
