### ISSUE TITLE
Your version of jquery on the pip install has a vulnerable version, please update so I can use it on my site again. At least to 3.5.0

### ISSUE THREAD

**Issue by auctone** [mher/flower#1154]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information**
Output of `python -c 'from flower.utils import bugreport; print(bugreport())'` command

**Comment by auctone** [comment]
Your version of jquery on the pip install has a vulnerable version, please update so I can use it on my site again. At least to 3.5.0

**Comment by johanvergeer** [comment]
I have picked this up in #1078
