### ISSUE TITLE
When using Redis there is no data in the. dashboard

### ISSUE THREAD

**Issue by LanceMeister** [mher/flower#1157]
Hello, I'm am simply using redis==3.5.3 with flower==1.0.0 and celery==5.1.2. When I type:  `celery -A MyApp flower  ` in the terminal I get some warnings.

INFO 2021-11-02 23:38:04,177 mixins 46475 6142701568 Connected to redis://localhost:6379//
WARNING 2021-11-02 23:38:05,232 inspector 46475 6193180672 Inspect method registered failed
WARNING 2021-11-02 23:38:05,232 inspector 46475 6277312512 Inspect method conf failed
WARNING 2021-11-02 23:38:05,233 inspector 46475 6176354304 Inspect method active_queues failed
WARNING 2021-11-02 23:38:05,234 inspector 46475 6260486144 Inspect method revoked failed
WARNING 2021-11-02 23:38:05,234 inspector 46475 6243659776 Inspect method reserved failed
WARNING 2021-11-02 23:38:05,235 inspector 46475 6159527936 Inspect method stats failed
WARNING 2021-11-02 23:38:05,236 inspector 46475 6226833408 Inspect method active failed
WARNING 2021-11-02 23:38:05,236 inspector 46475 6210007040 Inspect method scheduled failed

I run a task on my website but then nothing appears in the dashboard.
![Screenshot 2021-11-02 at 23 39 47](https://user-images.githubusercontent.com/20726209/139961600-217a5847-68aa-44b9-86c3-47d33b14af61.png)

I do however see some information under broker.
![Screenshot 2021-11-02 at 23 39 59](https://user-images.githubusercontent.com/20726209/139961641-32c9a57b-920d-4352-b63e-57ad212f4198.png)
I have not been able to find a solution to this problem on stack exchange.

**Comment by JCardoen** [comment]
Did you start the worker?

`celery -A MyApp worker`

**Comment by LanceMeister** [comment]
I started the worker and that works to show when a task is executed. My question is with Django flower. [See the documentation of celery flower](https://flower.readthedocs.io/en/latest/install.html#usage-examples) 

celery -A MyApp flower

**Comment by abellotti** [comment]
Having the same issue, bumping flower down to 0.9.7 and celery to 4.4.7, I'm able to get info about my celery tasks from the redis broker.  So yea, the latest versions do not play nice with each other.

**Comment by abellotti** [comment]
Hi @LanceMeister, why was the issue closed ?  Were you able to get it working ? maybe with a workaround ?

I am having the exact same issue, Flower 1.0.0 as well as running from source, with Celery 5.2.3 and Redis 6.2.6. No issues with Flower 0.9.7, Celery 4.4.7 and Redis 6.2.6.  Thanks.
