### ISSUE TITLE
format_task() is needed for GET /api/tasks and GET /api/task/info/{id}

### ISSUE THREAD

**Issue by nskw29** [mher/flower#1161]
**Is your feature request related to a problem? Please describe.**
When I execute `GET /api/tasks` and `GET /api/task/info/{id}` API, `format_task()` function is not called.
I'm using format_task() to hide password that is in kwargs.  So `format_task()` is important for me.

**Describe the solution you'd like**
Call `format_task()` as same as `flower/views/tasks.py:TaskView#get()` does.
To accomplish it, insert one line `task = self.format_task(task)` into the following locations:
1. `flower/api/tasks.py:ListTasks#get()`: before the line `task = tasks.as_dict(task)` [url](https://github.com/mher/flower/blob/master/flower/api/tasks.py#L540)
2. `flower/api/tasks.py:TaskInfo#get()`: before the line `response = task.as_dict()` [url](https://github.com/mher/flower/blob/master/flower/api/tasks.py#L648)

**Comment by mher** [comment]
You can apply `format_task` programmatically in your api call results. `format_task` is only intended for UI
