### ISSUE TITLE
Allow configurable refresh rate by end user in dashboard

### ISSUE THREAD

**Issue by caleb15** [mher/flower#1202]
**Is your feature request related to a problem? Please describe.**
Currently my wifi connection is very slow. The dashboard refresh rate is set at 1 second, but the request takes longer than a second to go through my connection, so each request ends up getting cancelled before it can return. This makes the dashboard page entirely unusable.

**Describe the solution you'd like**
A configurable refresh rate, or raising the refresh rate to 2 seconds.

**Comment by caleb15** [comment]
Ah, it's a url param! Sweet: `?autorefresh=10`

**Comment by sc68cal** [comment]
There is one issue though, the autorefresh parameter doesn't get carried around as you navigate the site. So if you navigate away from the root URL it gets set back to 1
