### ISSUE TITLE
Warning: entry point could not be loaded. Contact its author for help.

### ISSUE THREAD

**Issue by kalsep** [mher/flower#1203]
I have installed airflow celery in my Linux machine. 
when i try to execute "airflow celery flower"
It is giving me this error as

`Traceback (most recent call last):
  File "/home/pravin/sandbox/lib/python3.8/site-packages/click_plugins/core.py", line 37, in decorator
    group.add_command(entry_point.load())
  File "/home/pravin/sandbox/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "/home/pravin/sandbox/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/pravin/sandbox/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (setuptools 44.0.0 (/home/pravin/sandbox/lib/python3.8/site-packages), Requirement.parse('setuptools<59.7.0,>=59.1.1'), {'celery'})`

**Comment by mgjo5899** [comment]
This is probably due to you using the latest celery. According to one of the Stackoverflow search I've done, you need to use 5.0.0 or lower

**Comment by mgjo5899** [comment]
After some google search, I found out you can manually install `setuptools` within that requirement version.
In my case, I managed all the packages using `poetry` and so I manually installed the target `setuptools` using
`poetry run pip install setuptools==59.6` and this fixed my issue.

**Comment by xrhstosmour** [comment]
Should we keep the same version for `setuptools` package, or we can update it to the latest now ?
