### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by themanifold** [mher/flower#1211]
Hello, what is the status of this project? The last thing to be merged into master was in November last year and since then there have been 10+ PRs.

Pinging @mher

**Comment by zenoran** [comment]
Anyone have any updates on this or know what's going on?  Aas @themanifold mentioned there is a ton of code unreleased, not to mention the documentation mentions 1.0.1 but that isn't even released.

**Comment by GitRon** [comment]
Yeah, that's really a bummer, the tool is not usable in v1.0 and just one tiny release would solve it... Maybe this project could be taken over by jazzband or the celery guys?

**Comment by jheld** [comment]
Clearly commits are still being merged so is the issue just around releases to PyPI?

**Comment by zenoran** [comment]
> Clearly commits are still being merged so is the issue just around releases to PyPI?

Ya, I don't think having the source code by itself is useful for the majority of users.  Good point though that there are still merges to master happening... Someone needs to do actual releases/builds and publish to pypi.

**Comment by themanifold** [comment]
We can petition pypi to request a name transfer: https://peps.python.org/pep-0541/#how-to-request-a-name-transfer but we need some one to step up and submit that.

**Comment by GitRon** [comment]
@mher could request to move the project to Jazzband: https://github.com/jazzband/help/issues/new?assignees=&labels=proposal&template=proposal.md&title=Proposal%3A+%3CPACKAGE+NAME%3E

Just fill out the form and we are good to go, if they accept it. 

Otherwise we have to find someone with the capacity to maintain the project.

**Comment by themanifold** [comment]
Is there anyone else we could ask?

**Comment by jheld** [comment]
> We can petition pypi to request a name transfer: https://peps.python.org/pep-0541/#how-to-request-a-name-transfer but we need some one to step up and submit that, and someone to take ownership of the package.

I'll give it a shot!

**Comment by dethos** [comment]
Any news about the current progress and status?

Looking at the current issues and pull requests, there are relevant security problems that need to be solved. Some of them already have pending solutions waiting for reviews and to be merged.

**Comment by jheld** [comment]
So, because @mher did cut a release to PyPI at the beginning of this month, it would make any request for ownership transfer essentially impossible to win.

Please see [abandoned project definition](https://peps.python.org/pep-0541/#abandoned-projects).
