### ISSUE TITLE
Fix --conf documentation

### ISSUE THREAD

**Issue by Patricol** [mher/flower#1213]
**Describe the bug**
Documentation states that `--conf` specifies "A path to the configuration file (by default, flowerconfig.py)"

**To Reproduce**
Attempting to provide a path always fails. (`--conf=relative_path/flowerconfig.py` -> `The module relative_path/flowerconfig was not found.`, `--conf=/absolute_path/flowerconfig.py` -> `The module /absolute_path/flowerconfig was not found.`, etc.)

**Expected behavior**
Documentation should state that it's a python-import-style module. `--conf=relative_path.flowerconfig` works.

**System information**
Using flower 1.0.0, celery 4.4.7, and python 3.6.9. (unfortunately)

It was very hard to research this bug/behavior; the main information I could find was in the incorrect documentation. Hopefully this fix can be pushed to docs soon to avoid another person wasting hours figuring this out. Thank you!

**Comment by Abyss-W4tcher** [comment]
Hello, for those who also wasted time figuring out how to use custom broker url and ssl files :

celery --config relativepath.celeryconfig flower

With celeryconfig.py based on https://docs.celeryq.dev/en/latest/userguide/configuration.html

My example :  

```python
import ssl 

broker_use_ssl =  {
        'keyfile': 'key.pem',
        'certfile': 'certificate.pem',
        'ca_certs': 'ca_certificate.pem',
        'cert_reqs': ssl.CERT_REQUIRED
    }

broker_url='your_url'
```

**Comment by mher** [comment]
Fixed in the latest version
