### ISSUE TITLE
More consistent navigation by keeping pagination settings alive between page visits

### ISSUE THREAD

**Issue by markkorput** [mher/flower#1215]
**Is your feature request related to a problem? Please describe.**
Tasks navigation is inconsistent; *page number*, *number of entries per page*, *selected sorting options* and *search terms* get reset after opening a task and then navigating back (using the browser's back button, because flower does not provide a link back to the index).

**Describe the solution you'd like**
It would help if the browser's location href is updated whenever any of the pagination/filtering/ordering options change. This not only provides more sensible navigation but also allows users to share links to tasks pages with specific pagination settings.

**Comment by lf-novelt** [comment]
yes please, it's very difficult to troubleshoot a lot of tasks failure, as it gets back to page 1 and does not persist the search filter

**Comment by lf-novelt** [comment]
@mher would you accept such a PR?
