### ISSUE TITLE
Task times, Failed tasks, Succeeded tasks are not showing in monitor

### ISSUE THREAD

**Issue by Katafalkas** [mher/flower#123]
Hey,

I am running celery workers on one machine, and RabbitMQ broker on separate server.
I am trying to run Flower. I am running Flower on the same box as RabbitMQ this way:

```
flower --port=5555 --broker=amqp://guest:guest@localhost:5673// --broker_api=http://guest:guest@foo.bar:15672/api/ --logging=debug
```

Broker monitoring works. And all other features work, but the Task times, Failed tasks, Succeeded tasks are empty tables. altho tasks are running.

I run celery with these options:

```
celery worker -A foobar.tasks:celery -B --concurrency=2 -E --loglevel=debug --logfile=/var/log/celery.log  --workdir=/var/www/foo/bar
```

I am sure its not much of an issue, but more of me missing some setting. Any ideas ?

**Comment by charleshan** [comment]
Sorry, to bring up an old issue but I'm having the same problem. The clocks in my machines are synced:
```
$ timedatectl status
Local time: Tue 2019-04-23 22:52:41 UTC
                  Universal time: Tue 2019-04-23 22:52:41 UTC
                        RTC time: Tue 2019-04-23 22:52:42
                       Time zone: Etc/UTC (UTC, +0000)
       System clock synchronized: yes
systemd-timesyncd.service active: yes
```
@Katafalkas could you share how you fixed the issue? Thanks!
