### ISSUE TITLE
API is disabled when using basic_auth

### ISSUE THREAD

**Issue by jepify** [mher/flower#1231]
**Describe the bug**
Is it intentional that the flower API is disabled when using basic_auth.
It is a result of the change being made to all requests [here](https://github.com/mher/flower/blob/master/flower/api/__init__.py) as a fix to the [1217](https://github.com/mher/flower/issues/1217) issue about no default auth.

Is it intentional that basic_auth dissables the API even though the disclosure mentions that basic_auth is not vulnerable?

**Comment by frontierpsycho** [comment]
I believe this change was perhaps the result of a misunderstanding. @tprynn's original [blog post](https://tprynn.github.io/2022/05/26/flower-vulns.html) that disclosed the security issues that the change was supposed to fix, had this recommendation for flower:

> Disable the API unless authentication is configured for Flower

But I think this was misunderstood and in the end the API was disabled _when_ (not unless) authentication is configured. 

It seems that the creator of flower has probably been too busy to maintain it, unfortunately.

**Comment by snyaggarwal** [comment]
Any update on this? When can this be merged?

**Comment by jangia** [comment]
Have no idea. I haven't heard anything from the package author yet.

**Comment by rajkumarvenkatasamy** [comment]
Any updates on when this issue will get fixed? Thanks!

**Comment by SoundWaveX81** [comment]
Another one here trying to know if this will get fixed at some point :)

**Comment by adampl** [comment]
This is stupid: "Disable the API unless authentication is configured for Flower"

If at all, the API access should be disabled by default, and enabled by a parameter. Authentication and authorization can be done on multiple levels (physical, network, HTTP, application), so functionalities should not rely on auth being enabled in the app itself.

**Comment by adampl** [comment]
@alexanderaltanis  It's not rude to point out that something is stupid, when it actually is stupid. Advice from a security audit shouldn't be always taken literally, because security auditors don't care about functionality and usability and separation of responsibility. If some company exposes unprotected Flower to the Internet, then it's entirely their fault and their problem.

**Comment by tprynn** [comment]
@adampl I'm the person who gave that advice initially and I'll point out that I actually [submitted a PR](https://github.com/mher/flower/pull/1216) along with my original post which does exactly what you asked for (gives you a config option to enable the API without authentication).

Anyway I didn't take that personally but I'm unsubscribing from this thread as I don't think I have much to offer here! I think the core issue is that the maintainer is unfortunately not very active (I hope *they* don't take that personally as I know it's hard). As a community it might be worth exploring creating a fork, or reaching out to the owner to add some additional mainteiners.

**Comment by adampl** [comment]
@tprynn Thanks, and I'm glad you don't take it personally. It's sad that your PR was rejected, while the bad one was blindly accepted...

**Comment by esauser** [comment]
@mher when can we expect a release? We've been pinned to 1.0.0 since this was broken in 1.1.0.

**Comment by adampl** [comment]
@mher Why is this closed? AFAIK the issue isn't resolved.

**Comment by heathf** [comment]
Agreed with @adampl. We're on 1.2.0 and are experiencing this issue too

**Comment by wojiazaiyugang** [comment]
same issue

**Comment by rajkumarvenkatasamy** [comment]
Hi @mher I think the issue is fixed in master branch. Could you let us know when can we expect a tag release with the fix for this issue ?

**Comment by rajkumarvenkatasamy** [comment]
Hi @adampl Please refer this link for relevant commit : https://github.com/mher/flower/commit/72eb05a38e9dc2dbc3ce98e948d542e9274cc5a9 

I can see now that this commit has been included as part of the tag release v2.0.1  and v2.0.0. FYI, I didn't test this fix myself yet. 

Thanks!

**Comment by adampl** [comment]
@rajkumarvenkatasamy It still doesn't fix the issue. Not only the message:

> API is not available when auth is enabled

does not make sense, but the whole concept of using auth config as a condition.

There should be a separate option to control the availability of the API.

**Comment by Kesha2447** [comment]
Will there still be no solution?

**Comment by Kesha2447** [comment]
The exception is called in the file api/__init__.py
![image](https://github.com/mher/flower/assets/56413584/3be704c7-26b7-4617-b50c-e59d26b5b9fb)
To get rid of the error, it is enough to comment out this code
![image](https://github.com/mher/flower/assets/56413584/f955f1bd-c7fe-4e28-8b73-4cdc522df6e3)
If you are desperate to wait for a solution, you can change this code in the library or using the monkey patch
