### ISSUE TITLE
Configuring flower in aws EC2 instance

### ISSUE THREAD

**Issue by thangaraj535** [mher/flower#1236]
First of all, I would like to thank the mher and contributors for giving us such a wonderful tool. My concern is to configure the flower tool in AWS ec2 instance and already celery configured with supervisord. Much helpful if you provide me with information or guidance on configuring the EC2 instance.

**Comment by mher** [comment]
Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use StackOverflow.com for general usage questions instead.
