### ISSUE TITLE
Provide option for custom GitLab domain for GitLab Auth via environment variables.

### ISSUE THREAD

**Issue by chriswachira** [mher/flower#1237]
I've found myself in a situation where I needed to configure GitLab authentication from a self-hosted GitLab instance. The global `gitlab.com` is baked into the GitLab Auth login handler code and it'd be good to have an option of specifying a custom GitLab domain via an environment variable to use for authentication.

For example:
```
export FLOWER_GITLAB_AUTH_DOMAIN="gitlab.mycompany.com"
```

The GitLabLoginHandler class will check for the custom domain from the environment and default to `gitlab.com` if none is present.

I am currently working on this. Let me know your suggestions.

**Comment by mher** [comment]
`FLOWER_GITLAB_OAUTH_DOMAIN` support was added
