### ISSUE TITLE
Project Activity

### ISSUE THREAD

**Issue by themanifold** [mher/flower#1241]
Hello,

I guess I'm going to be that guy.

I'm wondering if anyone is using a more active fork as I feel like the main branch is just too slow.

If such a fork does not exist, then is there appetite to create one as I feel like there is a lot of scope for small changes and obviously big changes waiting in the wings.

This is a really great project and my work has come to depend on it and I would hate to see it languish.

Thanks.

**Comment by mher** [comment]
https://github.com/mher/flower/discussions is a better place for this. Issues are for bug reports and enhancement requests
