### ISSUE TITLE
Hide "Running without authentication" warning

### ISSUE THREAD

**Issue by adnathanail** [mher/flower#1245]
**Is your feature request related to a problem? Please describe.**
I have Flower running behind Nginx so I have implemented Basic Auth through nginx, as recommended here https://github.com/mher/flower/blob/ce5f0de7b25bc42ef9fb909340ba9fe9c8f903f0/docs/reverse-proxy.rst

This means I am not passing `basic_auth` or `auth` arguments, so whenever I start it up I get a warning `"Running without authentication"`

**Describe the solution you'd like**
I think the warning is useful, in case you forget, but would it be possible to add an addition option `no_auth_required` or something, so that I can acknowledge to Flower that I have my own authentication solution in place?

**Comment by mher** [comment]
`Running without authentication` warning was removed from the latest version
