### ISSUE TITLE
Missing documentation on Metrics

### ISSUE THREAD

**Issue by kaizendae** [mher/flower#1259]
The following metrics of flower do show on prometheus but aren't documented, I do not know what they represent.

```
flower_task_runtime_seconds_sum
flower_task_runtime_seconds_count
```

this expression `rate(flower_task_runtime_seconds_sum[5m]) / rate(flower_task_runtime_seconds_count[5m])` is used on [example dashboard in this repo](https://github.com/mher/flower/blob/master/examples/celery-monitoring-grafana-dashboard.json) but not documentation is provided.

**Comment by adampl** [comment]
@kaizendae The `_sum` and `_count` suffixes are integral part of the Histogram type, which is used for the `flower_task_runtime_seconds` metric:
https://prometheus.io/docs/concepts/metric_types/#histogram
