### ISSUE TITLE
celery flower s3 public file url or sqlalchemy database url

### ISSUE THREAD

**Issue by nirob-appsbee** [mher/flower#1260]
**Describe the bug**
**i cannot able to add s3 file url or sqlalchemy databse url like this**

/home/venv/bin/celery -A celery_worker.celery flower --port=5555 --persistent=True  --db=https://cloudsignpro-static.s3.amazonaws.com/flower.db --state_save_interval=5

or 

/home/venv/bin/celery -A celery_worker.celery flower --port=5555 --persistent=True  --db=mysql+pymysql://root:123456@db:3306/flask_cloudsignpro

**To Reproduce**
getting this error ===============
File "/home/venv/lib/python3.10/site-packages/flower/events.py", line 142, in __init__
cloudsignpro-flower  |     state = shelve.open(self.db)
cloudsignpro-flower  |   File "/usr/lib/python3.10/shelve.py", line 243, in open
cloudsignpro-flower  |     return DbfilenameShelf(filename, flag, protocol, writeback)
cloudsignpro-flower  |   File "/usr/lib/python3.10/shelve.py", line 227, in __init__
cloudsignpro-flower  |     Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
cloudsignpro-flower  |   File "/usr/lib/python3.10/dbm/__init__.py", line 95, in open
cloudsignpro-flower  |     return mod.open(file, flag, mode)
cloudsignpro-flower  | _dbm.error: [Errno 2] No such file or directory: 'https://cloudsignpro-static.s3.amazonaws.com/flower.db'

**Expected behavior**

**Screenshots**
screenshot are in attachment

**System information**
ubuntu 22.04 docker image

![Screenshot from 2023-01-19 11-32-39](https://user-images.githubusercontent.com/52662304/213367699-f5558000-b3af-428a-9f45-87fd91e13a0d.png)
![Screenshot from 2023-01-19 11-33-07](https://user-images.githubusercontent.com/52662304/213367729-2282c46b-9930-41ce-8f11-f566b66600da.png)

**Comment by mher** [comment]
`--db` should be local file name
