### ISSUE TITLE
Rendered HTML documentation is using an outdated command

### ISSUE THREAD

**Issue by mashour-spire** [mher/flower#1264]
**Describe the bug**

[Here](https://flower.readthedocs.io/en/latest/prometheus-integration.html#start-flower-monitoring) you can find that the docs is using the outdated command order  
`celery flower -A tasks --broker=redis://localhost:6379/0`  
which will not work correctly , rather than the current one  
`celery -A tasks --broker=redis://localhost:6379/0 flower`   [here](https://github.com/mher/flower/blob/master/docs/prometheus-integration.rst#start-flower-monitoring) 
as it appears that the html rendered docs are out of sync with the `.rst` files

**Comment by mher** [comment]
Updated, thanks for reporting
