### ISSUE TITLE
Any way to disable Google OAuth completely?

### ISSUE THREAD

**Issue by paulocheque** [mher/flower#1265]
**Is your feature request related to a problem? Please describe.**
I can't use Flower anymore because of a bug related to Google OAuth. Without auth or with basic auth it get a 401 error.

**Describe the solution you'd like**
Any way to disable Google OAuth completely?

**Comment by mher** [comment]
Try https://github.com/mher/flower/commit/9b7c81a7afc9b391779d6c5237499628fe129480. It should fix the issue
