### ISSUE TITLE
Docs: examples regarding --auth flag do not work anymore

### ISSUE THREAD

**Issue by fiksn** [mher/flower#1271]
**Describe the bug**

The literal examples from 
https://github.com/mher/flower/blob/master/docs/auth.rst
like `celery flower --auth=.*@example\.com` do not work anymore with 1.2.0 version. Correct syntax is now apparently
`celery flower --auth=.*@example.com` (no escaping of the dot in domain part).

**To Reproduce**

Start flower with --auth flag and observe that you get `Access denied to '...'. Please use another account or ask your admin to add your email to flower --auth.`

**Expected behavior**

Documentation should be in sync with actual behaviour.

**System information**
```
flower   -> flower:1.2.0 tornado:6.2 humanize:4.6.0
software -> celery:5.2.7 (dawn-chorus) kombu:5.2.4 py:3.10.10
            billiard:3.6.4.0 redis:4.3.4
platform -> system:Linux arch:64bit
            kernel version:5.15.0-1023-aws imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled

deprecated_settings: None
```

**Comment by fjcapdevila** [comment]
Same problem here. I was able to fix it by un-escaping the dot in the domain part.

**Comment by mher** [comment]
Updated the docs
