### ISSUE TITLE
How to pass RabbitMQ ca, certfile and keyfile for SSL auth when run flower in docker (https://hub.docker.com/r/mher/flower)

### ISSUE THREAD

**Issue by zagr0** [mher/flower#1279]
**Is your feature request related to a problem? Please describe.**
We have rabbitmq broker with mtls authentication mandatory, the broker url can be passed with CELERY_BROKER_URL env variable. Are there variables I can use to pass SSL keyfile, certfile and ca certificate?

**Describe the solution you'd like**
There would be really great to have corresponding ENV variables for ca, cert and key files for RabbitMQ SSL mutual authentication

**Comment by mher** [comment]
You can use celery application configuration with docker

```
docker run -v /project:/data -p 5555:5555 mher/flower celery --app=tasks.app flower
```
