### ISSUE TITLE
Can we get a new pypi release following the jquery patch?

### ISSUE THREAD

**Issue by mmdanziger** [mher/flower#1288]
**Is your feature request related to a problem? Please describe.**
Flower is still flagged as vulnerable because of the jquery vulnerabilities. This is fixed in https://github.com/mher/flower/pull/1280 but the pypi version is not updated.

**Describe the solution you'd like**
Push a new release to pypi

Of course, I could install from github main branch, but i would really prefer to use a package manager with versioning etc

**Comment by mher** [comment]
https://pypi.org/project/flower/2.0.0/
