### ISSUE TITLE
--auth flag example in doc is not working

### ISSUE THREAD

**Issue by ggorge-etiqa** [mher/flower#1289]
**Describe the bug**
In the [latest docs](https://flower.readthedocs.io/en/latest/auth.html) it's described how to use the `--auth` flag:

```
--auth=.*@example\.com
```

But email `test@example.com` is not matched. It only matches with `--auth=.*@example.com`.

I think the docs should be updated.

**Comment by mher** [comment]
Updated the docs, thanks for reporting
