### ISSUE TITLE
Rapid memory leaks in version 2.0.0

### ISSUE THREAD

**Issue by estraph** [mher/flower#1305]
**Describe the bug**
I upgraded from version 1.2.0 to 2.0.0 yesterday. There have always been slow memory leaks but since the upgrade, RAM seems to spike quickly and hit hard limits faster:

Note that we barely use flower, it's just there in case we wish to investigate so there are virtually 0 users in both cases.

**To Reproduce**
Run flower 2.0.0 and watch RAM consumption.

**Expected behavior**
RAM utilisation does not increase so rapidly and stays steady over longer periods of time, especially if there is no active usage.

**Screenshots**
![image](https://github.com/mher/flower/assets/22151295/e0bd25ca-cd5b-467d-88ce-bdf5d99a7683)

**System information**
I don't have this available right now. It's flower version 2.0.0 on python 3.11.3, running in an x86 AWS Fargate container (0.5 GB RAM per container).

**Comment by estraph** [comment]
The increases in RAM seem to be correlated to when celery workers process tasks. So it would seem flower is doing something in memory based on events from the (in my case Redis) broker as they come through, until it runs out of memory. Is that expected behaviour?

**Comment by mher** [comment]
The default value of max_tasks in version 2.0 has changed from 10000 to 100000. Version 2.0 now keeps more tasks in memory. However, you can still override the default value.

**Comment by estraph** [comment]
Just to close the loop here, I set the `max_tasks` to `50000` and now no longer see it hitting the memory limit; in my case it has stabilised around 80%. Thanks @mher
