### ISSUE TITLE
Hyperlink to tasks page in workers view does not respect the url prefix

### ISSUE THREAD

**Issue by estraph** [mher/flower#1307]
**Describe the bug**
On the workers overview page, there is a hyperlink to the total tasks which - unlike the main navigation menu - does not consider the [`url_prefix` configuration](https://flower.readthedocs.io/en/latest/config.html?highlight=url_prefix#url-prefix). Clicking it returns a 404 error.

**To Reproduce**
1. Define a custom `url_prefix`, e.g. `foo`
1. Navigate to `/workers` page
1. Notice that the main navigation `tasks` link targets `/foo/tasks`
1. Notice that the hyperlink on the total sum of tasks targets `/tasks` (without `/foo`)
1. Clicking the total sum link returns a 404 error

**Expected behavior**
When setting a `url_prefix` I would expect every hyperlink to flower pages to include the prefix in the URLs and not 404.

**Screenshots**
In this example, I have a `url_prefix` of `flower`. Notice that the main nav respects this and works as expected:
<img src="https://github.com/mher/flower/assets/22151295/bb2356a8-7c1b-439b-81e9-0d09d2c24ea8" width=400px/>

However, the other link on the workers page does not:
<img src="https://github.com/mher/flower/assets/22151295/22ab2ac5-09a7-4dcc-87fe-e8e3448e15f6" width=400px />

**System information**
This is flower 2.0.0 running on python 3.11.3 in an official python docker container (x86).

**Comment by mher** [comment]
Thanks for the bug report. Feel free to open a pull request.

**Comment by mvaled** [comment]
This was fixed in https://github.com/mher/flower/pull/1297

**Comment by estraph** [comment]
Very cool - thank you @mher @onyx-flame 🚀
