### ISSUE TITLE
url-prefix is not picked up in the footer links

### ISSUE THREAD

**Issue by deepchatterjeeligo** [mher/flower#1316]
**Describe the bug**
![image](https://github.com/mher/flower/assets/23223278/84f99c4e-ee11-48a7-a531-2917493578a3)

The links in the footer lead to 404 when launching flower with `--url-prefix`.

**To Reproduce**

1. Launch flower with the `--url-prefix`. Here `proj` is any representative celery project.
```
celery -A proj flower --url-prefix=flower
```
Putting a trailing slash (as mentioned in #1207) does not help. Using ` --url-prefix=flower/` has the same behavior.

This starts flower at ` http://0.0.0.0:5555/flower/`
2. Launch a few tasks from the celery project, so that there are non-zero processed tasks
3. Click on (or hover over) the number of processed tasks (in the above case, the value 10)
4. This redirects to ` http://0.0.0.0:5555/tasks` and gives a 404 (screenshot below).

**Expected behavior**
It should have redirected to `http://0.0.0.0:5555/flower/tasks`. The url-prefix is missing.

**Screenshots**
![image](https://github.com/mher/flower/assets/23223278/fa3dc805-6ddc-4f81-a395-3aec8979a28a)

**System information**
Output of `python -c 'from flower.utils import bugreport; print(bugreport())'` command

```
flower   -> flower:2.0.0 tornado:6.3.2 humanize:4.7.0
software -> celery:5.2.7 (dawn-chorus) kombu:5.2.4 py:3.10.8
            billiard:3.6.4.0 py-amqp:5.1.1
platform -> system:Linux arch:64bit, ELF
            kernel version:5.15.0-78-generic imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

deprecated_settings: None
```

**Comment by mher** [comment]
Fixed by https://github.com/mher/flower/pull/1297
