### ISSUE TITLE
Using virtual host in broker URI with rabbitmq causes errno 104

### ISSUE THREAD

**Issue by ntucker** [mher/flower#152]
I use the same url with no virtual host and everything works fine. However I use a virtual host that is known to work and I get 

[E 131121 01:39:40 events:94] Failed to capture events: '[Errno 104] Connection reset by peer', trying again in 2 seconds.
[E 131121 01:39:40 state:128] Failed to inspect workers: '[Errno 104] Connection reset by peer', trying again in 2 seconds

Yes, the user has permission for both default and the specified virtual host.

**Comment by paulcalabro** [comment]
If you don't mind me asking, what was the solution to this? I'm experiencing the same issue.

**Comment by davidalpert** [comment]
@ntucker think I just ran into this issue; did you get it resolved?

**Comment by davidalpert** [comment]
in case this helps anyone else, I found this example in the ["Connecting to Broker](http://rubyamqp.info/articles/connecting_to_broker/) guide of the Ruby AMPQ Gem:

```
The vhost is obtained from the first segment of the path, with the leading slash removed. The path should contain only a single segment (i.e, the only slash in it should be the leading one). If the vhost is to include slashes or other reserved URI characters, these should be percent-escaped.

Here are some examples that demonstrate how AMQP::Client.parse_connection_uri parses out the vhost from connection URIs:

"amqp://dev.rabbitmq.com"            # => vhost is nil, so default ("/") will be used
"amqp://dev.rabbitmq.com/"           # => vhost is an empty string
"amqp://dev.rabbitmq.com/%2Fvault"   # => vhost is "/vault"
"amqp://dev.rabbitmq.com/production" # => vhost is "production"
"amqp://dev.rabbitmq.com/a.b.c"      # => vhost is "a.b.c"
"amqp://dev.rabbitmq.com/foo/bar"    # => ArgumentError
```

I have confirmed this with my own system.

Given a vhost of `zzz` you have to pass `/zzz` as the vhost name in the ampq URI, so you actually wind up URL-encoding that and passing `%2Fzzz` like this:

```
amqp://{user}@{pass}:dev.rabbitmq.com/%2Fzzz
```

which creates or accesses queues in the `/zzz` virtual host.

**Comment by ntucker** [comment]
This was way too long ago to remember. But given the history here I would guess mher's comment about user/pass was correct. Although that seems really silly to miss.

**Comment by kimosabi77** [comment]
@davidalpert Thanks for posting your fix, saved me some hair pulling

**Comment by lerdem** [comment]
@davidalpert Thank you!

**Comment by CumpsD** [comment]
This is pure evil:

```
"amqp://dev.rabbitmq.com"            # => vhost is nil, so default ("/") will be used
"amqp://dev.rabbitmq.com/"           # => vhost is an empty string
```

**Comment by davidalpert** [comment]
agreed that is opposite from what I might expect, though I can understand or at least imagine the parsing rules that would result in that behavior

**Comment by CumpsD** [comment]
I spend 2 hours debugging a Shovel issue because of this :) I had a trailing slash and the logs simply said `vhost  not found` (note the multiple spaces)

If it said `vhost "" not found` I probably would have figured it out sooner :)
