### ISSUE TITLE
Ability to create new task

### ISSUE THREAD

**Issue by carlskii** [mher/flower#162]
Hi,

Just wondering if there were any plans to add a feature for listing the tasks that have been defined and calling new tasks from the Flower UI. I know its possible to call a new task the API but it would be quite nice to have something similar to Swagger (https://github.com/wordnik/swagger-ui) here. 

This could be used with the API to provide a nicely abstracted view of the available task definitions. 

Regards,

Carl

**Comment by astewart-twist** [comment]
+1

**Comment by davschne** [comment]
I too would love to have this feature. @mher and/or other maintainers, would you consider a PR to implement this? The web UI is a great feature of this project. It would be wonderful if it allowed more of the admin tasks defined by the API.

**Comment by mher** [comment]
There are no plans to work on this feature at the moment until someone decides to contribute to the project.
