### ISSUE TITLE
Can't adjust the rate limit of a task

### ISSUE THREAD

**Issue by erikcw** [mher/flower#168]
I have a task that is configured with a rate limit of "12/m".  I just tries to change it using the flower UI to "1/s" and got this error:

`Error! Invalid argument '1/s' of type 'int'`

If the input value needs to be an integer, than some documentation should be added to the page clarifying what the value of the `int` represents.  Does a value of `1` change the rate limit for the task to once per second, once per minute, etc...

After entering a plain integer, Flower shows a green flash message saying that it was accepted.  But the old rate limit value persists next to the task.

**Comment by markstos** [comment]
The documentation issue has not been fixed. The doc-bug was: 

"If the input value needs to be an integer, than some documentation should be added to the page clarifying what the value of the int represents. "

I find the unit of the rate-limit is still not documented here:

http://flower.readthedocs.org/en/latest/api.html?highlight=rate%20limit#post--api-task-rate-limit-(.+)

Under "Query Parameters", the "ratelimit" parameter is not documented.
