### ISSUE TITLE
Flower web interface empty

### ISSUE THREAD

**Issue by pepijndevos** [mher/flower#181]
I'm trying to run Flower to monitor a Celery cluster on Heroku, and a Redis instance in development.

Neither of them shows anything at all. Just tabs with nothing much at all.

I start flower with

```
flower --port=55957 --broker=amqp://user:pass@big-avens-14.bigwig.lshift.net:10647/uovBHtQdqEkP --broker_api=https://user:pass@bigwig.lshift.net/management/22282/api/ --basic_auth=pepijn:blabla`
```

No errors are produced. Just a message that i's connected.and some time-drift warnings.

I start my workers like so:

```
celery worker --app=spider.config.app --autoscale=500,10 --pool=gevent --events
```

After adding the `--event` the "Tasks" tab started showing stuff. However, the other tabs are still completely empty.

![screenshot - 010914 - 13 49 08](https://f.cloud.github.com/assets/168609/1877668/73cc8e1a-792c-11e3-990b-2efc68bd90b0.png)

**Comment by Neulana** [comment]
@mher However, the version 0.9.2 still has this problem.
