### ISSUE TITLE
UX suggestions

### ISSUE THREAD

**Issue by arnists** [mher/flower#194]
I hope to have time to devote to this project in the summer, I really like what it offers as a management tool for Celery.  These features would in my opinion improve it's usefulness tremendously.

# /tasks
* while columns are static, should include timestamps (quick)
* columns should be decided by a setting (better)
* columns should be sortable
* time filtering
* bulk revoke from list-view

# /monitor
* async data from pageview (history)
* task filtering

**Comment by mozillazg** [comment]
@sandeepgk1989 
2) flower use CELERY_TIMEZONE to get timezone.

**Comment by daniel-cohen** [comment]
+1 on sorting

**Comment by meteozond** [comment]
+1 for pagination

**Comment by mher** [comment]
Most of the features requested here are implemented in the master version. Please try it.
