### ISSUE TITLE
Missing source for Javascript files

### ISSUE THREAD

**Issue by bdrung** [mher/flower#196]
There are a bunch of Javascript files in minified form (*.min.js). Please ship the unminified version of it in your repository.

I want to create an official Debian package for flower, but a Debian source package has to ship all sources in the _preferred form for modification_. Minified Javascript is not the preferred form for modifications.

I found all Javascript sources, except d3.layout.min.js. Where does d3.layout.min.js come from?

**Comment by pabs3** [comment]
This issue was fixed in commit 201f2407f3eba951e3ad95d52f5a3e94c9438057, which removes the 
monitor page in favour of the Prometheus integration.
