### ISSUE TITLE
task logging

### ISSUE THREAD

**Issue by chadrik** [mher/flower#211]
I would really love to be able to see task logs from within flower.

The ideal solution would:
- be easy to install and setup
- be optional?
- work as a handler for python's logging module
- provide real-time updates to flower when viewing that task's details
- keep past logs for a configurable amount of time

A few relevant projects:
- [logstash](http://logstash.net)
- [sentry](https://github.com/getsentry/sentry)
- [scribe](https://github.com/facebook/scribe)

Do you feel that this feature fits within the scope of Flower, and if so do you have any insight on how you would implement it?

chad.

**Comment by daniel-cohen** [comment]
+1 On this feature

**Comment by ptylenda** [comment]
+1, centralized logging for different celery machines would be great. Currently similar feature is available in Airflow, also when using CeleryExecutor, but that does not solve task logging for regular celery tasks

**Comment by ocervell** [comment]
Bump ! This would be a great feature to have.

**Comment by gabriellima** [comment]
Indeed a really nice feature to have. Today, I make use of the return statement of tasks to have a simple feedback, at least.

**Comment by gmrukwa** [comment]
Is there anything done in this matter so far?

**Comment by PasqualePuzio** [comment]
Totally agree. This would be an awesome feature. Looking forward to it :)

**Comment by jheld** [comment]
The celery events system is how flower gets its data. Either we could semi-abuse this, or yes, be able to pull from an external logger system using its API (and possibly caching on completion/failure). Latter is maybe an easier thing (integrate with the logging infra that a given project uses).

**Comment by mher** [comment]
There are no plans to work on this feature at the moment until someone decides to contribute to the project.

**Comment by hadpro24** [comment]
Hello guys are you work on this features ?

**Comment by frruit** [comment]
I would also like that this features is one day part of flower

**Comment by r4881t** [comment]
End of 2024 and I would still want to see this happening. @mher - may you tell us a little bit about how to get this done and maybe someone from my team can pick it up?

**Comment by onursoyer** [comment]
I think this feature request for task logging is very useful and would enhance Flower's functionality. Let's reconsider adding this enhancement. @mher
