### ISSUE TITLE
Support for Viewing and Revoking Celery Groups

### ISSUE THREAD

**Issue by edwardotis** [mher/flower#225]
We started using Celery Groups recently, and it would be very useful if these features were available in flower:
- the group task showed up in tasks view
- the group task could be revoked (thus propagating the revoke to all the other subtasks)

http://celery.readthedocs.org/en/latest/userguide/canvas.html

**Comment by frasergraham** [comment]
+1 for this. I just started making more complex canvas operations and being able to see that in flower would be awesome. A Dot graph view would make me even happier.

**Comment by mher** [comment]
There are no plans to work on this feature at the moment until someone decides to contribute to the project.
