### ISSUE TITLE
support sslify

### ISSUE THREAD

**Issue by edwardotis** [mher/flower#240]
Problem:
Flower dumps some unencrypted, sensitive data across the web when viewing our task details.

Solution:
We use flower on heroku, so we get SSL for free: https://myflowerinstall.herokuapp.com
We use basic auth already.
However, most of our users are not reliably typing 'https:' into their address bar.
It would be great is we could specify that SSL is required at cmd line  of flower and automatically sslify flower so that our sensitive data is not passed around the web unencrypted.

https://github.com/rdegges/django-sslify
https://pypi.python.org/pypi/django-sslify/0.2.3

**Comment by mher** [comment]
There are no plans to work on this feature at the moment until someone decides to contribute to the project.
