### ISSUE TITLE
There is no data when using redis broker.

### ISSUE THREAD

**Issue by jaggerwang** [mher/flower#253]
celery report
software -> celery:3.1.13 (Cipater) kombu:3.0.21 py:3.4.0
            billiard:3.3.0.18 py-amqp:1.4.5
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled

redis-server --version
Redis server v=2.8.9 sha=00000000:0 malloc=jemalloc-3.2.0 bits=64 build=6183a7cf6dbec67f

pip list
amqp (1.4.5)
anyjson (0.3.3)
billiard (3.3.0.18)
celery (3.1.13)
cement (2.2.2)
certifi (14.05.14)
flower (0.7.2)
hiredis (0.1.4)
humanize (0.5)
kombu (3.0.21)
msgpack-python (0.4.2)
Pillow (2.5.1)
pip (1.5.4)
pycket (0.3.0)
pymongo (2.7.2)
pytz (2014.4)
redis (2.10.1)
requests (2.3.0)
setuptools (2.1)
tornado (4.0)
WTForms (2.0.1)
wtforms-tornado (0.0.1)

supervisord.conf
[program:lusir-server-celery-worker-storage]
command=celery worker -A celeryapp.celeryapp -l info -E -Q storage -I lusir.storage.task -n storage@%%n
directory=%(ENV_HOME)s/projects/longyuan/lusir-server/src
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=30

[program:lusir-server-celery-worker-message]
command=celery worker -A celeryapp.celeryapp -l info -E -Q message -I lusir.message.task -n message@%%n
directory=%(ENV_HOME)s/projects/longyuan/lusir-server/src
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=30

[program:lusir-server-celery-worker-face]
command=celery worker -A celeryapp.celeryapp -l info -E -Q face -I lusir.face.task -n face@%%n
directory=%(ENV_HOME)s/projects/longyuan/lusir-server/src
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=30

[program:lusir-server-celery-worker-star]
command=celery worker -A celeryapp.celeryapp -l info -E -Q star -I lusir.star.task -n star@%%n
directory=%(ENV_HOME)s/projects/longyuan/lusir-server/src
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=30

[program:lusir-server-celery-flower]
command=flower --address=0.0.0.0 --port=8110 --broker=redis://lusir-redis-test:6379/12 --broker_api=redis://lusir-redis-test:6379/12 --url_prefix=flower
directory=%(ENV_HOME)s/projects/longyuan/lusir-server/src
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=30

**Comment by ivanvenosdel** [comment]
I ran into this one as well. To more clearly some the limitation up for others who may come across this. Flower requires access to the code base containing your tasks. So if you are trying to deploy flower somewhere without wanting to pull down the rest of your code base that won't work.

@mher I would like to see if I can get this working for others. So I am curious on your thoughts on where I may have the best luck in directing my efforts. I see that you linked the dashboard branch. Is that an abandoned branch or a future direction of the code? If it's abandoned how feasible do you think it would be for me to look at ways to get master to work without having a local copy of the project's task code?

**Comment by ivanvenosdel** [comment]
I get the same behaviour with the dashboard branch (and using the timeout). As far as I can tell the dashboard branch also relies on Celery to get the tasks.
https://github.com/mher/flower/blob/dashboard/flower/command.py#L116

That is what I think requires flower to have access to the project code base as it will only work if the tasks get registered with celery (e.g. the code base is available and the celery module is run).

**Comment by schmod** [comment]
This seems to still be an issue?  Is it really not possible to run flower outside of the process that runs my tasks?

**Comment by xujy** [comment]
@schmod any luck figuring this one out?

**Comment by schmod** [comment]
I "figured it out" in the sense that I determined that Flower is basically useless when using the Redis broker, as it depends on a whole bunch of functionality that isn't implemented on the celery side of things (most of Celery's `inspect` commands also don't work with Redis)
