### ISSUE TITLE
Monitor page: Graphs for 'Succeeded tasks', 'Failed tasks' and 'Task times' are empty

### ISSUE THREAD

**Issue by tjanez** [mher/flower#257]
I'm running Flower on a Debian 7 machine:

```
$flower --version
0.7.2
3.1.13 (Cipater)
flower   -> 0.7.2
software -> celery:3.1.13 (Cipater) kombu:3.0.21 py:2.7.3
            billiard:3.3.0.18 py-amqp:1.4.5
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled
```

The machine is actually a `libvirt` virtual machine.
To access Flower, I go to `http://192.168.122.181:5555/monitor` through my host machine's web browser. Here is the screenshot with the empty graphs for 'Succeeded tasks', 'Failed tasks' and 'Task times':

![celery flower monitor bug](https://cloud.githubusercontent.com/assets/2518544/3810520/26672384-1c91-11e4-8378-8f842bc47bff.png)

**Comment by sursma** [comment]
@dantezhu Adding the line 124 (it is in exception) does not help.  flower doesnt start
