### ISSUE TITLE
Bug report: flower web interface reports "Unknown task '<worker name>'

### ISSUE THREAD

**Issue by chisleu** [mher/flower#262]
The flower web interface reports "Unknown task '<worker name>'" instead of "Unknown task '<task name>' through the web interface.

The output at the command line shows: 404 POST /api/task/rate-limit/<worker name>

I tried my best to figure out the problem before creating the issue.

[root@localhost ~]# flower --version
0.7.2
3.1.13 (Cipater)

[root@localhost ~]# ls ~/rabbitmq-server*
/root/rabbitmq-server-3.3.0-1.noarch.rpm

If I can help in any way, please let me know.

**Comment by diegopedroso1** [comment]
@chisleu Flower does not see as tasks and ended up taking the time limit when it opens my worker, do you know if it has any relationship with the parameter -A?
