### ISSUE TITLE
During stopwait with pending jobs, running count goes to 0 incorrectly

### ISSUE THREAD

**Issue by zachmullen** [mher/flower#265]
I run `celery multi stopwait worker --pidfile=./.celerylock` on one of my worker nodes to bring it down and finish its current running task, which takes several minutes to complete. On the `/tasks` view, the task still correctly shows as "Started", but on the `/workers` view, its corresponding worker shows "0" in the "Running Tasks" column even though there is still one running task. This is also reflected in the Tasks tab when I drill down into the view for that worker; it shows the job as completed even though it is still running.

ping @mgrauer

**Comment by mher** [comment]
I'm closing this issue. There were many improvements in dashboard. Please open new tickets if you experience problems.
