### ISSUE TITLE
graph data persistency

### ISSUE THREAD

**Issue by tbarbugli** [mher/flower#27]
Hi,
Did I miss it or all real time data celery fetches from workers is not persistent on flower end ?

Tommaso

**Comment by mgingras** [comment]
@mher When you navigate to /monitor is the expected behaviour that it will show you past executed tasks or is it only real updated in real time?

Thanks.

**Comment by caiofbpa** [comment]
I have the same question: does persistent mode have any effect on the monitor's charts?

**Comment by gtangquri** [comment]
@mher Is there a way where I can edit the contents of `flower.db` such that if the file gets too big then I can edit it to save N newest tasks and delete the rest? I'm not sure whether `--max_tasks` will accomplish this

**Comment by shuigupta** [comment]
@mher I am new to flower and I am not able to figure out that from where does flower read celery tasks/events to show on dashboard? If I am not setting persistence flag as True that means there is no database file being created, then where does it read the data from?

**Comment by sshishov** [comment]
Flower reads data from events. When celery got message from broker, it fires the events: `received`, `started`, `processed` and flower listenings for these events and update it's internal state accordingly and represent it using API: dashboard, tasks, monitors etc... Therefore if celery started and flower not, then when you start the latter, you do not get previous data as flower process events in real time.

To keep data about workers and counters, I tried to persist counter data in this PR: https://github.com/mher/flower/pull/926
Dashboard now became restored. Will check monitor as well later on

**Comment by ilyakatz** [comment]
Any update on PR #926? would be great to see this data persisted

**Comment by mher** [comment]
Monitor tab is deprecated, use Prometheus instead.
