### ISSUE TITLE
Celery Flower Is Able To Shutdown Worker But Unable To Restart It

### ISSUE THREAD

**Issue by ChillarAnand** [mher/flower#271]
I have installed Celery, Django-Celery, Kombu & Flower.

Celery Flower is monitoring fine. It is able to shutdown worker(s) but unable to restart them.

Flower responses:

[I 140903 15:49:12 web:1856] 200 GET / (127.0.0.1) 77.49ms
[I 140903 15:49:13 web:1856] 304 GET /static/img/glyphicons-halflings.png (127.0.0.1) 17.01ms
[I 140903 15:54:27 web:1856] 304 GET / (127.0.0.1) 2.91ms
[I 140903 15:54:33 control:62] Shutting down 'celery@ftp_fastq' worker
[I 140903 15:54:33 web:1856] 200 POST /api/worker/shutdown/celery%40ftp_fastq (127.0.0.1) 4.03ms
[I 140903 15:54:40 control:103] Restarting 'celery@ftp_fastq' worker's pool
[E 140903 15:54:41 control:112] []
[W 140903 15:54:41 web:1856] 403 POST /api/worker/pool/restart/celery%40ftp_fastq

**Comment by jacobbridges** [comment]
Sorry to unearth this issue @mher, but I am experiencing the same issue as @ChillarAnand.

I have an AWS instance with Celery (3.1.17), RabbitMQ (3.5.0), and Flower (0.9.0-dev) installed. I have several celery workers running (these workers are running correctly), and I can monitor their task results through Flower. That part is working fine and dandy.

My problem is after I successfully shutdown a worker from the Flower interface, I cannot restart the worker through the interface. The error from the UI is "Unknown reason", and the console output is: 

```
[I 150402 19:45:20 control:146] Restarting 'job@vhost' worker's pool
[E 150402 19:45:21 control:154] []
[E 150402 19:45:21 control:60] Failed to extract error reason from '[]'
[W 150402 19:45:21 web:1825] 403 POST /api/worker/pool/restart/job%40vhost (XX.XXX.XXX.XX) 1012.18ms
```

I have `CELERYD_POOL_RESTARTS=True` in each worker's app.conf.update. Any ideas?

**Comment by mher** [comment]
Have you checked the workers log?

**Comment by jacobbridges** [comment]
Yes, I have checked the logs for each worker. Nothing suspicious. The workers respond to the shutdown then are nonresponsive to the restart command.

```
[2015-04-03 17:07:28,922: INFO/MainProcess] Task ScrapePartners[ff2c4f0b-1fc0-445c-be6e-2c9a12ac12b8] succeeded in 0.138599127997s: 'Finished! (Received a non-JSON response)'
[2015-04-03 17:07:38,701: WARNING/MainProcess] Got shutdown from remote
[2015-04-03 17:07:38,712: INFO/MainProcess] beat: Shutting down...
```

**Comment by mher** [comment]
I'd suggest to try restarting from the python shell and see the response. See https://celery.readthedocs.org/en/latest/userguide/workers.html#pool-restart-command for instructions

**Comment by jacobbridges** [comment]
I was tinkering with this issue more today..and had an idea. Could the issue be with Linux permissions?

I am running the celery workers under a linux user "celery" which from etc/passwd has the permissions of `celery:x:107:1001::/data/app:/bin/false`. And I am running Flower with sudo privileges. 

Since Celery does not like being run with sudo access, could the problem be that I am running Flower as sudo?

**Comment by zinwalin** [comment]
@jacobbridges grant current user with root privileges.
