### ISSUE TITLE
Random task loss

### ISSUE THREAD

**Issue by gtaylor** [mher/flower#300]
Flower seems to run great for a few hours, but eventually I'll check it only to find that only the most recent task is showing. The backlog that had previously been stored in memory seems to be cleared, as well.

http://i.imgur.com/AowveZ5.png

Also notice how it's saying "4 hours ago". I'm wondering if this is related, perhaps tasks are being expired.

The celery workers are running Django 1.7. Here are a few relevant bits of config:

```python
TIME_ZONE = 'America/New_York'
USE_TZ = True
```

Both the flower server and the celery server's system timezone is set to UTC.

Any ideas?

**Comment by mher** [comment]
Please checkout https://github.com/mher/flower/issues/321

**Comment by mher** [comment]
#321  fixes random task loss issue.
