### ISSUE TITLE
Random broker drop (or inspect() problem ?)

### ISSUE THREAD

**Issue by Karmak23** [mher/flower#302]
Hi,

I'm using flower to monitor http://1flow.io/. Here are the [celery settings](https://github.com/1flow/1flow/blob/master/oneflow/settings/snippets/celery.py). I use `rabbitmq` (version 2.4 on Ubuntu 12.04 LTS) as the broker.

I have five workers launched in separate machines, with these parameters:

```
/home/1flow/.virtualenvs/1flow/bin/python /home/1flow/www/src/manage.py celery worker --queues swarm,refresh -E --loglevel=warning --hostname worker-02-net.1flow.io -P gevent --soft-time-limit 120 --autoscale 160,20 --maxtasksperchild=128

/home/1flow/.virtualenvs/1flow/bin/python /home/1flow/www/src/manage.py celery worker --queues default,create -E --loglevel=warning --hostname worker-02-default.1flow.io -P gevent --soft-time-limit 600 --autoscale 32,4 --maxtasksperchild=128

/home/1flow/.virtualenvs/1flow/bin/python /home/1flow/www/src/manage.py celery worker --queues fetch,background -E --loglevel=info --hostname worker-03-articles.1flow.io -P gevent --soft-time-limit 300 --autoscale 24,3 --maxtasksperchild=128

/home/1flow/.virtualenvs/1flow/bin/python /home/1flow/www/src/manage.py celery worker --queues check,clean -E --loglevel=warning --hostname worker-04-longtasks.1flow.io -P gevent --soft-time-limit 345600 --autoscale 2,1 --maxtasksperchild=1

/home/1flow/.virtualenvs/1flow/bin/python /home/1flow/www/src/manage.py celery worker --queues high,medium,low -E --loglevel=warning --hostname worker-04-mongo.1flow.io -P gevent --soft-time-limit 600 --autoscale 144,16 --maxtasksperchild=128

```

I also have a 0.7.3 flower and a dedicated celery beat, launched with:

```
nice -n -1 ionice -c 3  /home/1flow/.virtualenvs/1flow/bin/python /home/1flow/www/src/manage.py celery flower  --broker=amqp://oneflow:PASSWORD@10.0.3.100:5672/1flow --broker_api=http://oneflow:PASSWORD@10.0.3.100:55672/api

/home/1flow/.virtualenvs/1flow/bin/python /home/1flow/www/src/manage.py celery beat --loglevel=info
```

Tasks are mixed types : some are short and not resource intensive (refresh, swarm, sync),  some are in the middle (default, articles) and some are very intensive (longtasks, check, clean). You can find all of them in 1flow's source code ([long tasks](https://github.com/1flow/1flow/tree/master/oneflow/core/tasks) and [others in various models](https://github.com/1flow/1flow/tree/master/oneflow/core/models/reldb); ask me if you want more details, don't bother to read there is too much).

**The problem: flower seems to loose connection to the broker very regularly. The `broker` tab looses some queues every now and then, and so does the monitor:** 

![capture d ecran de 2014-11-12 11 19 45](https://cloud.githubusercontent.com/assets/663404/5009200/d12f12c4-6a64-11e4-9659-3b7a5f7d9c53.png)
![capture d ecran de 2014-11-12 11 44 20](https://cloud.githubusercontent.com/assets/663404/5009201/d130d7b2-6a64-11e4-9b96-7cde13ad38a4.png)

Note: the `succeeded tasks` graphs (and failed, and time in queue) are always completely empty, but that's probably another issue. They used to work correctly in the past, in flower version 0.5.x and 0.6.x, but I had far less tasks in queues, and I was using `redis` as broker. For now I don't care, I prefer to concentrate on the broker information.

Note 2: I have [some code in the 1flow status page that queries celery queues](https://github.com/1flow/1flow/blob/master/oneflow/base/utils/stats.py#L213), and every now and then it doesn't get all the queues, too. So my guess is that the problem doesn't come from flower, but eventually from the underlying celery (which is 3.1.16 everywhere). In flower 0.7.3, 3/5 workers are offline most of the time, the other 2 are online most of the time; but it's not the same that are online/offline if i restart the flower process.

I'm currently running the master branch of flower, and results are mitigated: I get nothing at all in the broker graph, but the succeeded/failed/time are back. The broker tab is empty. workers keep getting offline/online, even if the succeeded graph shows constant activity. flower@master graphs:

![capture d ecran de 2014-11-12 13 50 13](https://cloud.githubusercontent.com/assets/663404/5010424/04a4386a-6a73-11e4-9c5e-228cfe025c6d.png)

My questions: could this "loosing connection" situation be expected, knowing that the machine is quite loaded heavy ? How does it happen that we loose some information on the way, even when doing manual celery inspection ? (is this related?) Do you have any advise to provide to help make the situation better ?

Thanks for your time and for your nice flowers ;-)

**Comment by mher** [comment]
Closing this issue. Please open a new issue if you think there are unaddressed problems.
