### ISSUE TITLE
Tab monitor empty

### ISSUE THREAD

**Issue by carlos386386** [mher/flower#310]
The graphics in tab monitor are empty:

![captura](https://cloud.githubusercontent.com/assets/10063469/5283748/be3f1a04-7b0f-11e4-9fea-1ed1dc9219c6.PNG)

The tab broker is also empty :

![captura3](https://cloud.githubusercontent.com/assets/10063469/5283914/082ccb92-7b11-11e4-9140-eff46d9da631.PNG).

The other tabs are ok.
Why this happens?

Thank you in advance.

**Comment by mher** [comment]
Monitor tab is deprecated. Use Prometheus instead.
