### ISSUE TITLE
Celery Flower consuming 100% cpu over time

### ISSUE THREAD

**Issue by sandeepgk1989** [mher/flower#312]
We are using celery flower 0.7.3 version. Here flower is consuming 100% cpu after some time(10hours). We are not able to figure out why this happens. We are using rabbitmq as broker and there will be approximately 10 workers on different servers running.

**Comment by chrisspen** [comment]
I'm using flower 0.9.2, the current version, and I'm still experiencing this. I have no Celery tasks running, yet flower is consuming 100% of my CPU.

**Comment by mlunny-tabc** [comment]
We has the same issue today, 100% CPU usage by celery-flower 0.9.2, had to be SIGKILLed.

It was running with celery 4.1.0/RabbitMQ 3.2.4  on ubuntu 14.04.

**Comment by sandeepgk1989** [comment]
I had this issue sometime back. I started using the development version and things are back to normal.
Am not sure for the production version.

**Comment by mlunny-tabc** [comment]
I've opened a new issue, https://github.com/mher/flower/issues/771, seemed worthwhile give that it's a much newer version of flower.

https://github.com/mher/flower/issues/771
