### ISSUE TITLE
No Information in Flower connected to amqp on remote machine

### ISSUE THREAD

**Issue by sitajaf** [mher/flower#315]
I have rabbitmq + celery + flower set up on machine A. When I access this flower, I get all the information in the broker, tasks, and workers tabs.

How I start flower on machine A: <br>

`flower --broker=amqp://username:password@machine_A_ip:5672/vhapp --broker_api=http://username:password@machine_A_ip:15672/api/
`

However, if I set up flower on machine B, but pointing to the first machine A's amqp, i dont get any information. The 3 tabs remain empty. 

How I start flower on machine B:

`flower --broker=amqp://username:password@machine_A_ip:5672/vhapp --broker_api=http://username:password@Machine_A_ip:15672/api/`

NB: The management-plugin is already enabled.

Sometimes, I see this in the logs, and this is what is there:

[I 150112 11:15:13 command:107] Broker: amqp://username:**@[broker ip]:5672/vhapp <br>
[I 150112 11:15:15 mixins:225] Connected to amqp://username:**@[broker ip]:5672/vhapp
[E 150112 11:16:18 state:71] <br>
Unable to get broker info: ('Connection aborted.', error(110, 'Connection timed out')) <br>
[E 150112 11:17:50 state:112] Failed to inspect the broker: ('Connection aborted.', error(110, 'Connection timed out')) <br>
[E 150112 11:17:50 state:112] Failed to inspect the broker: ('Connection aborted.', error(110, 'Connection timed out')) <br>
[E 150112 11:17:50 state:112] Failed to inspect the broker: ('Connection aborted.', error(110, 'Connection timed out')) <br>
[E 150112 11:17:50 state:112] Failed to inspect the broker: ('Connection aborted.', error(110, 'Connection timed out'))

What could I be doing wrong?

**Comment by mher** [comment]
Looks like a connectivity issue. You can debug using broker.py script

    $ python -m flower.utils.broker amqp://username:password@machine_A_ip:5672/vhapp celery http://username:password@Machine_A_ip:15672/api/

**Comment by mher** [comment]
No answer. Closing. Please reopen if you are still experiencing this issue.
