### ISSUE TITLE
add timezone option

### ISSUE THREAD

**Issue by mozillazg** [mher/flower#319]
`--timezone     show times in given timezone(default: UTC)`

ref https://github.com/mher/flower/issues/194#issuecomment-67922670

**Comment by mher** [comment]
The master version of flower should expect CELERY_TIMEZONE option. Have you tried it?

**Comment by mozillazg** [comment]
@mher  er, sorry, it work.
BTW, seems task page is still UTC datetime?

**Comment by AdrianLC** [comment]
The latest version from pypi doesn't check `CELERY_TIMEZONE` yet3
Are you planing a new release soon?

**Comment by mher** [comment]
Yes, I'm going to release a new version. Have you tested CELERY_TIMEZONE option from the master version?

**Comment by AdrianLC** [comment]
Not yet. I'll give it a try tomorrow.

**Comment by AdrianLC** [comment]
It'd be nice if I could set it directly through the command line. We don't have a celery app in the flower machine and I'll have to add a `flowerconfig.py` just for this option.

**Comment by mher** [comment]
You can use the existing celery app with -A option. No need to define it
for flower.

On Wed, Feb 4, 2015 at 9:11 AM, Adrián López Calvo <notifications@github.com

**Comment by AdrianLC** [comment]
That's the thing. We don't have the any celery app in the machine. We 
have 2 remote workers with different apps in their own machines and 
flower running in another machine with redis.

**Comment by AdrianLC** [comment]
@mher 
Finally got around to testing the master.
Our servers are configured with UTC time and our timezone is UTC + 1.
All the workers runnning with `CELERY_ENABLE_UTC = True` and `CELERY_TIMEZONE = 'Europe/Madrid'`.

* Flower without a celery app or any specific timezone setting: All timestamps shown in server time (1 hour less) and natural time from the tasks view saying `2 hours ago` for tasks ran just now. That is 1 extra hour less in this view... (Same issues with current pypi release)
* Running flower without a celery app, but with a celery config file (`--config celeryconfig`) with the settings: `CELERY_ENABLE_UTC = True` and `CELERY_TIMEZONE = 'Europe/Madrid'`: Same result.
* Flower with with the whole django settings and celery app, same timezone settings as above: Natural times from tasks view shown correctly. Timestamps everywhere else still in server time (1 hour less).

Hope that helps. Any idea why the extra hour less from the tasks view?

**Comment by PaleNeutron** [comment]
same problem even 2021.

```
  flower:
    image: mher/flower
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - CELERY_TIMEZONE=Asia/Shanghai
      - CELERY_ENABLE_UTC=True
```
and the same in worker docker.

task request at local time `21:00` shown `05:00` in flower. it has a 2 * 8 hours different.
