### ISSUE TITLE
Flower Randomly Stops Receiving Tasks

### ISSUE THREAD

**Issue by TimOrme** [mher/flower#321]
Hello,

We're running with the following setup:

flower   -> 0.7.3
software -> celery:3.1.17 (Cipater) kombu:3.0.24 py:2.7.6
            billiard:3.3.0.19 py-amqp:1.4.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled

Were pointing flower at an externally running broker. It is not running on the same box as the workers.

The issue were seeing is that flower seems to "die" and new tasks are no longer received. There are no error messages that appear in the logs, and a restart of the app seems to restore functionality, and tasks start showing up again.

Not sure what other info to provide, assuming this probably isnt enough to go on. I can try and turn up logging and see whats happening if that will help.

Thanks!
Tim

**Comment by mher** [comment]
Sorry for late reply. Can you try the master version?

**Comment by TimOrme** [comment]
Ill give that a go. It seems that at least partially, this is due to successful connection re-establishment not resetting the timer for failure. With our infrastructure, connections are frequently dropped, so it seems that the timer just keeps bumping up the time to retry, even if in between it succeeds. Something like:

Connection dropped, waiting 2 seconds to retry.
Connection established
Connection dropped, waiting 4 seconds to retry.
Connection established
...
Connection dropped, waiting 2000 seconds to retry

etc.

Will install the master branch and see where it gets us.

Thanks!
Tim

**Comment by TimOrme** [comment]
Tried this in the latest install (pip install flower-new), and still see this behavior.

`
[E 150310 05:04:08 events:117] Failed to capture events: '[Errno 104] Connection reset by peer', trying again in 16 seconds.
[I 150310 05:04:24 mixins:225] Connected to amqp://test-tasks_dev:**@rmq.test.com:5672/test-tasks
[E 150310 07:04:08 events:117] Failed to capture events: '[Errno 104] Connection reset by peer', trying again in 32 seconds.
[I 150310 07:04:40 mixins:225] Connected to amqp://test-tasks_dev:**@rmq.test.com:5672/test-tasks
[E 150310 09:04:07 events:117] Failed to capture events: '[Errno 104] Connection reset by peer', trying again in 64 seconds.
[I 150310 09:05:11 mixins:225] Connected to amqp://test-tasks_dev:**@rmq.test.com:5672/test-tasks
[E 150310 11:04:06 events:117] Failed to capture events: '[Errno 104] Connection reset by peer', trying again in 128 seconds.
[I 150310 11:06:15 mixins:225] Connected to amqp://test-tasks_dev:**@rmq.test.com:5672/test-tasks
[E 150310 13:04:07 events:117] Failed to capture events: '[Errno 104] Connection reset by peer', trying again in 256 seconds.
[I 150310 13:08:23 mixins:225] Connected to amqp://test-tasks_dev:**@rmq.test.com:5672/test-tasks
[E 150310 15:04:07 events:117] Failed to capture events: '[Errno 104] Connection reset by peer', trying again in 512 seconds.
[I 150310 15:12:39 mixins:225] Connected to amqp://test-tasks_dev:**@rmq.test.com:5672/test-tasks
[E 150310 17:04:06 events:117] Failed to capture events: '[Errno 104] Connection reset by peer', trying again in 1024 seconds.
`

**Comment by mher** [comment]
Fixed by #342
