### ISSUE TITLE
Tasks events sometimes are being missed by flower

### ISSUE THREAD

**Issue by AndreLobato** [mher/flower#322]
I noticed that sometimes flower misses some task events, and does not update the status in it's db, therefore keeps displaying out-of-date tasks. This has been happened even if the worker didn't died. 

I wonder even to run a periodic sync with celery results database, and why this might be happening?

Anyone have noticed something similar? Events are being consumed by someone else?

**Comment by mher** [comment]
Sorry for late reply. This can be a result of network errors. See #321

**Comment by mher** [comment]
No reply, closing. Please reopen if it is still an issue

**Comment by AndreLobato** [comment]
Sorry for not reply earlier, but I did deployed an updated version of flower and this does not seems to be happening any more. 

Thanks
