### ISSUE TITLE
Can shutdown celery worker with UI, but cannot start again.

### ISSUE THREAD

**Issue by jacobbridges** [mher/flower#323]
I'm having an issue with the Flower UI. When I shutdown a worker (Workers tab -> select worker -> Shutdown), I cannot bring the worker up again through the interface. The Restart command returns the following error: 

`Error! Failed to restart the 'worker@host' pool: None`

Is this an error in Flower? Or is starting a stopped worker not yet supported?

---

By the way, I have set my app config setup thusly:
```python
app.conf.update(

    # Retain Job Result for 1 hour
    CELERY_TASK_RESULT_EXPIRES=3600,

    # Maximum cached results to keep in memory
    CELERY_MAX_CACHED_RESULTS=100,

    # Enable worker restart from Flower interface
    CELERYD_POOL_RESTARTS=True,

    # Set the correct timezone
    CELERY_TIMEZONE='America/New_York',

    # Set the custom queue for this job
    CELERY_ROUTES={
        'Scrape': {'queue': 'Scraper'}
    },

    # Schedule Tasks
    # -- See http://bit.ly/1CiWDaN for more details.

    CELERYBEAT_SCHEDULE={
        'run-every-thirty-seconds': {

            # Name of task to run (see the "Tasks" section below)
            'task': 'Scrape',

            # Task interval
            'schedule': timedelta(seconds=30),

            # Task arguments (see the "Tasks" section below)
            'args': ()
        }
    }
)
```

**Comment by luthur** [comment]
you have to use supervisor to restart your worker. shutdown is shutdown

**Comment by jacobbridges** [comment]
Thanks for the response @luthur. So you are saying Flower does not currently support starting a worker that has been shutdown? If so that's a shame. Would be a great feature.

**Comment by anandtripathi5** [comment]
@mher is the restart feature, is in the development pipeline?
