### ISSUE TITLE
Possible mem leak on workloads with huge results in tasks

### ISSUE THREAD

**Issue by mvikharev** [mher/flower#326]
I have a celeryflower instance that monitors a couple of celeryd workers. I use redis as backend results storage. So when there are a lot of tasks that returns huge results (up to limit of 512mb) - celeryflower begins to eat memory until all tasks finishes or i restart flower.

There are no problem when results are small (bool).

I solved that problem with memory plugin of supervisord. But there is no way to store complete history.

As i see, flower stores own copy of results in locmem memory or it is a memleak.How can i make flower not to handle tasks results? Such option in config will be usefull.

**Comment by mher** [comment]
What version of flower are you using? Have you tried the master version?

**Comment by mvikharev** [comment]
Thank you for response.
We are on master now and there is no problem.

Also i guess i can filter out results in 0.8.0 within http://flower.readthedocs.org/en/latest/config.html#format-task

**Comment by tmacjx** [comment]
@mvikharev 
thanks your advice!!! Flower max_task not work for me and memory leak still exist.So we have to use superlance memmon to monitor memory limit and restart progress.
link  https://superlance.readthedocs.io/en/latest/memmon.html
