### ISSUE TITLE
Report errors on the web

### ISSUE THREAD

**Issue by mgedmin** [mher/flower#327]
There are configuration issues (like using rabbitmq as the broker but forgetting to enable the rabbitmq_management plugin) that result in [broken graphs](#324) but are hard to diagnose.

If the user is lucky, they see an error message on the console where they ran flower:

> [E 150203 11:51:06 broker:76] RabbitMQ management API call failed: [Errno 111] Connection refused
> [E 150203 11:51:06 broker:77] Make sure RabbitMQ Management Plugin is enabled (rabbitmq-plugins enable rabbitmq_management)

If they're less lucky, their celery logging configuration redirects those to /dev/null and they don't get to see anything when they run `celery flower`.

In any case it would be friendlier to show these errors in the Flower user interface.

**Comment by mher** [comment]
There are no plans to work on this feature at the moment until someone decides to contribute to the project.
