### ISSUE TITLE
Get size of queues via api

### ISSUE THREAD

**Issue by Gwildor** [mher/flower#328]
Hi there,

Is it possible to use the api to get the length of all the queues? This would make it easier for us to monitor Celery automatically, because we sometimes have a task that hangs and causes all new tasks to get thrown in the queue and wait indefinitely. If there was an easy way to get the queue size (I know you can also do that with a command to the broker, Redis in our case), it would be trivial to write a script that monitors multiple servers with Celery on them through Flower, and raise warnings when a queue gets over a certain threshold.

**Comment by mher** [comment]
There is no such api method but it is easy to implement. The api handler should return the result of https://github.com/mher/flower/blob/master/flower/views/broker.py#L29
