### ISSUE TITLE
How to display unicode result instead of raw repr?

### ISSUE THREAD

**Issue by luthur** [mher/flower#329]
I am a Chinese user. If the task result contains unicode character, it will display the raw repr like `"'\\xe5\\x8c\\x97\\xe4\\xba\\xac'"` or `"u'\\u5317\\u4eac'"` instead of "北京"

**Comment by mvikharev** [comment]
I think you can prepare your task result within http://flower.readthedocs.org/en/latest/config.html#format-task

**Comment by luthur** [comment]
@mvikharev thanks
