### ISSUE TITLE
Improve Broker graph label

### ISSUE THREAD

**Issue by mgedmin** [mher/flower#330]
The Monitor tab has four graphs:

- Succeeded tasks
- Failed tasks
- Task times
- Broker

I have no idea what "broker: 100" means.  100 tasks in the queue, waiting for execution?  A clearer label would be very welcome.

**Comment by mher** [comment]
It is the number of tasks in a broker's queue.

**Comment by mher** [comment]
Thanks for the feedback!

**Comment by mgedmin** [comment]
Thank you for fixing this!  :heart:
