### ISSUE TITLE
Negative activity on tasks ?

### ISSUE THREAD

**Issue by macnibblet** [mher/flower#333]
Can anyone explain why i have negative activity ? 
![Screenshoot](http://caps.interactivesolutions.se/ss/8cae85.png)

**Comment by macnibblet** [comment]
Also, the active column can display 100> when i only have a concurrency of 8 ?

**Comment by mher** [comment]
Any idea how to reproduce this?

**Comment by macnibblet** [comment]
None at all, i have tried pretty much everything i know. It's not on the javascript side, because i checked the data coming from the websockets.

**Comment by diegoguimaraes** [comment]
I'm experiencing the same issue here. I noticed that this happens when I restart the workers while there are tasks being processed.
`flower==0.8.0`
How I am restarting my workers: `celery multi restart 6 -A proj --pidfile=path/to/pidfile --logfile=path/to/logfile  -Q a,b,c,d `

**Comment by mher** [comment]
Please try the master version. I've fixed a couple of issues with active task calculation.

**Comment by mher** [comment]
Note that number of active tasks can be wrong if flower or worker restart happens while running tasks.

**Comment by diegoguimaraes** [comment]
@mher In this case that number of active tasks can be wrong restarting flower or worker while running tasks, is it a expected behavior or a known issue?

**Comment by mher** [comment]
Flower receives events from celery workers and calculate the number of active tasks by `active = started - failed - succeeded - retried` formula. There is no way to reliably calculate active tasks if flower misses some events.

**Comment by mher** [comment]
Closing this issue. The master version fixes issues with negative active tasks.

**Comment by jackyfkc** [comment]
A way to prevent event losing is to make the event receiver using a persistent queue instead of the transient queue.
