### ISSUE TITLE
Flower doesn't find previously scheduled tasks 

### ISSUE THREAD

**Issue by AlexIzydorczyk** [mher/flower#334]
Hi 

I'm having an issue where Flower is not finding scheduled tasks from redis if those tasks were scheduled before Flower was turned on. The tasks do not appear in the Tasks/ section as "received" and cannot be found using the HTTP API. They do, however, appear as belonging to a particularly Worker if a worker is selcted in the Workers/ menu. 

Tasks scheduled (and hence added to Redis) while Flower is running appear, as normal, in the Tasks/ section of Flower. 

Is this a known problem / is there a solution? 

Does anyone happen to know if this is a redis specific problem or something to do with how Flower reads existing tasks when turning on?

Thanks
Alex

**Comment by AlexIzydorczyk** [comment]
By scheduled tasks, I should mention these are tasks 'scheduled' using ETA

**Comment by mher** [comment]
Flower gets task info from celery via celery events api. Celery sends events in real time. You will need to have running Flower to collect the events.
