### ISSUE TITLE
List of queues is incomplete

### ISSUE THREAD

**Issue by NotSqrt** [mher/flower#335]
Hi !

I use Redis as broker.

On the pages "Broker" and "Monitor", only some of my queues show up. There should be a few more than those I get, and I know that some of the missing ones are not empty.

When I call ``python -m flower.utils.broker redis://localhost:XX/1 missing_queue``, I get a good value.. : ``[{'messages': 709, 'name': 'missing_queue'}]``

A problem of caching ?

**Comment by mher** [comment]
Have you tried to refresh the worker (there is a refresh button on worker info page)? Broker and monitor tabs use queue names from the workers cache.

**Comment by NotSqrt** [comment]
Refreshing seems to "fix" it.
So this means that it's impossible to get a queue size if no worker listens to that queue (even if it was a used queue at the previous refresh).


It does not fix another similar bug (it also uses the worker_cache, but on a class that does not provide a "refresh" button):
* one of my workers is correctly displayed as online on the dashboard
* if I click on it, it fails with ``Unknown worker '<name>'``

**Comment by NotSqrt** [comment]
bump for the second part of my last message.

It appears that any worker that starts after flower can appear on the dashboard tab, but accessing the details of the worker will fail with ``Unknown worker``

**Comment by mher** [comment]
I've added `refresh` param to the dashboard page. It will allow to update the cache with `/dashboard?refresh=true` requests. https://github.com/mher/flower/commit/c4625a3ea98da282d9cd77acc13bba996e9fa676

**Comment by NotSqrt** [comment]
Manually calling that url fixes the error.

Can you add a button for this on the ``Unknown worker '<name>'`` page ?
