### ISSUE TITLE
mongo is not supported?thx

### ISSUE THREAD

**Issue by yima1006** [mher/flower#337]
I use celery with mongo as a broker, and i runed by this command: 
"celery flower --address=127.0.0.1 --port=5555 --broker=mongodb://localhost:27017/web", but when i opened with http://127.0.0.1:5558/ in the brower, there is no data.

**Comment by mher** [comment]
celery mongodb transport doesn't support celery events. Flower uses events to get data from workers.

**Comment by yima1006** [comment]
Thanks. I will use RabbitMQ.
