### ISSUE TITLE
Store worker's pool parameters in flower

### ISSUE THREAD

**Issue by mvikharev** [mher/flower#338]
Currently we have two ways to change concurency (or autoscale) of celery worker:
1. to change configuration file of procces control system (like supervisord) and reload worker. Reloading can be very expensive if there are long-running tasks in the pool. In our case supervisord restart can go for tens of minutes.
2. to use flower UI. Very usefull when there is a need to tune concurrency on the fly. But tuned parameters will be reseted on the next time when worker restarted (for example on new version deploy). So we also need to touch supervisord configuration every time to not lose changes.

I think that concurrency or autoscale is not kind of static parameter. It can be changed very often. So it must be stored and handled by some who can change it quickly with minimum downtime, like flower does.

So it will be awesome to store pool parameters in flower permanently, monitor actual worker parameters and to sync them automatically. In that case we could create supervisord config file with pre defined minimum values and forget about it. Flower will change pool configuration each time when worker params changes on restart or crash.

**Comment by mher** [comment]
You can implement  persistent auto scaling in a script which will be called every time when you deploy or restart a worker. The script can use flower api to adjust the worker's concurrency.

**Comment by mvikharev** [comment]
i'l try to implement it.
thx
