### ISSUE TITLE
Hide sensitive data in Config panel

### ISSUE THREAD

**Issue by theY4Kman** [mher/flower#340]
We're using djcelery, so our config is flooded with the rest of our Django settings. It's showing passwords, so I'd like some way to filter them.

**Comment by mher** [comment]
This looks like a bug in Celery. Celery filters out sensitive and default options from configuration.

As a workaround you can try to redefine or disable `conf` remote command. http://celery.readthedocs.org/en/latest/userguide/workers.html#id17
