### ISSUE TITLE
setting --broker option in flowerconfig

### ISSUE THREAD

**Issue by bretth** [mher/flower#341]
It doesn't appear possible to define the broker url in flowerconfig.py. 

On the celery side I use django manage.py and the settings.py to define the broker (in fact I load it in as an environment variable from a .env file), but it's unclear how I can do the same for flower. I would normally do something like this for flowerconfig.py:

```python
# flowerconfig.py
import os
broker = os.getenv(CELERY_BROKER_URL, 'redis://localhost:6379/')
```

**Comment by mher** [comment]
Currently, it is not possible to define the broker url in flower config. The best way to configure the broker is reusing celery application:

    $ flower -A tasks.app

    //tasks.py
    app = Celery(broker='redis://')

**Comment by mher** [comment]
Or pass it as a command line option:

    $ flower --broker=$CELERY_BROKER_URL

**Comment by cedzz** [comment]
@mher  will the --conf settings works with the above `flower -A tasks.app` invoke ?
