### ISSUE TITLE
400 from google oauth (when oauth isn't configured)

### ISSUE THREAD

**Issue by ruthie** [mher/flower#343]
I'm running flower on heroku, pulling directly from master.  When I go to the app, after entering basic auth credentials, I get a google error page at `https://accounts.google.com/o/oauth2/auth?approval_prompt=auto&scope=profile+email&redirect_uri=None&response_type=code&client_id=None`

With the text
```
Error: invalid_request
Invalid parameter value for redirect_uri: Missing scheme: None
```

I'm starting flower with the following command:
`flower --port=$PORT --broker=$BROKER_URL --basic_auth=$FLOWER_AUTH --persistent --db=/tmp/flower`

$BROKER_URL points to a redis instance.

I'm not interested in using oauth.  How can I disable it?

**Comment by ruthie** [comment]
Hmm, interestingly, this happened to me for the first time when I upgraded to master, but it didn't stop happening again when I downgraded to 0.7.3, which had previously worked for me :-(

**Comment by mher** [comment]
`basic_auth` option doesn't enable oauth. Make sure you don't pass `auth` option from the command line or config file.

**Comment by cosenal** [comment]
I have the same problem even with `auth` option (again Flower deployed on Heroku). Maybe I am missing something about how Google OpenID works.

**Comment by cosenal** [comment]
Nevermind, I was reading the wrong documentation (https://github.com/mher/flower/wiki/Authentication) instead of https://github.com/mher/flower/blob/master/docs/auth.rst

**Comment by RiskerFalor** [comment]
You can't use "FLOWER_AUTH" as your heroku config variables, It will be your `auth` option value.@cosenal

**Comment by github-account-because-they-want-it** [comment]
I'm having the same problem. `flower==0.9.2`. It asks for my credentials specified in `FLOWER_AUTH` env var and only when I supply the correct values it redirects me to google's error page.

**Comment by j0lv3r4** [comment]
Happening to me as well in Heroku. Flower v0.9.3

**Comment by antonvalletas** [comment]
Can we reopen this @mher this is still happening. For me not on heroku, but rather when running on 0.9.7 as a systemd service. When running manually it auths correctly.

**Comment by antonvalletas** [comment]
> Can we reopen this @mher ? This is still happening. For me not on heroku, but rather when running 0.9.7 as a systemd service. When running manually it auths correctly.

An update on this. If you have an environment variable called $FLOWER_AUTH, even if it contains the credentials for --basic_auth, flower will automatically enable Google Auth thus causing this issue. This should be stated in the documentation because there are several tutorials that recommend calling this variable $FLOWER_AUTH without taking into account that Flower then automatically enables Google Auth
