### ISSUE TITLE
Show worktime for succeeded tasks in tasks list

### ISSUE THREAD

**Issue by Melevir** [mher/flower#344]
For each succeeded task I can calculate work time manually, by subtracting "Started" from "Succeeded", but I have to visit task page for that.
It looks like a good idea to add column with worktime at `/tasks` directly.
This involves API and templates modification.

I'll be glad to try to complete this task once it's approved.

**Comment by mher** [comment]
The /task/ page already contains Runtime column.

If you want to have it on /tasks page probably it makes sense to make it optional. Different users have different use cases. The columns can be added/ removed from UI or from configuration file.
