### ISSUE TITLE
Queues order by name

### ISSUE THREAD

**Issue by Melevir** [mher/flower#346]
Now queries are not ordered by name and there is no way to reorder them manually.
This doesn't look nice when there are more then two queries and not nice at all, when there are >10 queries.

Approve the issue please if the idea is ok.

**Comment by mher** [comment]
Queries or queues?

**Comment by Melevir** [comment]
Queues, yes.

**Comment by mher** [comment]
Makes sense. If you are going to make the columns sortable consider using http://tablesorter.com library.
