### ISSUE TITLE
Refactor some complex functions

### ISSUE THREAD

**Issue by Melevir** [mher/flower#349]
McCabe complexity > 10 for the following functions:

    flower/flower/command.py:31:1: C901 'FlowerCommand.run_from_argv' is too complex (13) [mccabe]
    flower/flower/utils/tasks.py:6:1: C901 'iter_tasks' is too complex (12) [mccabe]
    flower/flower/utils/template.py:33:1: C901 'humanize' is too complex (11) [mccabe]

It's good idea to test and refactor them to increase readability and maintainability.

**Comment by mher** [comment]
Refactored, thanks!
