### ISSUE TITLE
flower install error

### ISSUE THREAD

**Issue by ekoome** [mher/flower#355]
Installed Flower on CentOS 6.5 but receiving the following error on install and when running.

Installing collected packages: flower
  Running setup.py install for flower
    SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/flower/views/tasks.py', 58, 3
0, '        params = {k: v[-1] for k, v in self.request.query_arguments.items()}\n'))
    

Any thoughts on how to fix

**Comment by mher** [comment]
This already fixed in the master. See #352
