### ISSUE TITLE
Search tasks by args/kwargs

### ISSUE THREAD

**Issue by Melevir** [mher/flower#358]
Consider a use case: I have 1 million succeeded/failed tasks with "client_id" argument. I want to see list of all tasks, that have "client_id=1234".

For me it would be enough an "args/kwargs" search field on the `/tasks/` page, that I can fill with "1234" and get list of tasks, that have "1234" as value for any argument. Optionally, I want to fill the field with "client_id=1234" value and get tickets with client_id I need.

Is the idea looks nice to you? I can try to implement it if, it is approved.

**Comment by mher** [comment]
Ability to search/filter tasks by args/kwars/results will be very useful. Thanks!

**Comment by mher** [comment]
This feature is supported now. Try the master version.
