### ISSUE TITLE
Improve celery workers and tasks stopping

### ISSUE THREAD

**Issue by mvikharev** [mher/flower#371]
There are two ways of worker shutdowning: cold (QUIT signal) and warm (TERM signal). Currently flower performs only warm shutdown.
So will be usefull to stop celery worker with tasks killing via TERM signal. That action can be as third choice of actions on the Workers page:
- Warm Shut Down 
- Cold Shut Down
- Restart Pool

It also will be usefull to terminate group of tasks. That action can be applied to filtered tasks set on the tasks page via third button:
- Apply filter
- Cancel
- Terminate filtered

**Comment by mher** [comment]
There are no plans to work on this feature at the moment until someone decides to contribute to the project.
