### ISSUE TITLE
Relaunch tasks

### ISSUE THREAD

**Issue by Melevir** [mher/flower#375]
Consider a use case: a user monitors a queue health, finds a failed task and want to execute the task again.
To do this, one have to manually launch the task from his app and that is not convenient.
Button `relaunch` for finished tasks would be really helpful for failed tasks. On click, it puts the same task to the same queue with same arguments.
The only problem I see is complex arguments - since flower get stringified args/kwargs, the feature will works only for simple args/kwargs - int, float, string, datetime. If a task has arguments of other types, this feature is disabled.

Realisation doesn't looks difficult, except args/kwargs parsing part - it can get a little verbose, I think.

Is the feature ok for you?

**Comment by mher** [comment]
There is a pull request about this feature https://github.com/mher/flower/pull/158.
