### ISSUE TITLE
GET /api/workers changed

### ISSUE THREAD

**Issue by BjBlazkowicz** [mher/flower#383]
Hello,

Since the last version the API reference of resource "/api/workers" differs from what I get back from flower.

How can I get worker status in version 0.8.1?

**Comment by bivald** [comment]
I have the same problem, from what I see you could *possibly* get the amount of running tasks by counting the active[] array.

**Comment by nstanoszek** [comment]
i have the same issue on Ubuntu...but when i run local to windows...it works fine.

**Comment by BjBlazkowicz** [comment]
@nstanoszek are you sure you're running the latest version on windows? Because this seems to have changed within the latest version only. If I use flower 0.7.3 the workers resource works as documented.

**Comment by nstanoszek** [comment]
I think I figured it out (think haha).  Windows was fine, but not Ubuntu.
That said...does anyone know why it was changed?

If i run Flower inside my venv, it doesn't work right (in fact I cannot
switch the version properly) but outside it works with .0.7.3.  I wish the
latest version worked right!

On Tue, May 12, 2015 at 5:06 AM, BjBlazkowicz <notifications@github.com>
wrote:

> @nstanoszek <https://github.com/nstanoszek> are you sure you're running
> the latest version on windows? Because this seems to have changed within
> the latest version only. If I use flower 0.7.3 the workers resource works
> as documented.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mher/flower/issues/383#issuecomment-101203650>.
>



-- 
Nick Stanoszek
President/CEO Payr
(440)227-6450

www.payrmobileapp.com

**Comment by BjBlazkowicz** [comment]
@nstanoszek Then you probably have 0.8.x in your venv right?

**Comment by nstanoszek** [comment]
Yep. Can't get the damn thing to change. Ran it outside and it worked. Not sure what's up with my venv though

**Comment by nstanoszek** [comment]
Thanks again for the help!!

**Comment by qgriffith** [comment]
I am having the same issue with the 0.8.x version. It appears the worker status value is no longer being sent in the API, thus making a bit hard to monitor of a celery worker is online.  Does anyone know if this was fixed in teh 0.9.x version?

**Comment by bicharagadha** [comment]
Downloaded the latest master from github. (Version information included below)
The status field is still noticeably missing. 

0.9.0-dev
3.1.17 (Cipater)
flower   -> flower:0.9.0-dev tornado:4.0.2 babel:1.3
software -> celery:3.1.17 (Cipater) kombu:3.0.24 py:2.7.6
            billiard:3.3.0.19 py-amqp:1.4.6
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled

**Comment by nstanoszek** [comment]
I agree. Not sure why

**Comment by serdardalgic** [comment]
It's really annoying. We were using a munin plugin for inspecting the running tasks through flower, but API doesn't send 'running_tasks' anymore. Thanks to the uncompleted documentation, I've to dig into the code to figure this out. 

Did anyone find a solution to get the number of running tasks? from flower.api.control module, as much as I could have seen, those are the only inspect methods:

```
    INSPECT_METHODS = ('stats', 'active_queues', 'registered', 'scheduled',
                       'active', 'reserved', 'revoked', 'conf')
```

I'm digging some more into it, If I find smt, I'll write to here.

**Comment by nstanoszek** [comment]
What does munin do?

**Comment by serdardalgic** [comment]
We were getting the running_task number per our queue in order to track the number of tasks running during the day. If you actually ask what does munin, itself do; munin is a monitoring tool, more info here http://munin-monitoring.org/

**Comment by edgecaselabs** [comment]
Ditto. Status is suddenly gone and my monitors fails! Eek!

**Comment by BjBlazkowicz** [comment]
I wonder if we could get any comments on this.

**Comment by edgecaselabs** [comment]
I just rolled back to 0.7.3. It works fine for me.

**Comment by mher** [comment]
I've updated the docs and made a couple of changes:
1. To get a status of workers use: `/api/workers?status=1`
2. To get detailed workers info use: `/api/workers/`. `/api/workers` returns the cached info, if you need an updated info use `refresh=1` parameter

Version 0.7 uses periodic polling to get info from all workers. If workers are busy the current state requested by `/api/workers` can be outdated. Version 0.8 is implemented using events sent from celery workers.
