### ISSUE TITLE
Flower Dashboard shows Active Tasks when none are active

### ISSUE THREAD

**Issue by eswenson1** [mher/flower#384]
I'm pretty sure there are no celery tasks active on my system, yet the Flower Dashboard shows the "Active: NNN" button as "Active: 182".  It correctly shows that 183 tasks were Retried, and that 56 tasks have Failed. But no tasks are currently active according to the "celery inspect tasks" command. I'm using version 0.8.1 of Flower and version 3.1.17 of celery. 

When I refresh the Dashboard, initially the display seems correct, with the "Active: 0" button showing no active tasks. Then, about 5 seconds later, the button changes to "Active: 182".

**Comment by mher** [comment]
Please try https://github.com/mher/flower/commit/91f69e1ac5620fd3f0b01191bec63944499fb055. It should fix the issue.

**Comment by mher** [comment]
Note that number of active tasks can be wrong if flower or worker restart happens while running tasks.

**Comment by eswenson1** [comment]
That seemed to have fixed the issue. Thanks much!

**Comment by eswenson1** [comment]
Hmm... now, I'm seeing negative numbers for the active tasks. One of my dashboards currently has the following:

Active: -3, Processed: 4859, Failed: 0, Succeeded: 6864, Retried: 0

In the per-worker data, two of the 5 workers show Active=-1 and Active=-2.  The others show Active=0.

For the two workers with negative values for Active, please see the following details:

worker 1:
  Active: -1, Processed: 3426, Failed: 0, Succeeded: 3427, Retried:0
worker 2:
  Active: -2, Processed: 3427, Failed: 0, Succeeded: 3431, Retried: 0

So how can we have more Succeeded tasks than we have Processed tasks?

**Comment by eswenson1** [comment]
![screen shot 2015-04-27 at 12 43 30 pm](https://cloud.githubusercontent.com/assets/867939/7356127/0ff0a5f6-ecdb-11e4-93d1-a1e4a183f95b.png)

**Comment by mher** [comment]
The latest version shows N/A if it is not possible to calculate the number of active tasks correctly.
