### ISSUE TITLE
worker list shows lots of temporary clients

### ISSUE THREAD

**Issue by frasergraham** [mher/flower#387]
I just updated to the latest development flower and anything that connects to the broker to create a new job seems to be adding an entry to the worker list..

gen26865@myapp-api-dev	Offline	0	0	0	0	0	N/A

I get hundreds of these in the dashboard view and it makes the view unusable for knowing if my workers are online.

**Comment by frasergraham** [comment]
I am using celery 3.1.11 and RabbitMQ3.4 if that makes a difference

**Comment by saich** [comment]
I'm having the same issue. Using flower==0.8.2, celery==3.1.17, redis==2.10.1.

**Comment by frasergraham** [comment]
I upgraded my celery install to 3.1.18 and I still see this, i'm using flower from master. Could this be related to how i've configured django? It still uses django-celery so it never defines an app?

**Comment by mher** [comment]
Fixed by #417
