### ISSUE TITLE
Issues using OAuth

### ISSUE THREAD

**Issue by brandonberney** [mher/flower#388]
I have tried setting the OAuth key, redirect uri, and secret through both the command line and environment variables, but I'm getting the same error each time:

```
Traceback (most recent call last):
  File "/site/venv/bin/flower", line 9, in <module>
    load_entry_point('flower==0.8.2', 'console_scripts', 'flower')()
  File "/site/venv/local/lib/python2.7/site-packages/flower/__main__.py", line 11, in main
    flower.execute_from_commandline()
  File "/site/venv/local/lib/python2.7/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/site/venv/local/lib/python2.7/site-packages/flower/command.py", line 98, in handle_argv
    return self.run_from_argv(prog_name, argv)
  File "/site/venv/local/lib/python2.7/site-packages/flower/command.py", line 37, in run_from_argv
    option = options._options[name]
KeyError: 'auth2_secret'
```

**Comment by mher** [comment]
How do you launch flower?

**Comment by misread** [comment]
I use supervisor, but I tested via the command line to get the error.

```celery --port=5555 --auth="username@gmail.com|foo@bar.net"

**Comment by mher** [comment]
Checkout http://flower.readthedocs.org/en/latest/auth.html#google-oauth-2-0

`--oauth2_key` and `--oauth2_secret` should be supplied as well

**Comment by misread** [comment]
I've already tried:
* Setting them via the command line ```oauth2_key```, etc.
* Setting them as environment variables provided by the documentation ```FLOWER_OAUTH2_KEY```
* Setting them as environment variables seen in source code ```FLOWER_GOOGLE_OAUTH2_KEY```

**Comment by jamesbennet** [comment]
I also get this KeyError: 'auth2_secret' error. 

I am starting celry flower using supervisord too, and am supplying --auth, --oauth2_key, and --oauth2_secret, which should be sufficient, have also tried passing these as the environment variables FLOWER_OAUTH2_KEY, FLOWER_OAUTH2_SECRET, and FLOWER_OAUTH2_REDIRECT_URI.

Same issue as the guy above. This is flower 0.8.2.

**Comment by mher** [comment]
Please try the master version. It works for me.

**Comment by embolalia** [comment]
I don't get this with master (or 0.8.3) when passing `--oauth_key=… --oauth_secret=… oauth2_redirect_uri=…` arguments on the command line, but I do when setting environment variables as follows:
```sh
export FLOWER_OAUTH2_KEY=…
export FLOWER_OAUTH2_SECRET=…
export FLOWER_OAUTH2_REDIRECT_URI=http://localhost:27881/login
celery flower --auth='.*@gmail.com' --port=27881
```
It looks like the problem comes [here](https://github.com/mher/flower/blob/master/flower/command.py#L36), where it's grabbing all of the `FLOWER_*` environment variables and parsing them into options. I'm guessing at this point the oauth options haven't been set up within Tornado's options object? I'm not sure where that happens, exactly.

**Comment by mher** [comment]
This should be fixed now. Please try the master version and update the tornado version required by Flower. The problem was in Tornado version.
