### ISSUE TITLE
url_prefix option is not supported anymore

### ISSUE THREAD

**Issue by kaushalsingh11** [mher/flower#390]
Have Installed flower via pip. This is throwing the error: url_prefix option is not supported anymore.
If this option is deprecated? How to achieve this?

**Comment by kneckinator** [comment]
Documentation on readthedocs says the option is still available, though I ran into the same problem upgrading from flower==0.6.0 -> 0.8.2

http://flower.readthedocs.org/en/latest/man.html?highlight=url_prefix

**Comment by jeromedoyle** [comment]
Any updates on this?

**Comment by mher** [comment]
Duplicate of #414
