### ISSUE TITLE
Flower connect to RabbitMQ but fail on inspect methods

### ISSUE THREAD

**Issue by lendoly** [mher/flower#395]
Hello,

I have one machine with RabbitMQ and Celery, I'm trying to put Flower on it to monitorize the tasks, the problem is when I try to start the flower with the command:

 celery flower -A myproj

it connect correctly to Rabbit:

[I 150519 14:09:54 command:114] Visit me at http://localhost:5555
[I 150519 14:09:54 command:116] Broker: amqp://user:**@localhost:5672//
[I 150519 14:09:54 command:119] Registered tasks:
...
[I 150519 14:09:54 mixins:225] Connected to amqp://user:**@localhost:5672//

the porblem is the inspect method failed:

[W 150519 14:09:56 control:43] 'stats' inspect method failed
[W 150519 14:09:56 control:43] 'active_queues' inspect method failed
[W 150519 14:09:56 control:43] 'registered' inspect method failed
[W 150519 14:09:56 control:43] 'scheduled' inspect method failed
[W 150519 14:09:56 control:43] 'active' inspect method failed
[W 150519 14:09:56 control:43] 'reserved' inspect method failed
[W 150519 14:09:56 control:43] 'revoked' inspect method failed
[W 150519 14:09:56 control:43] 'conf' inspect method failed

So the management web is empty.

**Comment by aliasmrchips** [comment]
Same issue... but with redis as the broker.

flower==0.8.2

**Comment by mher** [comment]
What is the output of `celery -A myproj inspect ping` command?

**Comment by aliasmrchips** [comment]
Error: No nodes replied within time constraint.

**Comment by lendoly** [comment]
same error as @aliasmrchips

**Comment by mher** [comment]
`Error: No nodes replied within time constraint.` means no worker replies to queries. It can happen if the workers are busy. You can try to increase the timeout (`--inspect_timeout` option in flower and `celery inspect -t` with celery).

**Comment by aliasmrchips** [comment]
Sorry, no worker was running before...  If I start a worker, I get:

> -> celery@hostname: OK
>        pong

So, the problem seems to be starting flower before the worker(s).  If I start a worker and then start flower, it works as expected.  If I shut down both celery worker(s) and flower and then start flower _before_ the celery worker, I get:

> Unknown worker 'celery@hostname'

I believe this is the case whether or not it is a previously seen worker or a new one.  In either case, I cannot inspect the workers if they are started after flower is running.  Is this correct?

**Comment by mher** [comment]
There is a `Refresh` button on the dashboard page. It refreshes workers by resending inspect command. If you launch workers after flower just refresh workers.

**Comment by aliasmrchips** [comment]
Ah... Thanks!  This fixed the "issue" for me.  That is, it was not really an issue at all.  Anyway, for anyone else who may experience this:  The ```Refresh``` button is a choice under the drop down menu that has ```Shut Down``` selected by default.  In order to ```Refresh```, you have to select a worker (or all of them) first.

**Comment by lendoly** [comment]
Ok with the --inspect_timeout now is working correctly. Thanks

**Comment by Wu4m4n** [comment]
I have the same issue, but i cant fixit.
anyone can paste the full celery command related of how this could work.

this is the result of my inspect ping
celery -A tasks inspect ping
Error: No nodes replied within time constraint.

**Comment by darkpixel** [comment]
I appear to be running into the same/similar issue.  There is no 'refresh' on the dashboard tab, but it does show my worker, and that it is online.

Clicking on the worker gives ```Unknown worker 'celery@c98ff5d2e475'```.

I'm using RabbitMQ for my broker and Redis for my results backend.

Jobs run perfectly, I just can't use flower to look at a worker.
```
09:49:09 [aaron@praxis:~/code/uitintranet] [uitintranet] develop ± pip freeze | grep -i flower
flower==0.8.2
09:50:45 [aaron@praxis:~/code/uitintranet] [uitintranet] develop ± DATABASE_URL=postgres://uitintranet:PASSWORD@tetrad.utilizeit.com/uitintranet PRODUCTION=True BROKER_URL=amqp://intranet:PASSWORD@tetrad.utilizeit.com:5672/intranet REDIS_URL=redis://tetrad.utilizeit.com:6379/0 python manage.py celery inspect ping
-> celery@c98ff5d2e475: OK
        pong
09:51:04 [aaron@praxis:~/code/uitintranet] [uitintranet] develop ± 
```
![screenshot from 2015-08-12 09 52 03](https://cloud.githubusercontent.com/assets/158380/9230592/ef4a1e08-40d7-11e5-95ce-b5684abe8349.png)

**Comment by jackyfkc** [comment]
@darkpixel  The refresh button is on the dashboard page, workers' table. You will see a triangle button there.

**Comment by darkpixel** [comment]
It wasn't there.  No worries.  I ran into an old multithreading bug between celery and python and switched to python-rq last weekend.  The dashboard isn't as nice.  ;)

**Comment by asmodehn** [comment]
I had this issue as well.

When starting flower, many inspect methods failed.
As a result /api/workers returns empty.

I manually refreshed on the dashboard, then /api/workers returned the workers.

=> In a changing environment (workers going up and down ), it would be important to have flower periodically refreshing by itself, in order to get the updated workers data...
Is this currently doable ? Is this feature in a roadmap already ?

**Comment by Aameer** [comment]
I am also facing the issue where  i don't see any graphs on flower but the console for me shows this JS error `Uncaught TypeError: Cannot read property 'length' of undefined`.
![flower_admin](https://cloud.githubusercontent.com/assets/5312949/14226883/c3e0294a-f90c-11e5-8fd0-6b5a2522a822.png) I am using flower==0.9.0 and I am using circus to daemonize it.

**Comment by tbindi** [comment]
There should be a way to gracefully say that it was not able to see any workers when the Flower started to avoid method failed messages that don't send out the right message for any developer.

**Comment by delijati** [comment]
I got the same error with python3.5 ... I had to remove the `--autoreload`

**Comment by riyadparvez** [comment]
+1, same issue.

**Comment by Xepe** [comment]
Hello,

I was working with celery 3.1.24, I reviewed my packages and I found that I was using kombu 3.0.36, I downgraded it to previous version 3.0.35 and with that I solved my issue. 

Hope this help.

**Comment by emaste-r** [comment]
i gei it...

cmd > celery -A task worker
another cmd > celery flower

it works....

**Comment by imomaliev** [comment]
https://stackoverflow.com/a/54570067/3627387 reposting my answer here

Problem here that, flower starts before celery is ready

This could be easily checked with `celery inspect ping`

Here is example from my project

```
until timeout -t 10 celery -A project inspect ping; do
    >&2 echo "Celery workers not available"
done

echo 'Starting flower'
celery -A project flower
```
