### ISSUE TITLE
Error during WebSocket handshake

### ISSUE THREAD

**Issue by JameelMohammed** [mher/flower#403]
I followed this code snippet:

var ws = new WebSocket('ws://localhost:5555/api/task/events/task-succeeded/');
ws.onmessage = function (event) {
    console.log(event.data);
}

I am getting this error

WebSocket connection to 'ws://localhost:5555/api/task/events/task-succeeded/' failed: Error during WebSocket handshake: Unexpected response code: 403

**Comment by cbronazc** [comment]
I am also getting this one also but with nginx. Everything works when both the nginx host is set to / and there is no url prefix. But when I change the nginx path to `/flower` and add `--url_prefix=flower` to the flower server I get `/flower/update-workers' failed: Error during WebSocket handshake: Unexpected response`.

**Comment by troygrosfield** [comment]
@cbronazc, ``url_prefix`` is a deprecated option:

- https://github.com/mher/flower/blob/4ab84c054bca5233523e4b69da179659330625d5/flower/options.py#L64

**Comment by mher** [comment]
Please provide flower and browser version info

**Comment by dkdndes** [comment]
experience the same error when I open the page in my browser

chrome Version 46.0.2490.86 (64-bit)

0.8.3
3.1.19 (Cipater)
flower   -> flower:0.8.3 tornado:4.3 babel:2.1.1
software -> celery:3.1.19 (Cipater) kombu:3.0.29 py:2.7.10
            billiard:3.3.0.21 py-amqp:1.4.7
platform -> system:Darwin arch:64bit imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled

**Comment by dkdndes** [comment]
I added now "check_origin" in flower/api/[__init__.py](https://github.com/mher/flower/blob/master/flower/api/__init__.py)

    class BaseWebSocketHandler(tornado.websocket.WebSocketHandler):
        # listeners = [], should be created in derived class

        def check_origin(self, origin):
            return True

to ignore the origin check responsible for the 403 errir while I develope but thats not a fix.

**Comment by dkdndes** [comment]
Somehow it would have been easier if I would have known that I need to setup a secure environment to avoid the error message. Somehow it is for me not so obvious that you need to understand first

* [Keys, Certificates and CA Certificates](https://www.rabbitmq.com/ssl.html)
* [Setup of Celery Security](http://docs.celeryproject.org/en/latest/configuration.html#security)
    
and then setup secure keys, etc.

    CELERY_SECURITY_KEY = '/etc/ssl/private/worker.key'
    CELERY_SECURITY_CERTIFICATE = '/etc/ssl/certs/worker.pem'
    CELERY_SECURITY_CERT_STORE = '/etc/ssl/certs/*.pem'
    from celery.security import setup_security
    setup_security()

to avoid the above error message. 

It would be nice to include the explanation somewhere in the documentation and if in the source DEBUG would be used at these parts (serializer.py, line 174, TRUSTED_CONTENT, etc. ) as you would do in Django core. 

What do you think about the idea?

**Comment by mher** [comment]
Sorry for late response. Yes, please open a pull request.
