### ISSUE TITLE
Bug in flower.utils.tasks line 44

### ISSUE THREAD

**Issue by mdallen22** [mher/flower#404]
This call to **satisfies_search_terms** https://github.com/mher/flower/blob/master/flower/utils/tasks.py#L44 is missing the *args_search_terms* parameter, https://github.com/mher/flower/blob/master/flower/utils/search.py#L28.

**Comment by mher** [comment]
@Melevir

**Comment by Melevir** [comment]
Thanks for the report. Will fix this in a couple of days.

**Comment by ThiefMaster** [comment]
Still broken

**Comment by mher** [comment]
Fixed by #426
