### ISSUE TITLE
Use simplejson instead of json

### ISSUE THREAD

**Issue by nautilus28** [mher/flower#410]
https://github.com/mher/flower/blob/master/flower/api/tasks.py#L73

flower calls json.dumps for updating results, so probably using simplejson speeds up the process over the standard json library. Does anyone notice and experiment with it? if so, please let me know about the results.

Thanks,
Canh

**Comment by ThiefMaster** [comment]
Isn't `json` just `simplejson` added to stdlib?

**Comment by nautilus28** [comment]
@ThiefMaster yes, only pure Python code with no dependencies was added, but simplejson includes an optional C extension for a serious speed boost. Simplejson encoding is faster than the standard json encoding 2-3x. 

Maybe the flower's authors want to keep dependencies as small as possible.

**Comment by mher** [comment]
Without benchmarking and real performance issues it sounds like a premature optimization.
