### ISSUE TITLE
Monitor doesn't tell me the metric of running time

### ISSUE THREAD

**Issue by hakanw** [mher/flower#413]
Is it in milliseconds? Or seconds? Or something else? A metric should be used here to describe the times...

![skarmavbild 2015-06-16 kl 23 25 44](https://cloud.githubusercontent.com/assets/100824/8196434/4d565034-148c-11e5-8503-ea6474faa507.png)

**Comment by mher** [comment]
Fixed, thanks!

**Comment by hakanw** [comment]
Wonderful! Thanks @mher
