### ISSUE TITLE
Tasks list does not persist a restart

### ISSUE THREAD

**Issue by scorpiontahir02** [mher/flower#415]
I am running flower using supervisord with command:
python manage.py celery flower --address=127.0.0.1 --port=5555 --url_prefix=flower --persistent=True --basic_auth=abc:cba
but still when I use supervisorctl restart on this process tasks list does not persist and all the previous information is deleted.
Am I doing something wrong or there is some issue?

**Comment by mher** [comment]
Have you tried the latest version? There was a bug in one of the previous versions.

**Comment by scorpiontahir02** [comment]
I haven't checked the version but I installed it today just 4, 5 hours back via "pip install flower" so it should be the latest version.

**Comment by scorpiontahir02** [comment]
One other thing, number of completed tasks in workers tab persist restart and does not go to '0' but task list in tasks tab does not persist.

**Comment by mher** [comment]
The master version works as expected. I'll release a new version.

**Comment by krismaya** [comment]
I'm having the same issue, as mtahirtariq facing. I'm attached the empty task after restart the flower.
FyI, I'm Using flower==0.9.1, Is this version having same issue?
Please revert and thank you so much..
![taks_empty](https://cloud.githubusercontent.com/assets/19259712/18464973/c92da6a4-79b1-11e6-8262-bf941cb86c7b.png)

**Comment by krismaya** [comment]
I'm having the same issue, as mtahirtariq facing. I'm attached the empty task after restart the flower.
FyI, I'm Using flower==0.9.1, Is this version having same issue?
Please revert and thank you so much..

![flower_empty](https://cloud.githubusercontent.com/assets/19259712/18465078/628b58e6-79b2-11e6-8b9b-e8dfac957f52.png)

**Comment by chavenor** [comment]
@krismaya Just run flower with the following flag ```--persistent=true``` the tasks will stick around for awhile.

**Comment by khankuan** [comment]
@krismaya I have the same problem too. Setting CELERY_RESULT_PERSISTENT or `--persistent=true` did not work :/
