### ISSUE TITLE
flower.events seems to ignore configured logging level for b'[DEBUG]: Enabling events' message

### ISSUE THREAD

**Issue by rschwiebert** [mher/flower#419]
I am getting numerous b'[DEBUG]: Enabling events' messages from flower.events which I am trying to eliminate from logging.

In my logging dictconfig, I have levels set to WARNING and a custom handler that puts the messages into a Redis instance.

I am positive that flower is using this config: its messages appear in Redis. However, it is ignoring the WARNING logging level (I see DEBUG messages from flower.events.)

The WARNING level is certainly working for all other loggers: I cannot find any events lower than WARNING (other than the celery logs.)

I don't see DEBUG messages from any other flower modules, which I would expect if something were misconfigured with logging. It looks like this is something special to the events module. Is something about the order things are used causing this?

**Comment by mher** [comment]
Sorry for late response. Which version is this? The latest versions don't log about enabling events and there is an option [enable-events](https://flower.readthedocs.org/en/latest/config.html#enable-events) for disabling periodic events.

**Comment by rschwiebert** [comment]
Judging from the requirements file, it looks like 0.7.3.

**Comment by mher** [comment]
Updating the flower version will fix the problem
