### ISSUE TITLE
Flower API and CORS

### ISSUE THREAD

**Issue by asmodehn** [mher/flower#429]
I am trying to use the flower API as a REST backend to a webapp frontend ( potentially sitting on a different host ) that I am writing now.
However I am having issues with CORS requests. It seems to me that the preflight request is not handled properly : 

```
[W 150718 11:57:01 web:1811] 405 OPTIONS /api/tasks (127.0.0.1) 19215.00ms
```
```
[E 150718 11:51:49 web:931] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/opt/ros/indigo/lib/python2.7/dist-packages/tornado/web.py", line 929, in send_error
        self.write_error(status_code, **kwargs)
      File "/home/alexv/ROS/gopher_concert/src/flask-ext-catkin/src/flower/views/__init__.py", line 48, in write_error
        self.write(message)
      File "/opt/ros/indigo/lib/python2.7/dist-packages/tornado/web.py", line 656, in write
        raise TypeError("write() only accepts bytes, unicode, and dict objects")
    TypeError: write() only accepts bytes, unicode, and dict objects
[W 150718 11:51:49 web:1811] 405 OPTIONS /api/task/async-apply (127.0.0.1) 2579.07ms
```

So, should I be able to make CORS requests to flower backend ?
Or is there something I am missing here ? 
By the way, I'm using v0.8.2

**Comment by asmodehn** [comment]
Also after I managed to disable the preflight request by using "text/plain" as the contentType of my request, I still cannot process the reply as : 
`XMLHttpRequest cannot load http://localhost:5555/api/tasks. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8888' is therefore not allowed access.`

**Comment by asmodehn** [comment]
I added tornado-cors mixin to BaseHandler and it seems to have done the trick...
Please let me know if this is acceptable for you and I ll do a pull request for it once I have tested it more.

**Comment by asmodehn** [comment]
https://github.com/mher/flower/pull/433

**Comment by mher** [comment]
Closing this issue. There is a pull request #433

**Comment by tiktuk** [comment]
I am having the same issue, could be nice to have the pull request pulled :) .

**Comment by nevelis** [comment]
Guess we should've closed the issue after the pull request was merged! 👍
