### ISSUE TITLE
make datetime arguments ( like 'eta' ) support ISO8601 ? 

### ISSUE THREAD

**Issue by asmodehn** [mher/flower#431]
Just a proposition, instead of using a custom format : `DATE_FORMAT = '%Y-%m-%d %H:%M:%S.%f'`
The question would be which python library should we use for this ? Celery seems to have a custom implementation( that maybe we can use ? ), but there also are python packages for this...
Let me know if this would be suitable, I might be able to work on it sometime...

**Comment by mher** [comment]
Feel free to send a pull request.

I think converting DATE_FORMAT to ISO8601 will work. For backward compatibility it is important to support the old custom format as well.

**Comment by mher** [comment]
There are no plans to work on this feature at the moment until someone decides to contribute to the project.
