### ISSUE TITLE
GET /api/workers

### ISSUE THREAD

**Issue by asmodehn** [mher/flower#438]
When I do this request on my setup, in order to get information on the workers, I get only :

```javascript
{
    "celery@alexv-PC": {
        "conf": {
            "TESTING": false,
            "CELERY_ALWAYS_EAGER": false,
            "CELERY_RESULT_SERIALIZER": "json",
            "CELERY_ACCEPT_CONTENT": [
                "application/json"
            ],
            "CELERY_INCLUDE": [
                "celery.app.builtins",
                "gopher_rocon_bootstrap.celery_tasks"
            ],
            "CELERY_IMPORTS": "gopher_rocon_bootstrap.celery_tasks",
            "REDIS_URL": "redis://localhost:6379",
            "CELERY_BROKER_URL": "redis://localhost:6379//",
            "DEBUG": true,
            "CELERY_TASK_SERIALIZER": "json",
            "CELERY_RESULT_BACKEND": "redis://localhost:6379"
        }
    }
}
```

Any idea what would be the problem here ? Why cant I get all informations about my worker like the [documentation specifies](http://flower.readthedocs.org/en/latest/api.html#get--api-workers)  ?

Related to this, on the webpage I see my worker as "online" in the first page. But when I click on it I get : 
`[W 150730 19:18:10 web:1404] 404 GET /worker/celery@alexv-PC (127.0.0.1): Unable to get stats for 'celery@alexv-PC' worker`

FYI 
```
alexv@alexv-PC:~$ ping alexv-PC
PING alexv-PC (127.0.1.1) 56(84) bytes of data.
64 bytes from alexv-PC (127.0.1.1): icmp_seq=1 ttl=64 time=0.021 ms
```

Also my celery configuration is : 
```python
CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ALWAYS_EAGER = False  # We do NOT want the task to be executed immediately locally.
```

Thanks for any input or advice...

**Comment by mher** [comment]
The doc link is for master version. There was a change in API.

**Comment by mher** [comment]
Refreshing the dashboard (there is a "Refresh" button on the Dashboard page) should eliminate "Unable to get stats for xxx worker" errors.

**Comment by asmodehn** [comment]
I found out something... In the case in my example, if alexv-PC is not resolvable from the flower server, then the statistics are not available. I tested in the flower web page, but I would think the same applies for flower REST API.

My network setup is not clean, and hostname/DNS resolution might be different from the server to the worklers, or for one worker to another...

I wonder how it is supposed to work if someone only has (static?) IP setups with local-only hostname and no DNS to resolve the hostnames ( usual custom home network situation )...
