### ISSUE TITLE
missing broker stats for redis

### ISSUE THREAD

**Issue by jerzyk** [mher/flower#439]
when using redis with priority queues, flower is displaying only requests that are assigned only with queue and priority 0.

Prioritization is done internally by kombu's redis transport (kombu/transport/redis.py:Channel).
Kombu is creating n queues (controlled by `PRIORITY_STEPS` parameter, default: [0, 3, 6, 9]).
Queue names are created by concatenating queue name, prefix (default: '\x06\x16') and priority for all priority values except 0, for 0 (highest) a raw queue name is used.

Priority steps were implemented in version 3.0, it's default value can be override by specifying `priority_steps` as array in sort order in `BROKER_TRANSPORT_OPTIONS` config variable.

Flower does not read celery configuration nor have an option to specify what queue names shall be inspected. Instead all queue names are read by inspecting workers. Unfortunately in this scenario, only the raw queue name is reported by workers, not their prioritized names.

I can try to add this functionality, but there are design decisions needed. Basic implementation can be done in three ways:
1. add option to specify all queue names - I do not like this, because it looks like step backward, but it may be used as "additional queues to look at" - but then there will be multiple queues on the graph (not necessary bad thing)
2. add option to specify redis priorities only - much better, because then, `llen` will be used by inspecting all workers active queues, plus it is quite simple to implement
3. extend option 2 to read all default config from celery - definitely more work 

Let me know which option or any other is better, so I can help.

**Comment by mher** [comment]
Actually readnig celery options is pretty trivial. Try `self.capp.conf.BROKER_TRANSPORT_OPTIONS`. Those options can be passed to https://github.com/mher/flower/blob/master/flower/utils/broker.py#L99 and it will allow to avoid introducing a new flower option.
