### ISSUE TITLE
/api/tasks broken in versions > 0.8.2

### ISSUE THREAD

**Issue by inactivist** [mher/flower#445]
Hitting /api/tasks results in an empty response (or blank page if you're using a browser), and an exception message on the console:

    [E 150811 13:53:00 web:1407] Uncaught exception GET /api/tasks (127.0.0.1)
        HTTPServerRequest(protocol='http', host='localhost:5555', method='GET', uri='/api/tasks', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': 'localhost:5555', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36', 'Connection': 'keep-alive', 'Cookie': '<snip>', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1'})
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1332, in _execute
            result = method(*self.path_args, **self.path_kwargs)
          File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 2607, in wrapper
            return method(self, *args, **kwargs)
          File "/Users/someuser/.virtualenvs/someproject/lib/python2.7/site-packages/flower/api/tasks.py", line 447, in get
            worker=worker, state=state):
          File "/Users/someuser/.virtualenvs/someproject/lib/python2.7/site-packages/flower/utils/tasks.py", line 21, in iter_tasks
            any_value_search_term = search_terms.get('any', None)
        AttributeError: 'NoneType' object has no attribute 'get'

Looking at the [tasks api code](https://github.com/mher/flower/blob/master/flower/api/tasks.py#L445) it appears that it's not passing search_terms, and [utils.iter_tasks](https://github.com/mher/flower/blob/master/flower/utils/tasks.py#L25) requires that parameter (compare [views/tasks usage](https://github.com/mher/flower/blob/master/flower/views/tasks.py#L59)) -- I've not debugged further, but it appears `utils.iter_tasks` requires a dict-like `search_terms` parameter (though it defaults to `None`).

Additional info:

OSX Mavericks
Python 2.7
Installed from master per README.md

    $ pip install https://github.com/mher/flower/zipball/master
    Using download cache from /Users/someuser/.pip/cache/https%3A%2F%2Fgithub.com%2Fmher%2Fflower%2Fzipball%2Fmaster
    Running setup.py (path:/var/folders/gr/[some-random-string]/T/pip-XzWWtZ-build/setup.py) egg_info for package from https://github.com/mher/flower/zipball/master
        
    Requirement already satisfied (use --upgrade to upgrade): celery>=3.1.0 in /Users/someuser/.virtualenvs/someproject/lib/python2.7/site-packages (from flower==0.9.0)
    Requirement already satisfied (use --upgrade to upgrade): tornado>=4.0.0 in /usr/local/lib/python2.7/site-packages (from flower==0.9.0)
    Requirement already satisfied (use --upgrade to upgrade): babel in /Users/someuser/.virtualenvs/someproject/lib/python2.7/site-packages (from flower==0.9.0)
    Requirement already satisfied (use --upgrade to upgrade): pytz in /Users/someuser/.virtualenvs/someproject/lib/python2.7/site-packages (from flower==0.9.0)
    Requirement already satisfied (use --upgrade to upgrade): futures in /Users/someuser/.virtualenvs/someproject/lib/python2.7/site-packages (from flower==0.9.0)
    Requirement already satisfied (use --upgrade to upgrade): billiard>=3.3.0.19,<3.4 in /Users/someuser/.virtualenvs/someproject/lib/python2.7/site-packages (from celery>=3.1.0->flower==0.9.0)
    Requirement already satisfied (use --upgrade to upgrade): kombu>=3.0.24,<3.1 in /Users/someuser/.virtualenvs/someproject/lib/python2.7/site-packages (from celery>=3.1.0->flower==0.9.0)
    Requirement already satisfied (use --upgrade to upgrade): certifi in /usr/local/lib/python2.7/site-packages (from tornado>=4.0.0->flower==0.9.0)
    Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname in /usr/local/lib/python2.7/site-packages (from tornado>=4.0.0->flower==0.9.0)
    Installing collected packages: flower
      Running setup.py install for flower
        warning: build_py: byte-compiling is disabled, skipping.
        
        warning: install_lib: byte-compiling is disabled, skipping.
        
        
        Installing flower script to /Users/someuser/.virtualenvs/someproject/bin
    Successfully installed flower
    Cleaning up...
    $ flower --broker=amqp://guest:guest@localhost:5672// --address=0.0.0.0 --port=5555
    [I 150811 13:51:42 command:116] Visit me at http://0.0.0.0:5555
    [I 150811 13:51:42 command:118] Broker: amqp://guest:**@localhost:5672//
    [I 150811 13:51:42 command:121] Registered tasks: 
        ['celery.backend_cleanup',
         'celery.chain',
         'celery.chord',
         'celery.chord_unlock',
         'celery.chunks',
         'celery.group',
         'celery.map',
         'celery.starmap']
    [I 150811 13:51:42 mixins:225] Connected to amqp://guest:**@127.0.0.1:5672//

**Comment by mher** [comment]
Thanks for the report! Can you open a pull request?

**Comment by inactivist** [comment]
Just tested this against 0.8.3 on Pypi, same problem?  0.8.2 seems to work fine.

WRT pull request, I'd love to, but not sure when I'll be able to get around to it.  I'll investigate.

**Comment by mher** [comment]
Fixed by https://github.com/mher/flower/commit/79ef3fe160322781f567bbf88a3289803d1fe2e7

**Comment by Loknar** [comment]
hate to be that guy but are plans on releasing a new version with this fix? :crying_cat_face: is there a scheduled new version release soon?
