### ISSUE TITLE
REST API to schedule tasks

### ISSUE THREAD

**Issue by asmodehn** [mher/flower#448]
I am in need of a REST API to schedule tasks, modify existing schedule, etc.
Is it something in the scope of flower ? 

I already use a redis backend so my schedule class could be something like https://github.com/kongluoxing/celerybeatredis

But I would still need a REST API to store this in Redis from a webapp...

Or is there another solution that I am not aware about ?

Thank you for any info !

**Comment by jackyfkc** [comment]
It is beyond the power of Flower since `Celery` does not supporting remote control `beat`.

**Comment by asmodehn** [comment]
I'm not sure why we would need to remote control beat...

Maybe I'm over simplifying but : 
1) The web rest backend sends the schedule to redis and can modify it live.
2) The beat process periodically reads from redis and dispatch the task at the correct time.

**Comment by asmodehn** [comment]
@aig- : could you detail what this commit fixes please ?
I dont really understand how it relates this issue...
