### ISSUE TITLE
Abort from REST API

### ISSUE THREAD

**Issue by asmodehn** [mher/flower#450]
Hello,

I am using [AbortableTask](http://celery.readthedocs.org/en/latest/reference/celery.contrib.abortable.html) as a base for my tasks.

I would like to be able to abort a running task, using the REST API.
I dont think this is currently supported, correct ?

Where would I start to look if I want to implement such a feature in flower ?

**Comment by mher** [comment]
There is no api method to abort abortable tasks. It is possible to terminate running tasks though http://flower.readthedocs.org/en/latest/api.html#post--api-task-revoke-(.+)

If you want to implement, have a look how the `/result` method is implemented https://github.com/mher/flower/blob/master/flower/api/tasks.py#L274

**Comment by asmodehn** [comment]
Thank you for the information.
I ll have a look at implementing that. not sure about ETA yet though...

**Comment by asmodehn** [comment]
I played a bit with revoke, but according to celery doc , revoke should not be used programmatically to temrinate an already running task : http://docs.celeryproject.org/en/latest/userguide/workers.html#revoke-revoking-tasks
Revoke should be used to not execute a task before it gets executed on the worker. But if the task is already running, Abort is the proper choice. http://docs.celeryproject.org/en/latest/reference/celery.contrib.abortable.html

So it looks like I will have to implement this feature sometime soon...
I ll keep you posted.

**Comment by asmodehn** [comment]
Made a quick pull request there to implement abort : https://github.com/mher/flower/pull/525
Let me know what you think.
