### ISSUE TITLE
format_task not properly applied

### ISSUE THREAD

**Issue by BastienFaure** [mher/flower#451]
Hello all,

First, thank you to core devs, I really like this nice webUI and I'm using it daily for monitoring mail campaigns :+1: 

My problem is the following : I'm passing some args to a celery tasks and want to display only some of them in the dashboard : I also made use of the "format_task" option in the flower config file but the task.args attribute seems to be passed as an unicode object instead of a list, so I cannot access to a specific arg (knowing his index)

For the following config file

````
from flower.utils.template import humanize

def format_task(task):
    task.args = str(type(task.args))
    task.result = humanize(task.result, length=20)
    return task
```

I got the following output 

![selection_012](https://cloud.githubusercontent.com/assets/5211907/9451821/367cfc5e-4ab1-11e5-9711-77d3deb558ae.png)

What what I want is to do `task.args = task.args[2]`

**Comment by mher** [comment]
flower gets the string representation of arguments from celery workers. It doesn't parse them.

**Comment by mher** [comment]
It should be easy to parse and filter args in format_task.
