### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by lovasko** [mher/flower#453]
The method `celery.app.task.update_state` supports metadata to be handed over. Is there any plan on supporting the state name "PROGRESS" and the metadata dictionary to render a progress bar of a task based on some agreed dictionary structure?

**Comment by schaubl** [comment]
:+1: This would be very useful.

I had a quick look into the code to see how to implement that and what I understood is that Flower is only receiving events but there is no event sent in the state PROGRESS or any custom state.
So the only way to do this will be to periodically consume messages from the result backend.

Am I right ?

**Comment by schaubl** [comment]
I just discovered the issue #143 which answered my question.

**Comment by mher** [comment]
`task-custom` events are added to the event list https://github.com/mher/flower/pull/478

**Comment by EugZol** [comment]
Is there a complete working example somewhere?

I tried the following:

```
@shared_task(bind=True)
def test_task(self):
    from time import sleep

    for i in range(1, 101):
        sleep(1)
        self.send_event('task-progress', current=i, total=100)
```

This leads to state 'PROGRESS' being displayed in Flower, but no `current`/`total` is seen anywhere.

**Comment by EugZol** [comment]
#1071 1071
