### ISSUE TITLE
Passing 'queue' as option to async_apply REST API is ignored/not working

### ISSUE THREAD

**Issue by asmodehn** [mher/flower#456]
It seems to me so far that by default the dictionnary keys that we pass are unicode strings.
But celery option structure seems to expect normal strings...
In my case when I reach send_task() code in celery/app/base.py, my option dict looks like : 
```python
{
    'time_limit': None,
    'mandatory': None,
    'compression': None,
    'exchange': None,
    'delivery_mode': None,
    'routing_key': None,
    'immediate': None,
    'queue': None,
    'soft_time_limit': None,
    u'options': {
        u'queue': u'alexv-PC'
    },
    'serializer': 'json',
    'priority': None
}
```

Any hint on the best way to fix this ?

**Comment by asmodehn** [comment]
Note : This might be fixed as of 0.8.4.
However I m working on a fork with quite a few patches, so I cant be sure about actual flower code.

**Comment by mher** [comment]
Please test with the master version before opening a ticket.

**Comment by asmodehn** [comment]
OK I finally found the reason for this.

This code https://github.com/mher/flower/blob/master/flower/api/tasks.py#L29
and this documentation https://github.com/mher/flower/blob/master/flower/api/tasks.py#L196
conflict.

Reading https://github.com/mher/flower/blob/master/flower/api/tasks.py#L196
I understand my async-apply request body should be
```
{
    "args": [],
    "kwargs":{
        "myarg": "myval"
    },
    "options":{
        "queue": "myq"
    }
}
```
but reading the code in https://github.com/mher/flower/blob/master/flower/api/tasks.py#L29 I now understand that my async-apply request body should be
```
{
    "args": [],
    "kwargs":{
        "myarg": "myval"
    },
    "queue": "myq"
}
```
