### ISSUE TITLE
Successed Task is still listed as active in the worker

### ISSUE THREAD

**Issue by asmodehn** [mher/flower#457]
On the worker Task tab, I can still see the task as active.
But manually running inspect active returns `- empty -`
However on the global Task tab, the task is marked as "SUCCESS"

So It seems the worker information is out of date ?
Note : I did refresh the workers info from the dashboard before that.

**Comment by asmodehn** [comment]
I had a debug run through the code, and I found that in control.py aound l45:

If there is no active task running on the worker now, we have this case : 
```python
            for worker, response in result.items():        # response = []
                if response:                                             # False
                    info = cls.worker_cache[worker]         # worker data not updated
                    info[cls.INSPECT_METHODS[i]] = response
```

not sure what would be the proper fix though...

**Comment by asmodehn** [comment]
FYI : ``` if response is not None : ``` seems to fix my problem without undesired effects so far...

**Comment by mher** [comment]
Worker tab gets info using celery inspect methods. There can be delays in responses if a worker is busy.
