### ISSUE TITLE
Flower not show tasks send before worker online?

### ISSUE THREAD

**Issue by yclod** [mher/flower#459]
Hi I set Celery with Rabbitmq as backend,

1) if the worker's status is online firstly, and then I send tasks use app.send_task(), the Flower can show the tasks run on worker correctly, 
2) but if I disconnect worker firstly, then send some tasks, the tasks save in the queue, and then I connect the worker, the worker can consume message from rabbitmq, and do the job correctly, but Flower cannot show those part of tasks.

Does any one meet this issue?

Thanks!

**Comment by ask** [comment]
Are you using `CELERY_SEND_TASK_SENT_EVENTS`?

Only the worker sends task events by default, but if you enable this setting the clients will also send an event whenever a task is sent, so you will be able to monitor them before they are received by a worker.

**Comment by yclod** [comment]
@ask Thanks for replying, I set the CELERY_SEND_TASK_SENT_EVENT = True on client, and send the tasks when worker is offline, the tasks can be found in "Queued tasks" in Flower/Monitor page, but when I reconnect  the worker back to online, the worker will consume the tasks and do the job, but after that, in Flower/Dashboard, the numbers still don't change for "Processed/Failed/Succeeded" for that worker.

**Comment by yclod** [comment]
oh, I think I find the tasks in Flower/Tasks page, they are all in PENDING status, of course cannot be found in dashboard, but see from worker's console, the tasks were all succeeded, why the status are pending instead of Succeeded in this situation? I tested same tasks in both way (both with CELERY_SEND_TASK_SENT_EVENT = True ):
1) worker connected previously, the tasks will succeed
2) send the tasks firstly then connect worker, the same tasks are pending, why?
Could you share some information about that? Thanks!

**Comment by yclod** [comment]
set correct CELERY_RESULT_BACKEND fixed that problem. Closing it. Thanks.
