### ISSUE TITLE
Flower is not loading password when broker url contains os.getenv("redis_pw")

### ISSUE THREAD

**Issue by Scriptkiddi** [mher/flower#461]
```BROKER_URL = 'redis://:{}@redis:6379/0'.format(os.getenv("redis_pw"))``` is not working when starting flower with``` flower -A mydjangoproject``` but if i do ```BROKER_URL = 'redis://mysupersecretpassword@redis:6379/0'``` its working

**Comment by mher** [comment]
Broker URL should be passed via `--broker` or `-A` options
 
    flower --broker=redis://:$redis_pw@redis:6379/0

**Comment by Scriptkiddi** [comment]
since flower reads my django config should it not also read the broker_url correctly?
