### ISSUE TITLE
Specify default sorting for tasks

### ISSUE THREAD

**Issue by jbub** [mher/flower#463]
Hello, is there a way to specify default sorting field for "Tasks" view ? For example i want to always order tasks by the "Received" field by default. Thank you.

**Comment by mher** [comment]
The default task sorting is not customizable

**Comment by gsemet** [comment]
Could be done by the URL (`&sort=task:desc`) for example

**Comment by mher** [comment]
There are no plans to work on this feature at the moment until someone decides to contribute to the project.

**Comment by yarikoptic** [comment]
FWIW, this issue probably the one I was thinking about too: to reflect chosen interactively search & sorting within the url so it could then be persistently or shared to be seen by others.
