### ISSUE TITLE
Ability to get worker status via REST ?

### ISSUE THREAD

**Issue by asmodehn** [mher/flower#464]
I would like to get the status of a worker (online / offline) via REST.
But it seems the worker is always returned by the REST API, and the flower webpage uses a websocket to get the status information.

Is there a way to get this information via the REST API instead ? Or should I, from another website, use the websocket and expect it to always work in the future ?

**Comment by mher** [comment]
`/api/workers?status=1` returns worker's status (see also https://github.com/mher/flower/issues/383#issuecomment-125452318)
