### ISSUE TITLE
Result of Task being Truncated

### ISSUE THREAD

**Issue by michaelhelmick** [mher/flower#465]
The result column on my task view is being truncated to 110 characters.

After doing a little research (in the issues, code and flower conf); I found it was suggested to use `flowerconfig.py` and define a `format_task` function. Which I did.

```python
from flower.utils.template import humanize

def format_task(task):
    print 'in format task!'
    task.result = humanize(task.result, length=1000)

    return task
```

The print get logged. But my result column is still truncated.

**Comment by nocrosstalk** [comment]
I can confirm this behavior. It seems this format_task function is not applied at all. When I replace task.result='Dummy result', this is not what I get as result.

**Comment by anupsabraham** [comment]
Same issue happens for me. I tried debugging by printing task.result before calling humanize method. It seems the task.result is already truncated before calling the format_task method. The format_task can only reduce the number of characters(<110) by calling humanize method on already truncated task.result.

**Comment by anupsabraham** [comment]
Is there any update on this?

**Comment by mher** [comment]
This is how celery works. Results are truncated and stringified in events.

**Comment by shsdev** [comment]
It seems to me that closing comment (@mehr) does not address the issue completely. I can also confirm that the 'format_task' function in flowerconfig.py is not being applied at all.

**Comment by bcoover** [comment]
same results for me

**Comment by bcoover** [comment]
Ok, I am seeing the full results in the backend (using database), but it seems that flower is instead using events, which are indeed truncated, with no option to extend until Celery 4
