### ISSUE TITLE
api/task/info and api/task/result show different status for same taskID

### ISSUE THREAD

**Issue by nocrosstalk** [mher/flower#470]
I run tasks that takes several minutes to complete. The api/task/info servcie shows the correct status, and result but truncates the result. When trying to access the result via api/task/result I always get a 'PENDING' state, though the info service says 'SUCCESS'. Would be OK if the info servcie would not truncate the result.

**Comment by mher** [comment]
See https://github.com/mher/flower/issues/471#issuecomment-141667948. `/api/task/info` and `/api/task/result` use different sources. The results from `/api/task/info` come from celery events and can be truncated.

**Comment by keepangry** [comment]
I have the same problem.  /api/task/result  returns always "state": "PENDING"
