### ISSUE TITLE
Access to results when using api/task/async-apply/xxx

### ISSUE THREAD

**Issue by nocrosstalk** [mher/flower#471]
Is there an alternative way to get Celery results when starting jobs using async-apply? Alternative to api/task/info and api/task/result?

**Comment by nocrosstalk** [comment]
To be clear, when I use api/apply it works as expected and I get the full results back.

**Comment by mher** [comment]
`/api/task/result` should return the result if the backend is properly configured. The implementation is pretty straightforward (see https://github.com/mher/flower/blob/master/flower/api/tasks.py#L274).

`/api/task/info` returns task info from events. It doesn't query the backend (see https://github.com/mher/flower/blob/master/flower/api/tasks.py#L493)

**Comment by nocrosstalk** [comment]
I saw the code, I saw both functions work differently. Celery does seem to use the backend correctly. Doe I need specific configuration for Flower with regard to the backend? I tried the memcahed backend. didn't work either.

**Comment by mher** [comment]
Flower needs the same config as celery. You can pass celery app object with `-A` option

**Comment by nocrosstalk** [comment]
Bizar, that's what I do... Will check Monday again.
