### ISSUE TITLE
dashboard can't see num of  Processed	Failed	Succeeded	Retried. Tasks is empty

### ISSUE THREAD

**Issue by likaiguo** [mher/flower#474]
[W 150922 10:23:28 control:44] 'stats' inspect method failed
[W 150922 10:23:28 control:44] 'active_queues' inspect method failed
[W 150922 10:23:28 control:44] 'registered' inspect method failed
[W 150922 10:23:28 control:44] 'scheduled' inspect method failed
[W 150922 10:23:28 control:44] 'active' inspect method failed
[W 150922 10:23:28 control:44] 'reserved' inspect method failed
[W 150922 10:23:28 control:44] 'revoked' inspect method failed
[W 150922 10:23:28 control:44] 'conf' inspect method failed

**Comment by mher** [comment]
This means workers don't reply to inspect requests. Try to increase the inspect timeout with `--inspect_timeout` option. Additionally, you can debug workers without flower using `celery inspect` command.
