### ISSUE TITLE
Task times graph not working

### ISSUE THREAD

**Issue by argaen** [mher/flower#477]
Hi,

I have flower and celery working with Django all in the same machine. The other graphs from the monitor section seem to work fine but the task times isn't showing anything. 

I've been looking for similar issues but seems everything was related to clock synchronization stuff and I have everything in the same machine. 

From the logs I can see that the queries are being done `GET /monitor/completion-time?lastquery=1443603463` but this always returns `{"Execution time": 0, "Time in a queue": 0}`. From the celery log I know that the execution time for the tasks is around 1.5 secs each.

Any guidance/suggestions?

**Comment by minhoryang** [comment]
+1 `flower==0.9.0`

**Comment by melvin15may** [comment]
+1

**Comment by charleshan** [comment]
+1

**Comment by mher** [comment]
Monitor tab is deprecated. Use Prometheus instead.
