### ISSUE TITLE
Using flower as micro service

### ISSUE THREAD

**Issue by mwaaas** [mher/flower#486]
Am using this docker container mwaaas/flower_0.8.3 (https://hub.docker.com/r/mwaaas/flower_0.8.3/)  to monitor my celery. Every thing is working fine I can view the queues and workers but I can't stop the workers from the flower dashboard. I have already added CELERYD_POOL_RESTARTS = True in celery flower

**Comment by mher** [comment]
Have you checked the stderr? There should be error messages there.

**Comment by mher** [comment]
No reply. Closing
