### ISSUE TITLE
What license is Flower?

### ISSUE THREAD

**Issue by masterrex** [mher/flower#490]
Currently the GitHub page nor license file explicitly states which of the major FOSS license types the Flower project is. According to the [ pypi page ]( https://pypi.python.org/pypi/flower ) Flower has a BSD license. Looks like it's also on the [ rtd page ]( http://flower.readthedocs.org/en/latest/ ). Could the license file and GitHub page use the same explicit statement for the poor souls who have to go through approval processes for FOSS?

**Comment by mher** [comment]
Fixed, thanks!
