### ISSUE TITLE
Feature Request: ability to dynamically configure periodic task by flower web.

### ISSUE THREAD

**Issue by garyelephant** [mher/flower#496]
As far as I know, we have to hard code the periodic task, although its configuration syntax is as easy as crontab, can we configure these tasks in flower web, which makes it much easier.

**Comment by km-pg** [comment]
If you are already using or don't mind using Django, there's a way to do this in the Django admin with django-celery (or django-celery-beat for Celery 4.0)
https://github.com/celery/django-celery
https://github.com/celery/django-celery-beat

**Comment by mher** [comment]
There are no plans to work on this feature at the moment until someone decides to contribute to the project.
