### ISSUE TITLE
github auth does not work on python 3 

### ISSUE THREAD

**Issue by syphar** [mher/flower#498]
https://github.com/mher/flower/blob/5bd860e6fa20a80a7ca074d3951fe70d2f2d03d3/flower/views/auth.py#L80

the `urllib` module changed in python 3

**Comment by syphar** [comment]
what's the proposed solution here? I'm happy to provide a PR if it helps. 

Use `six`? `try`/`catch ImportError` ?

**Comment by mher** [comment]
@syphar yes, try/catch will work. See https://github.com/mher/flower/blob/master/flower/utils/broker.py#L14

**Comment by mher** [comment]
Fixed thanks!
