### ISSUE TITLE
python2.6 start flower error

### ISSUE THREAD

**Issue by callnothing** [mher/flower#501]
File "/usr/lib/python2.6/site-packages/flower-0.9.0-py2.6.egg/flower/command.py", line 64, in run_from_argv
    logging.getLogger("tornado.access").addHandler(logging.NullHandler())
AttributeError: 'module' object has no attribute 'NullHandler'

**Comment by callnothing** [comment]
my question,my solution,copy my code,and fix the command.py file in the error place
```
null_file  = logging.FileHandler("/dev/null","a")
null_file.setLevel(logging.ERROR)
# logging.getLogger("tornado.access").addHandler(logging.NullHandler())
logging.getLogger("tornado.access").addHandler(null_file)
logging.getLogger("tornado.access").propagate = False
```

**Comment by mher** [comment]
Fixed, thanks!
