### ISSUE TITLE
'stats' inspect method failed

### ISSUE THREAD

**Issue by hero007asd** [mher/flower#503]
flower: 0.8.3
celery: 3.1.17

When I start 
>"celery flower -A ttcelery --broker=redis://localhost:6379/0" , 

Warning appear:
>"[W 151223 16:24:57 control:44] 'stats' inspect method failed"
[W 151223 16:24:57 control:44] 'active_queues' inspect method failed
[W 151223 16:24:57 control:44] 'registered' inspect method failed
[W 151223 16:24:57 control:44] 'scheduled' inspect method failed
[W 151223 16:24:57 control:44] 'active' inspect method failed
[W 151223 16:24:57 control:44] 'reserved' inspect method failed
[W 151223 16:24:57 control:44] 'revoked' inspect method failed
[W 151223 16:24:57 control:44] 'conf' inspect method failed

And open http://localhost:5555, all tabs is empty

**Comment by mher** [comment]
It means flower failed to inspect workers. You can use `celery inspect` command to debug your workers.

**Comment by Bassel2387** [comment]
how do you start your workers?
Try to give them unique names: 
`celery -A myapp worker -n myworker`

**Comment by kep-w** [comment]
I had the same problem with you. then i find running both flower and the worker together is wrong. 
Flower does not process tasks. You must run both, then Flower can be used as a monitoring tool.
Run celery in a shell, and then open another shell and run flower!

**Comment by sys-temd** [comment]
@kep-w I'm also facing this issue. I have set up Celery executor in airflow along with flower to monitor workers. Everything is running in docker. Flower and the worker start in docker at the same time. What you are saying is that first I should start Celery and once it is up and running then only I should start Flower?

**Comment by alucard001** [comment]
To people who come from Google (like me) and research on this problem: @kep-w is right, you need to run both.

What "run both" means is this:

Run: `/usr/local/bin/celery --app task.celery worker &`
Run `/usr/local/bin/celery  --app task.celery flower --port=5555`

Notice the `&` at the end of first command: I send the worker process to background.  I think you can do that for `flower` also.

Then when you access <domain>:5555, you would see flower dashboard, and not seeing those "Inspect failed" error
