### ISSUE TITLE
Error in setup.py

### ISSUE THREAD

**Issue by paperBraun** [mher/flower#511]
Building a Python package from master branch throws:
`error: can't copy 'flower/static/css/images': doesn't exist or not a regular file`

Your `setup.py` needs modification. Please update line 65 to something like:
`package_data={'flower': ['templates/*', 'static/**/*', 'static/*.*', 'static/css/images/*.*']},`

**Comment by wklken** [comment]
+1, I think you should make a pr for that. @paperBraun

**Comment by wklken** [comment]
The right config is

```
    package_data={'flower': ['templates/*', 'static/css/images/*.*', 'static/**/*', 'static/*.*']},
    exclude_package_data={'flower': ['static/css/images'], },
```

**Comment by paperBraun** [comment]
What is 'exclude_package_data={'flower': ['static/css/images'], },' meant to do? @wklken 
Why would you exclude a dir that you include files from?

**Comment by wklken** [comment]
when I run 
```
python setup.py install
```
got
```
doesn't exist or not a regular file
```

I not so familar with `setup.py` rules, I use you change but the error is still there.
I think 'static/css/images' is a dir, so I just have a try.

**Comment by tboquet** [comment]
Hello, I still have the same error message using `pip install https://github.com/mher/flower/zipball/master`. I submitted a PR (#517)to add the missing line.

**Comment by mher** [comment]
This happened because of bug in distutils https://bugs.python.org/issue19286. I've pushed a simple fix.

**Comment by tboquet** [comment]
Yep much cleaner, Tx!
