### ISSUE TITLE
On Ubuntu installing Flower Package through PIP breaks SSL in Requests Library

### ISSUE THREAD

**Issue by dereklitzfpx** [mher/flower#518]
Hi guys, sorry for the weird bug, but I just experienced this on two versions of Ubuntu. As soon as I use pip to install flower, requests can no longer validate SSL certificates. I'm assuming it breaks across python, but I did not test. Seems like a serious issue if you can reproduce.

I was using the following to validate, I hope the URL doesn't matter:

python -c "import requests; requests.get('https://api.mailgun.net');"

Output of lsb_release -a:

Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.4 LTS
Release:	12.04
Codename:	precise

Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

Oh and the final line of the stack trace just so your sure you're reproducing the same issue...

requests.exceptions.SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

**Comment by vinayinvicible** [comment]
flower has a dependency on tornado which has a dependency on ``certifi``.

requests package tries to import ``certifi`` and if it fails it uses predefined ssl certificates else it uses ``certifi``.

there is no version specification in tornado setup, so it install the latest ``certifi`` which is know to cause these kind of certification issues. (which I have faced recently)

install ``certifi==2015.04.28`` version and everything should be normal.

**Comment by dereklitzfpx** [comment]
@vinayinvicible Thanks much for the quick explanation!

**Comment by mher** [comment]
thanks @vinayinvicible
