### ISSUE TITLE
celery-flower bug

### ISSUE THREAD

**Issue by strongant** [mher/flower#529]
flower   -> flower:0.8.4 tornado:4.2 babel:2.2.0
software -> celery:3.1.20 (Cipater) kombu:3.0.33 py:2.7.6
            billiard:3.3.0.22 redis:2.10.3
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://:**@180.153.57.30//1

JSON_AS_ASCII: True
ES_PORT: '9200'
CELERY_ACCEPT_CONTENT: ['json']
CELERY_DEFAULT_ROUTING_KEY: '********'
LOGGER_DIR: '/home/achieve/gslz/logs'
SCARPING_JS_PATH: '/home/achieve/gslz/phantomjs/fetch.js'
SCARPING_JS_DIR_PATH: '/home/achieve/gslz/phantomjs'
CELERY_IGNORE_RESULT: True
CELERY_DEFAULT_QUEUE: 'celery'
LOGGER_NAME: 'app'
CELERY_TIMEZONE: 'Asia/Shanghai'
SECRET_KEY: '********'
BROKER_URL: 'redis://:********@180.153.57.30:6379//0'
CELERY_RESULT_SERIALIZER: 'json'
CELERY_DEFAULT_EXCHANGE_TYPE: 'direct'
CELERY_DISABLE_RATE_LIMITS: True
SERVER_NAME: None
PREFERRED_URL_SCHEME: 'http'
LZ_RESULT_DIR_PATH: '/home/achieve/gslz/result'
TESTING: False
SMTP_SERVER: 'smtp.163.com'
CELERY_TASK_SERIALIZER: 'json'
SESSION_COOKIE_PATH: None
CELERY_DEFAULT_EXCHANGE: 'celery'
USE_X_SENDFILE: False
CELERY_ACKS_LATE: True
LOGGER_PATH: '/home/achieve/gslz/logs/agent.log'
SESSION_COOKIE_SECURE: False
MAIL_NOTICE: '\xe6\x82\xa8\xe5\xa5\xbd\xef\xbc\x8c\xe6\x82\xa8\xe6\x8f\x90\xe4\xba\xa4\xe7\x9a\x84\xe4\xbb\xbb\xe5\x8a\xa1\xe5\xb7\xb2\xe7\xbb\x8f\xe6\xa3\x80\xe6\x9f\xa5\xe5\xae\x8c\xe6\xaf\x95\xef\xbc\x8c\xe8\xaf\xb7\xe6\xb3\xa8\xe6\x84\x8f\xe6\x9f\xa5\xe6\x94\xb6\xe6\x9c\xac\xe6\xac\xa1\xe4\xbb\xbb\xe5\x8a\xa1\xe6\xa3\x80\xe6\x9f\xa5\xe7\xbb\x93\xe6\x9e\x9c.\xe6\x9c\xac\xe6\xac\xa1\xe4\xbb\xbb\xe5\x8a\xa1\xe7\xbc\x96\xe5\x8f\xb7\xe4\xb8\xba:{},\xe4\xbb\xbb\xe5\x8a\xa1\xe7\xbb\x93\xe6\x9e\x9c\xe7\xbc\x96\xe5\x8f\xb7\xe4\xb8\xba:{},\xe5\x85\xb1\xe4\xba\xa7\xe7\x94\x9f{}\xe4\xb8\xaa\xe5\x8c\x85\xe6\x96\x87\xe4\xbb\xb6,\xe5\x8c\x85\xe7\xbc\x96\xe5\x8f\xb7\xe5\x88\x86\xe5\x88\xab\xe4\xb8\xba:{}.'
SESSION_COOKIE_DOMAIN: None
SEND_EMAIL_PASSWORD: '********'
SESSION_COOKIE_NAME: 'session'
EMAIL_PORT: 25
DEBUG: False
CELERY_RESULT_BACKEND: 'redis://:********@180.153.57.30//1'
APPLICATION_ROOT: None
MAX_CONTENT_LENGTH: None
SESSION_COOKIE_HTTPONLY: True
JSONIFY_PRETTYPRINT_REGULAR: True
MAIL_SUBJECT: '\xe6\x9d\xa5\xe8\x87\xaa\xe4\xb8\x8a\xe6\xb5\xb7\xe6\xb5\xa6\xe4\xb8\x9c\xe8\xbd\xaf\xe4\xbb\xb6\xe5\x9b\xad\xe4\xbf\xa1\xe6\x81\xaf\xe6\x8a\x80\xe6\x9c\xaf\xe5\xb7\xa5\xe5\x95\x86\xe5\xb7\xa1\xe6\xa3\x80\xe5\xb9\xb3\xe5\x8f\xb0'
PERMANENT_SESSION_LIFETIME: datetime.timedelta(31)
PROPAGATE_EXCEPTIONS: None
TRAP_BAD_REQUEST_ERRORS: False
SEND_EMAIL: '18215361994@163.com'
JSON_SORT_KEYS: '********'
TRAP_HTTP_EXCEPTIONS: False
PHANTOMJS_PATH: '/home/devbwh/phantomjs/bin/phantomjs'
SEND_FILE_MAX_AGE_DEFAULT: 43200
PRESERVE_CONTEXT_ON_EXCEPTION: None
ES_HOST: '0.0.0.0'

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1415, in _execute
    result = yield result
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/flower/views/broker.py", line 39, in get
    queues = yield broker.queues(sorted(queue_names))
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 215, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flower/utils/broker.py", line 136, in queues
    'messages': sum([self.redis.llen(x) for x in priority_names])
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 1202, in llen
    return self.execute_command('LLEN', name)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 565, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 577, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 574, in read_response
    raise response
ResponseError: NOAUTH Authentication required.

**Comment by mher** [comment]
Fixed, thanks!
