### ISSUE TITLE
Feature request: Tasks to be updated via Websockets

### ISSUE THREAD

**Issue by AndreLobato** [mher/flower#543]
When monitoring is needed to keep hitting refresh to see new info about tasks in the Tasks list, I wonder if have plans to add automatic update pushed via Websockets. I had implement this in the past in a fork of version 0.7.3, using the events API, but one of the problems I had was the fact we have 1 address for each task-state, that means I had to connect several clients instances, one for each state. 

Would worth to work in a PR for that?

**Comment by mher** [comment]
Feel free to send a pull request

**Comment by mher** [comment]
I'm not sure using web sockets is the best solution. I think Datatable's auto update is more desirable.
