### ISSUE TITLE
Cannot make flower use config file

### ISSUE THREAD

**Issue by mehdigmira** [mher/flower#544]
Hey,

I'm finding it extremely hard to set up flower with a flowerconfig.py file.
the file looks like this:
`BROKER_URL = ***
broker_api = ***`
When I run flower with flower --conf=/path/to/config, flower picks up the default amqp://guest:**@localhost:5672// broker url instead of the one in the config file.
I'm sure that flower is running my flowerconfig.py file because I inserted some print statement, and i can see them on the terminal. I'm also sure that my broker_api/broker_url are right because when i run flower using flower --broker=*** --broker_api=*** it does work.

I don't know what i'm doing wrong. I even tried to debug flower/__main.py__ ^^ but i didn't amount to anything.

**Comment by mher** [comment]
`BROKER_URL` can not be configured from the flower config. It is a celery configuration option and should be passed either from the command line or through the Celery application.

**Comment by sshishov** [comment]
But in configuration it is stated that you can configure: [Configuration](http://mher.github.io/flower/config.html)

**Comment by mher** [comment]
It is fixed in the latest version http://flower.readthedocs.io/en/latest/config.html

**Comment by sshishov** [comment]
I cannot specify broker_url through environment variable neither configuration file. Only works using as script parameters. And only works if the parameter is `--broker` and not `--broker_api` as stated in help message. Thanks.
