### ISSUE TITLE
'Unknown worker' on clicking worker name in dashboard

### ISSUE THREAD

**Issue by professorDante** [mher/flower#546]
Just upgraded to flower 0.8.4 via pip. On clicking the worker name in the dashboard, you get:

Unknown worker 'celery@worker4.xxx.com'

**Comment by mher** [comment]
Updating workers using the `Refresh` button on the dashboard page should solve the problem.

Flower gets the list of workers on startup. If a worker is launched after the flower, the list of workers should be updated explicitly.

**Comment by victorpantoja** [comment]
I know this issue is closed but I'm having this same issue with flower 0.9.2 and python 3.6.5.

This refresh button doesn't exist anymore so I'm passing ?refresh=True.

I'm starting flower after all workers.

**Comment by stojan-jovic** [comment]
@victorpantoja 
Pretty late answer, but for those who googling: **Refresh** button is on the top of _Dashboard_ page under _ComboBox_ which shows **Shut Down** by default!

**Comment by victorpantoja** [comment]
Not on dashboard but on worker page itself. However, this page might not be accessible the first time, that is, after starting flower.

**Comment by stojan-jovic** [comment]
Yeah, on the older versions it's _Workers_ page, I was talking about 0.9.x versions (sorry for the confusion).

**Comment by 363568233** [comment]
Sometimes will appear this problem, I don't know the reason. There is not Refresh button on Dashboard page   0.9.3 version.

**Comment by Bi0max** [comment]
I have the same problem on the latest Docker version 0.9.7. Actually I also checked 0.9.5/4/3 Docker versions as well. Everywhere I get the "Unknown worker" error. ?refresh=True and there is no Refresh button anymore.
Also, I get the following warning in the log:

```
flower       | [I 210205 15:32:44 mixins:229] Connected to redis://redis:6379/0
flower       | [W 210205 15:32:45 inspector:42] Inspect method reserved failed
flower       | [W 210205 15:32:45 inspector:42] Inspect method registered failed
flower       | [W 210205 15:32:45 inspector:42] Inspect method active_queues failed
flower       | [W 210205 15:32:45 inspector:42] Inspect method conf failed
flower       | [W 210205 15:32:45 inspector:42] Inspect method stats failed
flower       | [W 210205 15:32:45 inspector:42] Inspect method revoked failed
flower       | [W 210205 15:32:45 inspector:42] Inspect method active failed
flower       | [W 210205 15:32:45 inspector:42] Inspect method scheduled failed
```

**Comment by samozturk** [comment]
Work around using link and query string didn't work for me. I have the same problem and identical logs output.

**Comment by Praneethvvs** [comment]
I still see this error, I am running redis and flower in docker-compose and starting the celery worker manually on the host machine. Does this setup have anything to do with "Unknown worker 'celery@HYDDSE7MJ77X3". In flower I see the queue size, tasks being processed etc but not the worker information
