### ISSUE TITLE
[feature] config address examples in docs

### ISSUE THREAD

**Issue by professorDante** [mher/flower#547]
I cannot get the --address config to be accepted in my supervisor file. No matter what I try, I get a FATAL from flower. Trying to run it in a PRD environment by giving it its own url.

So if you map www.example.com/flower to the flower app, and set this in config:

[program:flower]
command={{ PYTHON }} {{ PROJECT_DIR }}/manage.py celery flower --port={my port} --basic_auth={auth stuff} --address=http://www.example.com/flower

It dies. Running 0.8.4. Can we have some examples on how to configure?

**Comment by mher** [comment]
`--address` option is for running the flower on a specific ip address. For your use case `--url-prefix` option should be used.

http://flower.readthedocs.org/en/latest/config.html#url-prefix

**Comment by mher** [comment]
Please not that `--url-prefix` is available in the master version not `0.8.4`
