### ISSUE TITLE
support max_tasks count for failed events

### ISSUE THREAD

**Issue by cneberg** [mher/flower#550]
Very few of my events fail, but when they do I want to be able to look them up.   But that requires me to save all tasks, and I'm running out of memory and flower is crashing.

**Comment by trifle** [comment]
I upvoted this because it should be a simple fix.
But to be honest, most use cases would probably be better off using a dedicated error handling solution such as sentry.

**Comment by mher** [comment]
There are no plans to work on this feature at the moment until someone decides to contribute to the project.
