### ISSUE TITLE
Flower fails to start-  KeyError: service_port

### ISSUE THREAD

**Issue by ani82** [mher/flower#557]
Maybe this issue is as well related to dependencies, e.g. Tornado. However, being not involved in the development, I cannot detail on the cause:

`Traceback (most recent call last):
  File "/usr/local/bin/flower", line 9, in <module>
    load_entry_point('flower==0.9.0', 'console_scripts', 'flower')()
  File "/usr/local/lib/python2.7/dist-packages/flower/__main__.py", line 11, in main
    flower.execute_from_commandline()
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/flower/command.py", line 59, in handle_argv
    return self.run_from_argv(prog_name, argv)
  File "/usr/local/lib/python2.7/dist-packages/flower/command.py", line 36, in run_from_argv
    self.apply_env_options()
  File "/usr/local/lib/python2.7/dist-packages/flower/command.py", line 68, in apply_env_options
    option = options._options[name]
KeyError: 'service_port'`

Under Debian Jessie with 
flower   -> flower:0.9.0 tornado:4.2 babel:2.2.0
software -> celery:3.1.23 (Cipater) kombu:3.0.35 py:2.7.9
            billiard:3.3.0.23 py-amqp:1.4.9
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.default.Loader
settings -> transport:amqp results:disabled

**Comment by ani82** [comment]
By several trials I found out that the issue does not exist locally. It is present on Kubernetes, whereby Kubernetes creates and distributes env. variables. 

One of my services was called flower-service, therefore a env. variable FLOWER_SERVICE_PORT was created, which leads to a crash during startup of flower itself. 

Maybe you harden the code by only allowing parameters to be parsed which are in a list of allowed ones? Also a crash with "unknown parameter FOO" would help, I guess. 
A simple crash with "KeyError" takes a lot of time to debug.

**Comment by mher** [comment]
Fixed, thanks!

**Comment by ani82** [comment]
Great! Thank you!
