### ISSUE TITLE
Revoked tasks counting as active tasks on the dashboard page

### ISSUE THREAD

**Issue by Thhhza** [mher/flower#558]
Flower 0.9.0

There seems to be a couple of issues here when you have revoked tasks:
1. The active count for individual workers on the dashboard page always counts revoked tasks as active
2. The global count of active tasks on the top of the dashboard page is correct upon first loading the page but once the dashboard is updated it counts revoked tasks as active tasks. This would be due to the following line in dashboard_update() in dashboard.py:
active = started - succeeded - failed - retried

While fixing this, perhaps the number of revoked tasks should be added to the dashboard page since the rest of the status types have been split up (i.e. active, processed, failed, succeeded, retried).

**Comment by melvin15may** [comment]
+1
This issue is also there in Reserved Tasks table.
Even after revoking a task, it shows up in the Reserved Task table in individual workers

**Comment by mher** [comment]
Thanks for opening the issue. Can you send a pull request?

**Comment by mher** [comment]
Please try the master version. This issue shouldn't be valid with the refactored dashboard.
