### ISSUE TITLE
Flower only lists queue "celery" and not own configured ones

### ISSUE THREAD

**Issue by ani82** [mher/flower#559]
Dear all,

I had to realize that Flower is not showing additional queues and information from RabbitMQ. It is only displaying the message count from the standard queue "celery". However, there are several more exchanges and queues (with messages in) which should display.

I start Flower from CLI with 
     
      `flower --broker=amqp://${RABBITMQ_DEFAULT_USER:guest}:${RABBITMQ_DEFAULT_PASS:guest}@${RABBITMQ_SERVICE_SERVICE_HOST:localhost}:5672// \
    --broker-api=http://${RABBITMQ_DEFAULT_USER:guest}:${RABBITMQ_DEFAULT_PASS:guest}@${RABBITMQ_SERVICE_SERVICE_HOST:localhost}:15672/api/`

I have checked the environment variables with $: printenv
and checked the clocks on both RabbitMQ and Flower to be in sync. Moreover, I've checked the RabbitMQ API with my user and obtained all desired information from 
`http://user:pass@rabbit-host/api/queues`

Thus I can barely say why Flower does not want to display the present information.

**Comment by mher** [comment]
Flower uses the default celery queue if it can't get a list of active queues from workers https://github.com/mher/flower/blob/master/flower/views/broker.py#L35-L37

**Comment by ani82** [comment]
Ok, thanks for sharing the code. Wouldn't it be better to get all queues from AMQP? E.g. if you have a system during dev where messages are filled into but you do not want to start a worker at that time.

**Comment by justdan23** [comment]
When you launch "flower" to start up, pass the -Q parameter with the queue you want it to watch.  I haven't figured out yet how to define multiples, but this does work for one custom queue.
