### ISSUE TITLE
No selection boxes in the dashboard

### ISSUE THREAD

**Issue by shrinidhimi** [mher/flower#562]
![selection_001](https://cloud.githubusercontent.com/assets/17136622/14307535/7d95051c-fbed-11e5-8fb9-d6ce3c073c5a.png)

Please help. Its a work stopping issue since we need to monitor and control the celery workers we have asap .

**Comment by mher** [comment]
Clicking on a worker row selects it. No need for a check box.

**Comment by shrinidhimi** [comment]
thanks for that info . will take a look .
