### ISSUE TITLE
checkbox missing to shutdown worker

### ISSUE THREAD

**Issue by sma202** [mher/flower#564]
Hi, I upgrade to 0.9.1 and now the flower gui doesnt have the shutdown checkbox for workers.  How do I shut the workers down, when I click on shutdown, it says select a worker, but there is no option to select a worker?

please help

**Comment by sma202** [comment]
This is what I am using (on chrome):

flower --basic_auth=xxx:xxx --inspect --address=xxx --port=5555 --broker=amqp://admin:admin@xxx:5672//

**Comment by mher** [comment]
Clicking on a worker row selects a worker

**Comment by sma202** [comment]
It's a bit confusing clicking on the row outside of the hyperlink, can't really tell if its selected.

I have a 150 workers across 5 servers, is there anyway to shut them down en masse like the previous version?

**Comment by john2x** [comment]
I agree that the new UI makes selecting workers difficult. The table rows are "zebra" colored green/white, and a selected row is highlighted green. This makes the rows which are already green unclear if they are selected or not.

**Comment by sma202** [comment]
Can we please add the "en masse" option via checkbox or "shut down all" back?

**Comment by john2x** [comment]
Example: I have 1 row selected in this screenshot, but can't tell which. 

<img width="446" alt="celery_flower" src="https://cloud.githubusercontent.com/assets/332885/14872585/4014adb6-0d20-11e6-951e-9a343a9648c5.png">

**Comment by mher** [comment]
Shutdown group button is moved to worker page. For bulk shutdown you can use `celery control shutdown` command.
