### ISSUE TITLE
when the queue is large   more than 4k queues  

### ISSUE THREAD

**Issue by stayliv3** [mher/flower#567]
the link  http://127.0.0.1:5555/broker  would maybe a long time to response or time out .

use rabbitmq as broker.

the log is 

[E 160414 21:25:17 broker:77] RabbitMQ management API call failed: HTTP 599: Timeout
[E 160414 21:25:17 broker:78] Make sure RabbitMQ Management Plugin is enabled (rabbitmq-plugins enable rabbitmq_management)
[E 160414 21:25:29 broker:77] RabbitMQ management API call failed: HTTP 599: Timeout

my rabbitmq management api is ok.and the other link just like http://127.0.0.1:5555/dashboard works fine.

when i first start the rabbitmq.  the link http://127.0.0.1:5555/broker   is fine.after a few time .it would be very slow and timeout.

I use the wireshark to catch the request.It seems like the /api/queue/%2F  response is to large and could not deal with it .

**Comment by mher** [comment]
@stayliv3 is this still an open issue? Have you tried to increase the RabbitMQ Management API timeout?
