### ISSUE TITLE
Monitor Tab not showing tasks

### ISSUE THREAD

**Issue by hassek** [mher/flower#568]
Investigating the issue I found that this is a problem with how flower manages to get time. Here is what I think should be changed:

The generation of the _lastquery_ timestamp is coming from javascript, that means that if the user computer has a problem on his clock he will not be able to see tasks coming and others will (making the bug hunting a pain). This could be avoided by using python's **time** library and adding a _padding_ to that time instead which will use the server time. We could also add a url query like _lastquery_ to modify the padding if required.

Here is a code example:

```
time_padding = self.get_argument('padding', type=float)
timestamp = time.time() - padding # let's say padding is 60 seconds
state = self.application.events.state

data = defaultdict(int)
for _, task in state.itertasks():
    if (timestamp < task.timestamp and task.state == states.SUCCESS):
        data[task.worker.hostname] += 1
```

Also, to be honest, I don't quite understand why these timestamp comparisons on the monitor view even exists, for what I could see, the tasks are sent to the monitor just once, even if the times are not exactly matching, shouldn't we just show them?

I understand this may be the case with RabbitMQ but not with other brokers and that would make sense. I think a padding to the time would make things a lot easier to handle though.

These are my installed app versions:
flower==0.9.1
celery==3.1.23

**Comment by gmixo** [comment]
Have the same issue and I think that
```python
if (timestamp < task.timestamp and task.state == states.SUCCESS):
```
should be
```python
if (timestamp > task.timestamp and task.state == states.SUCCESS):
```
since the _timestamp_ is current time and _task.timestamp_ is task execution time and task currently should be finished(if they state is SUCCESS)
or as @hassek said totaly remove the timestamp comparison

**Comment by Datta1993** [comment]
is this issue fixed? I'm also having the same problem.

**Comment by Datta1993** [comment]
This fixed the issue. 
Why is it not pushed to the main branch?

**Comment by johnarnold** [comment]
The only way it would make sense is if you only wanted to see tasks which complete after you open the monitor window (instead of historical).   That doesn't make much sense to me, I'd rather see all the historical possible.

**Comment by mher** [comment]
Monitor tab is deprecated. Use Prometheus instead.
