### ISSUE TITLE
Memory leak when starting flower with supervisord

### ISSUE THREAD

**Issue by hassek** [mher/flower#57]
so I just added flower to my production server and the server after around 5 minutes gets totally out of memory, here is a nice graph:

![Server2](https://f.cloud.github.com/assets/778410/219089/88e9dd9a-851f-11e2-89cb-6a9a6a02fac9.png)

As soon as I stopped flower all the memory came back (as seen on the image)

I'll try tomorrow to give it a deeper look thou.

My supervisor command would be this one:

```
[program:celery_flower]
command=/home/web/.virtualenvs/web/bin/python /home/web/manage.py celery flower  --url_prefix=celery --auth=EMAILS
stdout_logfile=/var/log/celery_flower.log 
autostart=false
user=web
killasgroup=true
```

and my celery setup:

```
software -> celery:3.0.13 (Chiastic Slide) kombu:2.5.4 py:2.6.5
        billiard:2.7.3.19 py-amqp:N/A
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> djcelery.loaders.DjangoLoader
settings -> transport:amqp results:mongodb
```

**Comment by tmacjx** [comment]
I have set max_tasks to 100，but it's still have memory leak.If used 6G memory after change the conf about 5 months!
I have read some source code of flower and can't figure why this happend.

kombu.utils.functional.LRUCache is what manage to store the state of works and tasks.
It's will check the limit when you set max_tasks or max_works.Nothing look wrong
Anything help other??
