### ISSUE TITLE
modify task table columns

### ISSUE THREAD

**Issue by nipunarora** [mher/flower#570]
I would like to modify the task table to show some information regarding the task. For instance I would like to show a column with description of the task, a custom ID value, and a name. All of these are passed as arguments to the celery task. I would like to show them in seperate named columns. How can I do this in the task tab?

**Comment by mher** [comment]
Flower doesn't support custom columns. All columns are listed https://flower.readthedocs.org/en/latest/config.html#tasks-columns. Some columns are hidden by default.

**Comment by nipunarora** [comment]
Is there a default flower DB from which I can query and show custom columns the way I want. Alternatively, where can the flask code be modified to show these columns?

**Comment by mher** [comment]
flower keeps event db in memory. You can use flower API to query it from external tools.

**Comment by mher** [comment]
http://flower.readthedocs.io/en/latest/config.html#format-task option can be used to modify task info in the `/tasks` page
