### ISSUE TITLE
Chart not showing up

### ISSUE THREAD

**Issue by thenewguy** [mher/flower#573]
Similar to the closed issue https://github.com/mher/flower/issues/324.  I've ran into this while upgrading from 0.7 to 0.9.  The odd part is that the only chart that doesn't work is "Queued tasks".  "Succeeded tasks", "Failed tasks", and "Task times" are turned into charts as expected.

<img width="959" alt="queued-tasks-chart-fails" src="https://cloud.githubusercontent.com/assets/77731/15058840/af736b76-12ec-11e6-8764-93a9ffb65cf4.png">

Not sure how to work around or diagnose this problem any further so pointers would be appreciated.  Staging project deployed using docker-compose so I don't think it can be clock drift.  Celery / flower / workers / app are all using django with the same settings file so they should be using the same time zone.

**Comment by rafalmp** [comment]
Same here. Looks like the problem appeared after upgrading amqp from 1.4.9 to 2.0.1

**Comment by imaia** [comment]
Same here. Doesn't even show "broken chart" frame.

**Comment by LyleScott** [comment]
Good catch. I had the same problem. It was fixed by downgrading amqp back to 1.4.x from 2.x

**Comment by mbande** [comment]
same error with redis broker

**Comment by rafalmp** [comment]
Interestingly, clicking a worker link in the dashboard makes the 'Queued tasks' graph appear and display the clicked worker's data, after clicking on all worker links in the dashboard the charts are fully functional until the next restart of flower.

**Comment by adampl** [comment]
It appears this is still the case on 4.1.0, but (luckily) the "solution" discovered by @rafalmp also works.

**Comment by mher** [comment]
Monitor tab is deprecated. Use Prometheus instead.
