### ISSUE TITLE
"Filter Tasks" not appearing. 

### ISSUE THREAD

**Issue by brian-polly** [mher/flower#575]
I recently upgraded from flower 0.8.3 to 0.9.1, and the tasks tab is much less helpful than it used to be. 

What I want is the "filter tasks" block, as shown ![](http://flower.readthedocs.io/en/latest/_images/tasks.png) in the latest flower docs, but what I have instead is a lonely search box that responds to filter syntax, but doesn't give me any way to tell whether no tasks of a certain name have been run or I'm spelling something wrong. 

I can't tell if this is a bug, a runtime flag that I'm leaving off (or accidentally applying) or a configuration setting. I haven't found anything about how to toggle in the docs, so I'm wondering if maybe the way I'm installing no longer works? 

How ought I go about diagnosing this?

**Comment by dhuang** [comment]
Looks like it was replaced intentionally when DataTables was added in 381e01840a42998d8c5d084bc9518e38db166f1c.

**Comment by mher** [comment]
Starting from version 0.9 static task filtering is replaced with DataTables based dynamic filtering.
