### ISSUE TITLE
Dockerization (does flower require the same sources of the worker).

### ISSUE THREAD

**Issue by richburdon** [mher/flower#577]
Flower seems to require the source code for the Celery worker, which if true, makes dockerization non-trivial -- since the sources will need to be in multiple places (and updated in multiple places).

Since it's just a monitor, why is this so? (i.e., can't it retrieve all available information from the broker?)

What's the best practice for using with docker?

**Comment by mher** [comment]
`flower` package depends on `celery` package. It uses Celery event library to consume events from broker.  `pip install flower` installs all required dependencies. No need to install celery manually.
