### ISSUE TITLE
Wrong status logo in dashboard for offline workers

### ISSUE THREAD

**Issue by mvikharev** [mher/flower#578]
There is an issue in 0.9.1. Dashboard shows online logo for worker even it goes offline. It seems like problem in UI as in the second before icons rendering i see False values in Status cells of dead workers and True for alive.

**Comment by AndreLobato** [comment]
I have noticed also that if I stay on the dashbord long enough, after a few seconds, all my workers appears as offline, but I am using a modified version of flower, so could just be on my version.

**Comment by bpereto** [comment]
I have also Flower 0.9.1 and Celery 3.1.9 with amqp backend.

After I started the celery worker it shows up in the flower dashboard, but doesn't change to offline when stopping the worker.
Even with the 'Refresh' Button on the Dashboard the status is not updated.

If you click on the Worker it shows an error 'Unkown Worker'

**Comment by bpereto** [comment]
The Issue was the Apache HTTP Proxy which dont' proxying the WebSocket Request.
Due the implementation of Websockets in Firefox, there must be a WSS Connection, if the frontend is also Secure (SSL). Note that in this case flower must also running with ssl.

This works for me with Apache 2.4.6:
```
# Upgrade normal HTTP to Websocket if needed
RewriteEngine On
RewriteCond %{HTTP:Connection} Upgrade [NC]
RewriteCond %{HTTP:Upgrade} websocket [NC]
RewriteRule /(.*) wss://localhost:5555/$1 [P,L]

# SSL Proxy Request
SSLProxyEngine On
SSLProxyVerify none
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off
SSLProxyCheckPeerExpire off

# origin check in tornado - you get a 403 if not set
Header set Origin "https://localhost:5555"
RequestHeader set Origin "https://localhost:5555"

ProxyRequests off
ProxyPass / https://localhost:5555/
ProxyPassReverse / https://localhost:5555/
```

**Comment by mher** [comment]
Please try the master version. The dashboard doesn't not use web sockets anymore.
