### ISSUE TITLE
Error at /api/task/info/T when T is in state PENDING

### ISSUE THREAD

**Issue by alexmojaki** [mher/flower#585]
When querying a task that is pending, the following error occurs:

```
File "/usr/local/lib/python2.7/site-packages/flower/api/tasks.py", line 601, in get
    response['worker'] = task.worker.hostname
AttributeError: 'NoneType' object has no attribute 'hostname'
```

which makes sense since pending tasks have no worker. This attribute should only be added if `task.worker is not None`.

**Comment by mher** [comment]
Fixed, thanks!
