### ISSUE TITLE
Why does flower require exactly `tornado==4.2.0`?

### ISSUE THREAD

**Issue by mrmachine** [mher/flower#586]
Instead of `tornado>=4.2.0`? This seems very restrictive. Flower doesn't know what project it will be installed into and what packages might be installed alongside it, and they might require `4.3` (which probably also works with Flower)?

This commit relaxed all the other requirements except for tornado: https://github.com/mher/flower/commit/57e87e184edbd751b6a2ab88a886ba41e2755e0f

**Comment by mher** [comment]
There was a problem with version 4.3. See https://github.com/mher/flower/issues/489 for details.

**Comment by mrmachine** [comment]
So 4.3 is known to be incompatible, but are future versions of tornado also going to be incompatible? If so, Flower's requirements should be `tornado<4.3`. If it's only 4.3 that is incompatible, and future versions are expected to work, it should be `tornado>=4.2,!=4.3.0`? Although if all future versions of tornado are not going to be compatible because of an API change (rather than a bug that will be fixed), perhaps Flower needs an update to be compatible?

**Comment by mher** [comment]
I didn't have a time to implement a solutions which works with both 4.2 and 4.3. The future versions should be compatible with 4.3.

**Comment by mher** [comment]
Feel free to send a patch

**Comment by arjenfvellinga** [comment]
Tornado 4.2.0 is considered vulnerable, so we had to upgrade it in our project. http://www.tornadoweb.org/en/stable/releases/v4.2.1.html . Moreover Tornado 4..4 is already released.

Is it possible to reconsider this issue?

**Comment by alzeih** [comment]
@arjenfvellinga @mher I've submitted a patch for this issue https://github.com/mher/flower/pull/629

**Comment by mher** [comment]
Fixed by #629
