### ISSUE TITLE
Inconsistent start time

### ISSUE THREAD

**Issue by lbolla** [mher/flower#587]
I can see inconsistent start times in the worker view and in the task view.
In the attached files, see task f9677c35-b59a-4785-bec7-298d9fd47b5d, which has a start time of 2016-06-08 12:03:37.326168 UTC in the task page, but 1970-07-03 17:25:27.437767 UTC in the workers page.
![screenshot from 2016-06-08 13 57 55](https://cloud.githubusercontent.com/assets/20991/15895081/3bfa4796-2d81-11e6-92fe-d1cc3ccd144a.png)
![screenshot from 2016-06-08 13 58 13](https://cloud.githubusercontent.com/assets/20991/15895084/3e9e4042-2d81-11e6-8f7e-09f1cde96d3d.png)

**Comment by wsantos** [comment]
I can confirm. Version 0.9.0

**Comment by mher** [comment]
Start time is [removed](https://github.com/mher/flower/commit/3a59fc9b47ab0e5cf6d21f93e6a331c434c81764) from the worker page. It is the monotonic time and is only useful on the same machine. 

See http://stackoverflow.com/questions/20091505/celery-task-with-a-time-start-attribute-in-1970/ for details.
