### ISSUE TITLE
'FLOWER_' prefix for flower config from flowerconfig

### ISSUE THREAD

**Issue by imaia** [mher/flower#589]
Hello folks,
In my django project, I have a python file which holds all my settings and import from nowhere. I'm trying to import it from my flowerconfig.py file because there are a few name collisions. This approach is quite problematic because I have to "hard wire" sys.path to make it work. If flowerconfig had a flower specific approach to configure itself, like only loading properties prefixed with 'FLOWER_', my problem would be solved. What do you guys think?

**Comment by imaia** [comment]
By the way, --conf is not working at all here.

**Comment by jefftriplett** [comment]
`--conf` doesn't work for me either.

**Comment by mher** [comment]
You can easily filter flower options in common config. See https://github.com/mher/flower/blob/master/flower/command.py#L126 for example

**Comment by mher** [comment]
`--conf` option is fixed in the master
