### ISSUE TITLE
--conf argument does not really do anything

### ISSUE THREAD

**Issue by imaia** [mher/flower#590]
Trying out some examples, --conf seems unable to change any params for flower. I tried to pass broker and broker_api and it actually produced no effect. Passing arguments to "celery flower", on the other hand, works just fine. Is anyone facing this kind of problem?

```
broker = 'amq://... something'
broker_api = 'http://... something'
```

**Comment by SilentShanx** [comment]
I am having this issue too. Command line arguments seem to work but reading from a conf file does not.

**Comment by ssmchuckb** [comment]
I too am having this issue

**Comment by mher** [comment]
`broker` option is a special option. It doesn't work with configuration file. The other options work as expected. Please try the master version and reopen the issue if you are still experiencing the problem.
