### ISSUE TITLE
broker_api gotcha

### ISSUE THREAD

**Issue by imaia** [mher/flower#591]
If the broker_api param does not end with "/api/", like when it ends with "/api", well, it breaks horribly, with a message that is quite hard to guess. I would like to suggest that the error message be improved or a workaround be implemented, like, "oh, there is no trailing slash, let's add one, cuz we're are really nice folks!" or something.

**Comment by gtangquri** [comment]
well, to be fair, it shows the format to use [here](http://flower.readthedocs.io/en/latest/config.html#broker-api)

**Comment by mher** [comment]
@gtangquri https://github.com/mher/flower/commit/595beecde8781870f3c6c9a5dc7983fde7b37ca3 should fix https issue
