### ISSUE TITLE
HTML injection via task parameters

### ISSUE THREAD

**Issue by tdero** [mher/flower#594]
During an audit I came across an issue in flower 0.9.1 that allows me to inject HTML into the /tasks webpage with a specially crafted set of parameters to a task in celery. 

In this particular case the following adjustment should fix the issue in flower.js:

```
            }, {
                targets: 3,
                data: 'args',
                visible: isColumnVisible('args'),
                render: $.fn.dataTable.render.text() /* FIX : prevent args from being rendered as HTML */
            }, {
```

You should probably evaluate if other fields such as "kwargs" and "results" are vulnerable as well.

**Comment by mher** [comment]
Fixed by https://github.com/mher/flower/pull/651
