### ISSUE TITLE
task not saved to database when running inside a docker 

### ISSUE THREAD

**Issue by ywx649999311** [mher/flower#596]
I tried to run the flower insider a docker container, but the tasks are not properly saved to the database file I specified on the mounted volume. However, there is no problem at all when running flower locally. 

my shell command:
flower -A dtasks --port=5555 --db=/path/to/database/file --persistent=True

Actually, there are some tasks were saved, but only a few. Most of the tasks record were gone.

I appreciate any helps.

**Comment by mher** [comment]
This doesn't sound a flower related issue. I'd suggest to debug using local database file inside docker.
