### ISSUE TITLE
celery 4.0 rc3

### ISSUE THREAD

**Issue by mbande** [mher/flower#598]
anyone tried this?
it seems that most of user interface does not work,
e.g. worker is reported offline, task list is not shown at all, ...

**Comment by Cediddi** [comment]
Same here, rc4. My problem is a TypeError, Task is not JSON serializable, which I think would be pretty easy to fix.

**Comment by bkabrda** [comment]
Hi guys, I've run into this issue as well and it seems it has been fixed by https://github.com/celery/celery/pull/3490 (merged now). I've installed celery with this patch included and flower has been working for me great since then.
