### ISSUE TITLE
Cannot use Google Cloud Load-Balancer health checks with Flower 

### ISSUE THREAD

**Issue by admiralobvious** [mher/flower#600]
I use Flower on Google Cloud's [Container Engine](https://cloud.google.com/container-engine/) with their HTTP L7 load-balancer but when I turn on Flower's Google authentication, the health checks on / fail because the return code is 302 while the health checks expects a 200.

The Container Engine and its HTTP Load-Balancer are new-ish products so you cannot customize the path and status code it checks on a per service basis at the moment which leaves me with modifying Flower to change the return code to a 200.

I haven't looked extensively at that part of Flower's code but from the top of your head, would that possible?
Also, can you think of a better fix that you would accept as a merge request? My first thought would be to add a new config option, but I don't find that very elegant.

Cheers

**Comment by mher** [comment]
I'd suggest to try hide flower behind some proxy and modify the status code in proxy. Your use case is not general enough to introduce a new config option.

**Comment by acro5piano** [comment]
For someone who use AWS ELB and see this issue, you can set valid status code with ELB health check.

https://stackoverflow.com/a/42832056/4287971
