### ISSUE TITLE
restore  static task filtering

### ISSUE THREAD

**Issue by filipslavik** [mher/flower#601]
Hi,

Based on a comment on #575 it seems that starting from version 0.9, static task filtering has been replaced with DataTables based dynamic filtering. 

I don't know if it is just me, but I believe the new filtering approach is very restrictive and far less usable than the previous implementation based on the tasks filter 'widget'. Perhaps, there is something that I'm missing here, however, with the 0.9.x based data-tables approach I'm unable to do simple and fast filtering like I was used to :
- I was able to see what tasks have been "seen" by celery 
- I was able to select (and filter) by simply choosing something from the available drop list (now I have to type the search term in the search box ?)
- I was able to combine search filters (tasks of type X in state Y which ran on worker Z). I don't see any way to do this right now (is there any hidden UI box ? search box seems to ignore boolean expressions)

Please consider re-adding the static task filtering back to master. We are handling thousand of thousands of celery messages each day and with the current task filtering implementation, we are unable to filter as we were used to :-(

Cheers!
Filip

**Comment by ushuz** [comment]
Downgrade to 0.8.x due to this.

**Comment by tmehlinger** [comment]
Was also forced to downgrade because of this. The dynamic filtering is inferior.

**Comment by luzfcb** [comment]
Same here.

**Comment by jgirdner** [comment]
I'm going to downgrade as well.
