### ISSUE TITLE
How can i intergrate flower into django admin or run flower ad daemon?

### ISSUE THREAD

**Issue by thanhngvpt** [mher/flower#602]
Hi author.
As title i am new to celery and django have a question How can i intergrate flower into django admin or run flower ad daemon?.

Many thanks

**Comment by antonyc** [comment]
the native way is running it as a daemon, and it's fully covered in docs. You just run http://flower.readthedocs.io/en/latest/install.html#usage 
there is no native way of integrating it to django admin.
