### ISSUE TITLE
Offline workers shown as online

### ISSUE THREAD

**Issue by vineet-rh** [mher/flower#603]
Offline workers are appearing to be online on the flower dashboard. 

Interestingly enough if I look at the network responses I see (for 1 of the workers):

```
<tr id="celery%40ip-10-1-40-143">
<td>celery@ip-10-1-40-143</td>
<td>False</td> # <------ False
<td>0</td>
<td>41</td>
<td>1</td>
<td>40</td>
<td>0</td>
<td>0.0, 0.01, 0.05</td>
</tr>
```

However when rendered on the front end, this is shown as online. If I refresh I can see the html say false for that worker - for a fraction of a second before the javascript renders it as online.

**Comment by pg1671** [comment]
+1

**Comment by exister** [comment]
Had the same issue with flower running behind AWS ELB. It was caused by websocket connections not being correctly proxied to flower.

**Comment by msalvadeo** [comment]
i've the bsame issue running celery + flower on windows-8 and Python 2.7

**Comment by tristanguo** [comment]
having the same issue while websocket is ok.
it can update to 'offline', but can't update to 'online' when the worker is back up.

Version 0.9.1

**Comment by mher** [comment]
Please try the master version. Web sockets have been removed from the dashboard.
