### ISSUE TITLE
Ability to remove offline workers

### ISSUE THREAD

**Issue by vineetgoel** [mher/flower#604]
This will be super useful especially when using an Amazon ASG for tweaking the number of workers. 

Currently the dashboard looks too polluted as it shows all the offline workers too.

**Comment by tbindi** [comment]
+1

**Comment by zenvisuals** [comment]
+1

**Comment by kheshav** [comment]
+1

**Comment by clems4ever** [comment]
+1

**Comment by yothinix** [comment]
Seems to be duplicate with #852

**Comment by dejlek** [comment]
The difference is that #852 comes with an implementation...

**Comment by mher** [comment]
https://github.com/mher/flower/pull/852 implements this
