### ISSUE TITLE
Config file when running from outside folder

### ISSUE THREAD

**Issue by someburner** [mher/flower#605]
Saw that some people were having an issue with flowerconfig.py not loading.

I investigated a bit and found that it seems to be due to flower looking in the directory it's run from. This makes sense, but in some cases, due to the way celery projects are organized, you have to run celery/flower from the first directory outside the "app" directory. 

For ex, here's my folder structure:

```
somedirectory/myapp/
---consumer/
---consumer/tasks/
---consumer/tasks/tasks.py
---consumer/worker.py
---celery.py
---celeryconfig.py
---flowerconfig.py
```

When I run celery, I have to run it from the **somedirectory** location like this:

```
celery -A myapp.celery worker -l info
```

So flower must also run from there to register the tasks properly (I think anyways). 
Anywho, quick fix is to just go into `flower/options.py` and change the default to include your folder, like 

```
DEFAULT_CONFIG_FILE = 'myapp/flowerconfig.py'
```

But it would be nice if flower could use the module structure when there's a command like `flower -A myapp.celery` to know to look in the myapp folder

**Comment by mher** [comment]
https://github.com/mher/flower/commit/1610aee5f360145f90aa72c33efe9ec58295fd01 allows to use absolute config file paths
