### ISSUE TITLE
Data not html-escaped.

### ISSUE THREAD

**Issue by account-login** [mher/flower#607]
The 'args' colunm of tasks page can contain arbitary data. If you feed your task with some HTML, you will notice that the HTML was injected into task page. Please escape data correctly.
Thanks.

**Comment by totopsy** [comment]
Can you provide a payload please @account-login ? Thanks

**Comment by account-login** [comment]
Hello @totopsy . Here is code to reproduce this issue:
```python
# task
@celery.task(name='fdsa')
def fdsa(haha):
	return haha
```
```python
# run task
fdsa.apply_async(("this is <b>HTML</b>",))
```

Screenshots:
![flower_issue](https://cloud.githubusercontent.com/assets/9835862/17767678/791da43c-6563-11e6-8ac0-d9dbf01d9983.png)

**Comment by tdero** [comment]
There's an example on how to fix it here : https://github.com/mher/flower/issues/594

Applies to args, kwargs and result
