### ISSUE TITLE
problem when I try to revoke a schedule task(with eta) 

### ISSUE THREAD

**Issue by GitProBo** [mher/flower#608]
when I try to revoke a schedule task(with eta) , 
it's recevied sucessed, but nothing changed when get task detail

`curl -d "" http://redis.daily.vdian.net:5555/api/task/revoke/836fb8cd-d3c2-4cf8-9a3d-0b3af01024cb
{"message": "Revoked '836fb8cd-d3c2-4cf8-9a3d-0b3af01024cb'"}
curl http://redis.daily.vdian.net:5555/api/task/info/836fb8cd-d3c2-4cf8-9a3d-0b3af01024cb
{"task-id": "836fb8cd-d3c2-4cf8-9a3d-0b3af01024cb", "result": null, "clock": 106, "exchange": null, "routing_key": null, "failed": null, "state": "RECEIVED", "client": null, "kwargs": "{}", "sent": null, "args": "('switch_sentinel', u'{\"host\":\"10.1.100.220\",\"port\":\"6380\"}')", "retries": 0, "started": null, "timestamp": 1470892689.174498, "expires": null, "worker": "celery@vm-idc01-testzone-101100198", "revoked": null, "received": 1470892689.174498, "exception": null, "name": "app.views.long_task", "succeeded": null, "traceback": null, "eta": "2016-08-12T13:20:00+08:00", "retried": null, "runtime": null}`

**Comment by TheBlusky** [comment]
Same issue here (but not using Flower).
did you have any success resolving it ?
