### ISSUE TITLE
ignore_result 

### ISSUE THREAD

**Issue by bohea** [mher/flower#609]
I have a celery task which set  ignore_result = True
But flower still trace this task's state and show results
@task_app.task(ignore_result=True)
def some_task():
      do_something()

**Comment by bohea** [comment]
can flower ignore the result of a task which ignore_result in celery

**Comment by nicholasserra** [comment]
Also curious about the relationship between flower's reporting and the tasks `ignore_result` value.

**Comment by mher** [comment]
flower uses celery events to monitor tasks. celery events include task results regardless off `ignore_result`

**Comment by Ridder90** [comment]
Is there another way to ignore the task in flower?
