### ISSUE TITLE
No queues info in Broker tab

### ISSUE THREAD

**Issue by kkzxak47** [mher/flower#610]
Hi, I'm using celery with Django, redis as broker. But I'm unable to get queues info in flower.
Searched this problem for two days but got no solution. Please help.

In "Dashboard"/"Tasks" tab, everything seems fine, the numbers are updating in realtime.
![screenshot from 2016-08-25 10-18-52](https://cloud.githubusercontent.com/assets/2363326/17954412/7c350832-6aad-11e6-8c5c-c08d4defa7e6.png)

But in "Broker" tab, the message number of queues are all 0 and one queue is missing. I've checked redis, the usage shows it is impossible that every queue is empty.
![screenshot from 2016-08-25 10-06-25](https://cloud.githubusercontent.com/assets/2363326/17954374/3f41ac0a-6aad-11e6-9866-fd41f1570e20.png)

The "Queued tasks" graph in the "Monitor" tab is always empty while the rest of the four graphs are working.
![screenshot from 2016-08-25 10-21-18](https://cloud.githubusercontent.com/assets/2363326/17954461/d251dce0-6aad-11e6-8d2f-dfd67fad6fa0.png)

I'm running Django 1.8.9, Celery 3.1.20, django-celery 3.1.17, and flower 0.9.1 on Ubuntu 12.04.5 LTS.
Tried to start flower with "python manage.py celery -A proj flower --broker=redis://xxxx:6379", "celery -A proj flower --broker=... --broker_api=..." and several other variations.

**Comment by jefftriplett** [comment]
This issue bit me too, but I'm not sure if the project maintainers have a preference for how to solve it.

From what I can tell, Flower internally supports multiple queues, but there's no way to tell Flower to monitor more than one queue at a time with redis. The default is `CELERY_DEFAULT_QUEUE` which can bee seen [here](https://github.com/mher/flower/blob/master/flower/api/tasks.py#L382) and [here](https://github.com/mher/flower/blob/master/flower/views/broker.py#L37). 

If these sections would support looking for Celery's `CELERY_QUEUES` variable and then fall back to Celery's `CELERY_DEFAULT_QUEUE` setting then that would give us the names we need to check all of the queues.

As a temporary fix, I overrode https://github.com/mher/flower/blob/master/flower/api/control.py#L66 to return my queue names for now.

I'm happy to contribute a patch with a bit of guidance but maybe this information will help someone else out too.

**Comment by mher** [comment]
@jefftriplett thanks for your contributions. Can you try https://github.com/mher/flower/commit/2436ae77a0e1ff770b51f9eaf121b85aad4873fe?

**Comment by trianglesis** [comment]
Same here:
- change nothing, works fine for few last months, now didn't.
- Dashboard is showing workers for a half second while web page refreshed, then they disappear.
- Can see workers on my web site
- Can see workers on Charts (Monitor)
- Can see tasks and while trying to go to selected worker I see this:

> Unknown worker 'w_bla@HOST.bmc.com'


![flower](https://user-images.githubusercontent.com/12595699/37478938-0fcc8a30-2884-11e8-84c3-dd5969f6b0e2.png)

**Comment by darknate** [comment]
Have a similar issue. Once after I restarted flower all queues in the broker tab just disappeared.

**Comment by emaniacs** [comment]
I got the same issue here,
but when i try to run the worker first and then flower, the worker info shown up.

**Comment by mher** [comment]
I believe the issue was fixed by https://github.com/mher/flower/commit/2436ae77a0e1ff770b51f9eaf121b85aad4873fe

**Comment by jefftriplett** [comment]
@mher thank you. Sorry, this was buried in my email and lost for what appears to be almost four years.

**Comment by sevaiam** [comment]
I'm still running into that issue.
Flower is running in docker container, the workers and task are displayed right, however the broker tab shows  all queues as empty - the same as initial post.
