### ISSUE TITLE
Old (dead) workers appear on the dashboard after autoscaling

### ISSUE THREAD

**Issue by IlianIliev** [mher/flower#612]
We have celery running on AWS inside an autoscaling group. As a result the number of worker nodes varies a lot (for example 2 to 20). The problem is that after autoscaling the dead nodes keep showing up on the dashboard.
Also the later spawned worker have new names based on our naming policy e.g. `w@<ip>-<aws_zone>` the list is constantly growing.

Is there a way to remove the terminated nodes from the dashboard after some time e.g. 24 after shutting the worker down?

**Comment by piotrpawlaczek** [comment]
We have the same problem.
Flower is configured with `--auto_refresh=True`.

Restart helps but then the history is also cleared out...

**Comment by mher** [comment]
You can filter online workers by typing `online` in a search box

**Comment by maxirus** [comment]
+1

**Comment by johnarnold** [comment]
Had similar issues, added https://github.com/mher/flower/pull/709 to clear worker cache
