### ISSUE TITLE
[Feature request] Full breakdown of tasks

### ISSUE THREAD

**Issue by btoueg** [mher/flower#614]
Hi,

I've been using celery for a couple of years now, and I am still feeling quite helpless when tracking down tasks congestions.

I feel the need for a `htop`-like view of my tasks, by name, with full breakdown (incoming rate/average computation time) with running average within 5sec/30sec/5min.

I am neither satisfied of `rabbitmqctl` nor `rabbitmqadmin` because I can't see queues breakdown and I can't see average computation time. Although I considered having one queue per task, I am not convinced I should go through the hassle.

`Flower` tasks view seems to have 80%+ of the data needed to provide an `htop`-like view. However it's designed to audit recently `received`, `processed` and `failed` tasks: nice way of reading the logs, but not a tool to gain vision on congestions.

Am I the only one in this situation ? Maybe I'm not tackling the problem the right way. If so could anyone point me in the right direction or provide me with tools/best pratices I am unaware of?

Thanks

**Comment by maria-jabon** [comment]
I agree with this.  I would very much like this feature, as well as graphs that breakdown by task type, not worker.  We have one worker with many tasks so the graphs are of little use right now.

**Comment by mher** [comment]
You should be able to use Prometheus for this feature. Prometheus integration was added in the recent version.
