### ISSUE TITLE
Unable to get stats for worker (Kombu 3.0.36 using celery 3.1.24 and flower 0.9.1)

### ISSUE THREAD

**Issue by Xepe** [mher/flower#619]
Hello, 

I was having the following issue, 
![image](https://cloud.githubusercontent.com/assets/2806076/19053066/81b4ff64-8976-11e6-9688-fc3edd0bda0a.png)

I did research and I tried the recommendation from https://github.com/mher/flower/issues/438 but it did not work. I reviewed all my packages and my previous installation of celery and I found that it was using Kombu 3.0.35, I changed to that version and with that I was able to see the worker details. 

Using Kombu 3.0.36 the error message was: 
`Control command error: EncodeError(TypeError("<type 'itertools.cycle'> is not JSON serializable",),)
`

Hope this help.

**Comment by broc-harcourt** [comment]
Would second that we've been having this issue, introduced kombu 3.0.35 to our pip requirements to prevent celery from pulling in kombu 3.0.36. Issue occurred for us in both Python 2.7 and Python 3.5 environments. Thank you.

**Comment by sgtsquiggs** [comment]
We're seeing this on celery 3.1.23 and kombu 3.0.35 & 3.0.36. On python 2.7.12

**Comment by mher** [comment]
This issue is fixed in `kombu 3.0.37` https://github.com/celery/kombu/issues/635

**Comment by cjarv** [comment]
Not Sure if this is related. The web UI does not have a worker tab and the api seems to return nothing for both tasks and worker. I also do not have a workers tab nor do the worker links seem to work (returns a 404).

running...
celery==3.1.25
kombu==3.0.37
flower==0.9.2
tornado==5.0.1

So by this did 3.0.37 not fix the issue?
