### ISSUE TITLE
Feature request: django admin authentication

### ISSUE THREAD

**Issue by km-pg** [mher/flower#624]
It would be nice if Flower could somehow share authentication with Django. So, a user could login to django admin and depending on their status (staff, superuser, or specific permission) get access to Flower.

**Comment by km-pg** [comment]
@ask was talking about this over in this django-celery issue: https://github.com/celery/django-celery/issues/474

**Comment by thenewguy** [comment]
This seems like the best way to integrate.  or something similar if you aren't using nginx: https://gist.github.com/hlawrenz/11219276

**Comment by mher** [comment]
There are no plans to work on this feature at the moment until someone decides to contribute to the project.

**Comment by Regressor** [comment]
I tried this:
https://stackoverflow.com/questions/19689510/celery-flower-security-in-production

and all works like a charm.

**Comment by guettli** [comment]
this looks promisiong: use django auth for reverse proxy: https://pypi.org/project/django-revproxy/
