### ISSUE TITLE
Incorrect start_date

### ISSUE THREAD

**Issue by AvihayTsayeg** [mher/flower#627]
Hi,
The start date of a task is incorrect showing date from 1970
![image](https://cloud.githubusercontent.com/assets/702139/19965545/249530ca-a1d0-11e6-9986-84227e7805be.png)
see this [stackoverflow](http://stackoverflow.com/a/20096342) discussion how to compute it correctly

Regards, Avihay

**Comment by mher** [comment]
This issue might be fixed by #670

**Comment by mher** [comment]
Start time is removed from the worker page. See https://github.com/mher/flower/issues/587 for details.
