### ISSUE TITLE
celery timezone issue

### ISSUE THREAD

**Issue by MaxGoh** [mher/flower#628]
flower   -> flower:0.9.1 tornado:4.2 babel:2.3.4
software -> celery:3.1.23 (Cipater) kombu:3.0.35 py:2.7.3
            billiard:3.3.0.23 redis:2.10.3
platform -> system:Linux arch:64bit, ELF imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled

BROKER_TRANSPORT_OPTIONS: {
    'visibility_timeout': 1209600}
CELERY_TIMEZONE: <DstTzInfo 'Asia/Singapore' LMT+6:55:00 STD>
TASK_QUEUE_URL: 'redis://taskqueue.vbee8w.0001.apse1.cache.amazonaws.com:6379/0'

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2717, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flower/views/tasks.py", line 88, in get
    time += '-' + capp.conf.CELERY_TIMEZONE
TypeError: cannot concatenate 'str' and 'Asia/Singapore' objects

Please help with this.

**Comment by MaxGoh** [comment]
Nvm solved!

**Comment by matthewhopkins** [comment]
I am seeing a similar issue, how did you solve it?
