### ISSUE TITLE
Pool restarts not enabled

### ISSUE THREAD

**Issue by yunsonbai** [mher/flower#636]
[{'celery@ubuntu': {'error': "ValueError('Pool restarts not enabled',)"}}]

tag:0.9.1

**Comment by uoxiu** [comment]
http://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-worker_pool_restarts

use it in such a way:
```
app = Celery('name', broker='brokerlink...')

app.conf.update(
    worker_pool_restarts=True,
)
```
