### ISSUE TITLE
flower 0.9.0 / celery 3.1.25 : GET task gives a HTTP 404 when no worker process is available

### ISSUE THREAD

**Issue by tramora** [mher/flower#645]
Hi all,

I use flower 0.9.0 and celery 3.1.25 and submit new tasks via the flower API :

POST /api/task/async-apply/tasks.add

A task id is attributed as the message is received and held by the broker (RabbitMQ).
However when no more process is available in the worker pool (every process is busy or the whole worker family is down), this "ghost" task is not kept in the celery.app.events dict and I get a HTTP 404 error.

My wish is that whenever a task is on the broker (and not acknowledged) any subsequent query returns a task with a PENDING status as this task will be eventually consumed by a worker process.

GET /api/tasks
GET /api/task/info/91396550-c228-4111-9da4-9d88cfd5ddc6
GET /api/task/result/c60be250-fe52-48df-befb-ac66174076e6 

Is there any easy way to do it ? (I'm a bit lost in the flower/celery internals)
Thanks a lot.
Thierry

(I have previously sent this request on the wrong google celery-users group)

**Comment by mher** [comment]
Please try the master version. `flower/utils/search.py` issue has been fixed in the master.
