### ISSUE TITLE
Feature Request: run() method in FlowerCommand

### ISSUE THREAD

**Issue by toryhaavik** [mher/flower#647]
Celery's `worker` `Command` has a nice `run(...)` method ([here](https://github.com/celery/celery/blob/master/celery/bin/worker.py#L230)) that allows you to start a worker from Python, rather than the command.  This is nice for a number of reasons, we mainly use it for starting workers inside integration tests.  We are adding Flower to our program, and it would be nice to have a similar `run(...)` method.  This is in comparison to what I have put together for now (unless I'm missing something obvious in the code):
```
app = Celery(...)
flower = FlowerCommand(app)
flower.run_from_argv("flower", argv="--port={}".format(celery_port))
```

Would there be some interest in this?

**Comment by mher** [comment]
Yep, feel free to create a pull request.
