### ISSUE TITLE
SQS broker not recognized by flower

### ISSUE THREAD

**Issue by utsengar** [mher/flower#65]
I have celery running on my localhost which connects to SQS, I get this error when I launch flower:

```
[I 130406 16:53:31 command:43] Visit me at http://localhost:5555
[I 130406 16:53:31 command:44] Broker: sqs://<url encoded id>@localhost//
[E 130406 16:53:31 state:42] Dashboard and worker management commands are not available for 'N/A' transport
```

I start it using:
`celery flower --broker=sqs://<url encoded id>:<url encoded secret>@`

Celery:  v3.0.17
Installed flower via pip install flower now.

Any suggestions?

**Comment by moshebeeri** [comment]
Same issue, but I see that it is an old request.
How can I add this I am really configured for that.
I may try with few instruction, any one?

**Comment by adhorn** [comment]
Any update? Having flower on top of SQS would be pretty neat if you ask me.

**Comment by moshebeeri** [comment]
It seems that the pub/sub model fits better, so SQS is a major change, not in the scope at the moment.
I kind of needed only basic monitoring so I bridged to redis via other Python lib.
