### ISSUE TITLE
XSS on tasks page

### ISSUE THREAD

**Issue by russtone** [mher/flower#650]
When task url is for example like `http://localhost/?q=<script>alert(1)</script>`
you can see alert on `/tasks` page:

![screen shot 2016-12-12 at 18 47 31](https://cloud.githubusercontent.com/assets/3396041/21105494/7a76a516-c09b-11e6-9470-f3d3544c58cf.png)

This happened because data was not properly escaped here:
https://github.com/mher/flower/blob/master/flower/static/js/flower.js#L800-L804

The fix for this issue I think will be like this:
```js
  }, {
    targets: 4,
    data: 'kwargs',
    visible: isColumnVisible('kwargs'),
    render: function (data) {
        var entityMap = {
            '&': '&amp;',
            '<': '&lt;',
            '>': '&gt;',
            '"': '&quot;',
            '\'': '&#39;',
            '/': '&#x2F;'
        };
        return data.replace(/[&<>"'\/]/g, function (s) {
            return entityMap[s];
        });
    }
}, {
```
Or like this:
```js
}, {
    targets: 4,
    data: 'kwargs',
    visible: isColumnVisible('kwargs'),
    render: $.fn.dataTable.render.text()
}, {
```
`$.fn.dataTable.render.text` appeared in DataTables 1.10.10 (see https://datatables.net/manual/security)

**Comment by mher** [comment]
Fixed by #650
