### ISSUE TITLE
Add ability to reset Active count in Dashboard

### ISSUE THREAD

**Issue by rickwargo** [mher/flower#653]
When my tasks get out of sync, I can reset the world, but I do not wish to reset flower. Often that leads flower into not being able to correctly determine how many active tasks exist. I know there is nothing active at the time - I would like to be able to reset the N/A to 0 without losing the current stats.

![image](https://cloud.githubusercontent.com/assets/430137/21287830/454ad088-c442-11e6-9cf7-011e82b7566e.png)

![image](https://cloud.githubusercontent.com/assets/430137/21287840/9899e63e-c442-11e6-95ea-a88a908d6655.png)

**Comment by mher** [comment]
@rickwargo please try the master version. I have refactored the active number calculation.

**Comment by rickwargo** [comment]
Still the same result. Also, would love the ability to zero out active on demand. Unfortunately, my tasks sometimes cause python to core dump (eventlet) - that's how all gets out of whack.

![image](https://cloud.githubusercontent.com/assets/430137/24152129/21de01d2-0e21-11e7-8faf-d92e8798abb9.png)

**Comment by mher** [comment]
The screen shot is not from the master version. There is no shut down button on the dashboard any more.

**Comment by rickwargo** [comment]
@mher Could it be running the latest code but using earlier templates?

```
[I 170321 07:30:51 command:136] Visit me at http://0.0.0.0:5050
[I 170321 07:30:51 command:141] Broker: redis://localhost:6379/0
[I 170321 07:30:51 command:144] Registered tasks:
    ['celery.accumulate',
     'celery.backend_cleanup',
     'celery.chain',
     'celery.chord',
     'celery.chord_unlock',
     'celery.chunks',
     'celery.group',
     'celery.map',
     'celery.starmap']
[D 170321 07:30:51 command:146] Settings: {'cookie_secret': b'YvXXXfxzT+WkdF6YJ9MJdQfiyJnMjUf3jZXf2YM2+Ic=',
     'debug': False,
     'login_url': '/login',
     'static_path': '/usr/local/lib/python3.5/dist-packages/flower/static',
     'static_url_prefix': '/static/',
     'template_path': '/usr/local/lib/python3.5/dist-packages/flower/templates'}
[D 170321 07:30:51 control:29] Updating all worker's cache...
[I 170321 07:30:51 mixins:224] Connected to redis://localhost:6379/0
[D 170321 07:30:53 app:62] Successfully updated worker cache
[D 170321 07:30:57 dashboard:92] Starting a timer for dashboard updates
[D 170321 07:31:31 dashboard:103] Stopping dashboard updates timer
[D 170321 07:31:50 dashboard:92] Starting a timer for dashboard updates
[D 170321 07:32:02 dashboard:103] Stopping dashboard updates timer
[D 170321 07:32:57 dashboard:92] Starting a timer for dashboard updates
[D 170321 10:31:34 dashboard:103] Stopping dashboard updates timer
[D 170321 10:46:43 dashboard:92] Starting a timer for dashboard updates
```

**Comment by gdoron** [comment]
@mher 
Hi,
Is there an ETA for releasing a version with the re-calculation?

Thanks.

**Comment by ohld** [comment]
![image](https://user-images.githubusercontent.com/5613295/75335385-7cc95a80-589a-11ea-954a-28211d4a430a.png)
Is there a way to reset the flower's data? I'm deploying the celery workers using dokku (open source Heroku) and it generates different names for workers. In that case, I have a huge amount of workers and failed tasks (while in practice I have only 2 workers). 

How can I reset the flower data?
