### ISSUE TITLE
Is logout working ?

### ISSUE THREAD

**Issue by a1Gupta** [mher/flower#654]
I am using the latest code from the master branch. It shows logout button. On clicking it shows successfully logged out, but its not logging out. When I press back button, it shows the dashboard again with user logged in. I am using Chrome browser. Also I tried to check the browser console, but I can't see any cookie named `'user'`. Is it working for anyone ? 

I can provide additional info if any required. Also when user is logged in `/login` url shows some error, shouldn't that redirect to `/ or /dashboard` if user is logged in ?

**Comment by olalonde** [comment]
I have the same issue. Using GH oauth.

**Comment by mingxs** [comment]
same issue

**Comment by blackholll** [comment]
still not work in version 0.9.3.    from 18 Dec 2016 to now?

**Comment by blackholll** [comment]
@mher

**Comment by stariqmi** [comment]
@mher Any updates on this? This is a pretty big issue.

**Comment by stariqmi** [comment]
Part of it is working as expected. I was using the GitHub auth. As long as I am logged in to Github, I am automatically logged back in but once I log out of Github and log out of Flower, I need to log in to GitHub again to be able to access Flower.

However with Basic Auth, I was expecting that I will be prompted for a password again which is not the case.

**Comment by stariqmi** [comment]
@mingxs @blackholll please read my above comment. It is working as expected with OAuth2 protocol.

@mher my apologies, I should have cleared up my understanding of Basic Authentication. Basic Authentication is not designed for "logout". A user will remain logged in till the browser window is open. For those interested, the following has some hacks/workarounds to force a logout:

https://stackoverflow.com/questions/233507/how-to-log-out-user-from-web-site-using-basic-authentication

**Comment by mher** [comment]
https://github.com/mher/flower/commit/830e6a98cf1b38358cffa039ce33e311301583ee removes logout
