### ISSUE TITLE
500 Internal Server Error, While Accessing /api/tasks

### ISSUE THREAD

**Issue by Tibingeo** [mher/flower#659]
`wget http://127.0.0.1:5555/api/tasks` returns HTTP request sent, awaiting response... 500 Internal Server Error.

**Comment by Tibingeo** [comment]
Flower log -  celerymon [11/Jan/2017:14:57:22 +0000] "GET /api/tasks HTTP/1.1" 500 0 "-"

**Comment by tramora** [comment]
Hi @Tibingeo : difficult to help you without any usable log.
I faced a HTTP 500 error too related to a KeyError on properties root and parent in celery 4.x.
c.f #626

**Comment by simonluijk** [comment]
I am seeing the same issue the exceptions are.


When ordering by kwargs

    flower   -> flower:0.9.0 tornado:4.2 babel:2.3.4
    software -> celery:3.1.24 (Cipater) kombu:3.0.36 py:3.5.1
                billiard:3.3.0.23 py-amqp:1.4.9
    platform -> system:Linux arch:64bit imp:CPython
    loader   -> celery.loaders.default.Loader
    settings -> transport:amqp results:disabled

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/site-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.5/site-packages/tornado/web.py", line 2717, in wrapper
        return method(self, *args, **kwargs)
      File "/usr/local/lib/python3.5/site-packages/flower/views/tasks.py", line 45, in get
        reverse=sort_order)
    TypeError: unorderable types: str() < NoneType()


When ordering by `started`

    flower   -> flower:0.9.0 tornado:4.2 babel:2.3.4
    software -> celery:3.1.24 (Cipater) kombu:3.0.36 py:3.5.1
                billiard:3.3.0.23 py-amqp:1.4.9
    platform -> system:Linux arch:64bit imp:CPython
    loader   -> celery.loaders.default.Loader
    settings -> transport:amqp results:disabled

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/site-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.5/site-packages/tornado/web.py", line 2717, in wrapper
        return method(self, *args, **kwargs)
      File "/usr/local/lib/python3.5/site-packages/flower/views/tasks.py", line 45, in get
        reverse=sort_order)
    TypeError: unorderable types: float() < NoneType()

**Comment by tramora** [comment]
@simonluijk : you get a 500 error using the dashboard not the API so the issue is not related.
Anyway for your issue, it seems that there are uninitialized values in your data that make the comparaison fail.

**Comment by mher** [comment]
@simonluijk the master version contains a fix for the issue
