### ISSUE TITLE
Monitor not Drawing/Displaying Traffic for Remote Worker

### ISSUE THREAD

**Issue by sterrell** [mher/flower#66]
On the Monitor tab, the graph is only displaying the traffic for my local (same server that runs rabbitMQ and flower) celery worker.  It is not displaying the traffic for my remote (running on different server) celery worker.

I am sure I have started the remote worker correctly and have it configured correctly, because the other Flower tabs _do_ show that the remote tasks are being executed successfully.  And, my app is working fine.

Not sure if it is a factor or not, but each worker is assigned its own distinct queue.  Also I should mention that the local worker task uses apply_async to send a task to the remote worker, in case this is unusual.

I'm new to python, Celery, and Flower.  If you can offer suggestions on what I might be doing wrong, I'll sure appreciate it.

Thanks,
    Steve

**Comment by fccoelho** [comment]
I am having this issue when running everything on the same machine, so it can't be a clock synchrony issue... I only get the queued tasks graph. not the other three...

**Comment by cutso** [comment]
for late, i have the same problem, but solved it well.
when most guy create virtual host and user, they forgot to set a tag.  rabbitmq user's tag.

so, just check your rabbitmq user's tag, make sure it is setting to administrator or management.

you can use rabbitmq-plugin command or it's web management.

Thank you!
