### ISSUE TITLE
Flower Broker tab fail with HTTP 500: Internal Server Error

### ISSUE THREAD

**Issue by suvari3V** [mher/flower#661]
I am using Celery Flower with RabbitMQ as message broker. However I am getting nasty error

> ERROR - RabbitMQ management API call failed: HTTP 500: Internal Server Error

every time I try to access RabbitMQ queues on RabbitMQ management interface (http://localhost:15672/#/queues) or Celery Broker (http://localhost:5555/broker).

Here is a detailed log info:

> =ERROR REPORT==== 15-Jan-2017::23:12:19 === webmachine error: path="/api/queues/%2F" {error,{error,function_clause, [{mochijson2,json_encode_string_unicode, [{error,[],<<166,65,92,180,0,0,0,0,0>>}, {encoder,null,false}, """], [{file,"src/mochijson2.erl"},{line,274}]}, {mochijson2,'-json_encode_proplist/2-fun-0-',3, [{file,"src/mochijson2.erl"},{line,198}]}, {lists,foldl,3,[{file,"lists.erl"},{line,1248}]}, {mochijson2,json_encode_proplist,2, [{file,"src/mochijson2.erl"},{line,202}]}, {mochijson2,'-json_encode_proplist/2-fun-0-',3, [{file,"src/mochijson2.erl"},{line,199}]}, {lists,foldl,3,[{file,"lists.erl"},{line,1248}]}, {mochijson2,json_encode_proplist,2, [{file,"src/mochijson2.erl"},{line,202}]}, {mochijson2,'-json_encode_array/2-fun-0-',3, [{file,"src/mochijson2.erl"},{line,189}]}]}}

RabbitMQ web management gives me:

> Got response code 500 with body {"error":"Internal Server Error","reason":"{error,{error,function_clause,\n [{mochijson2,json_encode_string_unicode,\n [{error,[],<<166,65,92,180,0,0,0,0,0>>},\n {encoder,null,false},\n "\""],\n [{file,"src/mochijson2.erl"},{line,274}]},\n {mochijson2,'-json_encode_proplist/2-fun-0-',3,\n [{file,"src/mochijson2.erl"},{line,198}]},\n {lists,foldl,3,[{file,"lists.erl"},{line,1248}]},\n {mochijson2,json_encode_proplist,2,\n [{file,"src/mochijson2.erl"},{line,202}]},\n {mochijson2,'-json_encode_proplist/2-fun-0-',3,\n [{file,"src/mochijson2.erl"},{line,199}]},\n {lists,foldl,3,[{file,"lists.erl"},{line,1248}]},\n {mochijson2,json_encode_proplist,2,\n [{file,"src/mochijson2.erl"},{line,202}]},\n {mochijson2,'-json_encode_array/2-fun-0-',3,\n [{file,"src/mochijson2.erl"},{line,189}]}]}}\n"}

I am using:

- Ubuntu 14.04
- Python 2.7.6
- Flower 0.9.1
- Celery 4.0.2
- RabbitMQ 3.6.6
- Erlang/OTP 19

RabbitMQ management plugin is enabled (rabbitmq-plugins enable rabbitmq_management).

Here is the output for rabbitmqctl status:

> [{pid,28609}, {running_applications, [{rabbitmq_management,"RabbitMQ Management Console","3.6.6"}, {amqp_client,"RabbitMQ AMQP Client","3.6.6"}, {rabbitmq_management_agent,"RabbitMQ Management Agent","3.6.6"}, {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.6.6"}, {rabbit,"RabbitMQ","3.6.6"}, {os_mon,"CPO CXC 138 46","2.4.1"}, {webmachine,"webmachine","1.10.3"}, {mochiweb,"MochiMedia Web Server","2.13.1"}, {ssl,"Erlang/OTP SSL application","8.1"}, {public_key,"Public key infrastructure","1.3"}, {crypto,"CRYPTO","3.7.2"}, {rabbit_common,[],"3.6.6"}, {xmerl,"XML parser","1.3.12"}, {asn1,"The Erlang ASN1 compiler version 4.0.4","4.0.4"}, {syntax_tools,"Syntax tools","2.1.1"}, {mnesia,"MNESIA CXC 138 12","4.14.2"}, {compiler,"ERTS CXC 138 10","7.0.3"}, {ranch,"Socket acceptor pool for TCP protocols.","1.2.1"}, {inets,"INETS CXC 138 49","6.3.4"}, {sasl,"SASL CXC 138 11","3.0.2"}, {stdlib,"ERTS CXC 138 10","3.2"}, {kernel,"ERTS CXC 138 10","5.1.1"}]}, {os,{unix,linux}}, {erlang_version, "Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:4:4] [async-threads:64] [kernel-poll:true]\n"}, {memory, [{total,112070616}, {connection_readers,471152}, {connection_writers,171664}, {connection_channels,494680}, {connection_other,407232}, {queue_procs,534792}, {queue_slave_procs,0}, {plugins,2121728}, {other_proc,12017232}, {mnesia,93584}, {mgmt_db,5114688}, {msg_index,49304}, {other_ets,1902144}, {binary,52694768}, {code,24783822}, {atom,1033401}, {other_system,10180425}]}, {alarms,[]}, {listeners,[{clustering,25672,"::"},{amqp,5672,"::"}]}, {vm_memory_high_watermark,0.4}, {vm_memory_limit,6691391078}, {disk_free_limit,50000000}, {disk_free,59039645696}, {file_descriptors, [{total_limit,3996}, {total_used,23}, {sockets_limit,3594}, {sockets_used,20}]}, {processes,[{limit,1048576},{used,454}]}, {run_queue,0}, {uptime,2498}, {kernel,{net_ticktime,60}}]

Here is how I run Celery:

Start 3 celery workers:

- celery worker -A celeryapp --config celeryconfig --workdir /proj -l DEBUG --soft-time-limit=3500 --time-limit=3600 --autoscale=2,1 -S /proj/states.db -s /proj/celerybeat-schedule.db -f /proj/logs/celery_worker_1_%n%I.log --pidfile /tmp/celery_w1.pid -n worker1@%d
- celery worker -A celeryapp --config celeryconfig --workdir /proj -l DEBUG --soft-time-limit=3500 --time-limit=3600 --autoscale=2,1 -S /proj/states.db -s /proj/celerybeat-schedule.db -f /proj/logs/celery_worker_2_%n%I.log --pidfile /tmp/celery_w2.pid -n worker2@%d
- celery worker -A celeryapp --config celeryconfig --workdir /proj -l DEBUG --soft-time-limit=3500 --time-limit=3600 --autoscale=2,1 -S /proj/states.db -s /proj/celerybeat-schedule.db -f /proj/logs/celery_worker_3_%n%I.log --pidfile /tmp/celery_w3.pid -n worker3@%d

Start celery beat:

- celery beat -A celeryapp --config celeryconfig --workdir /proj -l DEBUG -s /proj/celerybeat-schedule.db -f /proj/logs/celery_%n%I.log --pidfile /tmp/celery.pid

Start celery flower:

- celery flower -A celeryapp --workdir=/proj/ --broker=amqp://guest:guest@localhost:5672// --broker-api=http://guest:guest@localhost:15672/api/ --db=/proj/flower.db --logging=debug --basic-auth=guest:guest

I posted this question in Github issues of RabbitMQ but it was [rejected](https://github.com/rabbitmq/rabbitmq-server/issues/1081)

There is a [StackOverflow question](http://stackoverflow.com/questions/41667169/rabbitmq-management-api-call-failed-http-500-internal-server-error) opened also.

**Comment by addodelgrossi** [comment]
I have the same problem.

**Comment by suvari3V** [comment]
@addodelgrossi  I was not able to find solution for this problem so I switched to Redis backend.

**Comment by mher** [comment]
Closing this issue. It is a RabbitMQ issue. rabbitmqctl status reports the same error as flower

**Comment by addodelgrossi** [comment]
@suvari3V thanks !!
