### ISSUE TITLE
GET /api/task/info/(.*) results in 404s if task has been retried

### ISSUE THREAD

**Issue by BjBlazkowicz** [mher/flower#664]
Seems like a bug.

Tasks that has been retried keeps the same ID so this should not happen.

Flower version used: 0.8.4

**Comment by rafaelreuber** [comment]
Have you tried to reproduce de this bug using the version 0.9.1?

**Comment by anilpai** [comment]
/api/task/info gives 500 Server Error . This is a known open bug. https://github.com/mher/flower/issues/617

**Comment by anilpai** [comment]
This bug is fixed now on master, but since I was using 0.92 release, it was giving me this error. Looking forward to next release.
