### ISSUE TITLE
DB username/password are displayed in plain text in Broker_URL field when celery flower encounters error and dumps out debug information

### ISSUE THREAD

**Issue by kb99** [mher/flower#665]
If celery flower encounters an error, it dumps out all its config to help troubleshoot why the issue could occur.

Most passwords are obfuscated using astrix.

However the Broker_URL param still outputs the username:password that is included in the URL string.

```
CELERY_MONGODB_BACKEND_SETTINGS: {
    'database': '********',
    'password': '********',
    'taskmeta_collection': 'taskmeta_collection',
    'user': u'db_user'}
CELERYD_PREFETCH_MULTIPLIER: 1
BROKER_URL: u'mongodb://db_user:password1@localhost/broker'
```

**Comment by mher** [comment]
flower uses celery's `bugreport` method to show debug info. In the master version bugreport is only visible only in debug mode (`--debug` option is enabled).

**Comment by mher** [comment]
Please provide a version info when you open an issue.

**Comment by mher** [comment]
`flower --version`
