### ISSUE TITLE
Tasks are not automatically refreshed

### ISSUE THREAD

**Issue by ddahan** [mher/flower#668]
Hi, 

Not sure if it's an actual issue, but when I'm on the tasks tab (`/tasks`), task informations are not automatically updated, I need to refresh my browser to see them.
However, in the dashboard (`/`), worker informations are automatically refreshed.

I launch Celery and Flower this way:
`celery -A myproject worker --loglevel=info`
`celery -A myproject flower --port=5555 --persistent=True`
(Note that I do not need to set the `--auto-refresh` option since the default value is True)

I'm using Celery 4.0.2 and Flower 0.9.1

**Comment by mher** [comment]
Tasks page doesn't auto refresh

**Comment by ddahan** [comment]
@mher is it a technical limitation that prevented you from doing it?

**Comment by mher** [comment]
@ddahan there is no technical limitation. Tasks page needs some refactoring before auto-refresh.

**Comment by philip-C96** [comment]
In case I missed the update, I just refreshed Chrome itself with an extension. (ref: https://chromewebstore.google.com/detail/easy-auto-refresh/aabcgdmkeabbnleenpncegpcngjpnjkc)

**Comment by XotEmBotZ** [comment]
@mher Can I get some info about an estimate when this refactoring will be done or is it not planned for the near future?
