### ISSUE TITLE
Unknown Celery version ValueError: Invalid http api schema: redis

### ISSUE THREAD

**Issue by Amet13** [mher/flower#673]
Hello!
I'm using configuration for celery and flower:
```
CELERY_BROKER_URL='redis://redis:6379/0'
broker_api = 'redis://redis:6379/0'
logging = 'DEBUG'
address = '0.0.0.0'
auto_refresh = True
port = 8888
xheaders = True
```

Before this I installed:
```
pip3 install flower redis celery-with-redis
```

Checking connect to redis, it's OK:
```
root@8358ca511e9e:/# redis-cli -h redis
redis:6379> 
```

But in web interface i see:
![screenshot at 2017-03-02 23-58-57](https://cloud.githubusercontent.com/assets/5184847/23526747/3fdd3864-ffa4-11e6-8c07-421d38b7803d.png)

I don't understand, where is my mistake.
Can you help me? Thanks.

**Comment by mher** [comment]
broker_api should start with http://. For redis you can omit broker_api option.

**Comment by Amet13** [comment]
If' I omit this option, how can I use Broker tab in Flower?
Here is an example: http://flower.dandad.org/broker

**Comment by Amet13** [comment]
I ran flower like:
```
flower --broker=redis://172.17.0.2:6379/0 --conf=/etc/flower/flowerconfig.py
```
Where flowerconfig.py:
```
logging = 'DEBUG'
address = '0.0.0.0'
auto_refresh = True
port = 8888
xheaders = True
```
Now all ok. Thanks.
