### ISSUE TITLE
Celery once password is displayed in the worker configuration

### ISSUE THREAD

**Issue by xavierhardy** [mher/flower#685]
In the worker configuration page (`worker/celery@WORKER_NAME#tab-config`), the Celery once password is displayed. You should more generally remove passwords from URLs.
```
BROKER_URL 	redis://:********@127.0.0.1:12345/1
BROKER_USE_SSL 	True
CELERY_ACCEPT_CONTENT 	['json']
CELERY_IMPORTS 	['path.tasks']
CELERY_INCLUDE 	['celery.app.builtins', 'path.tasks']
CELERY_RESULT_BACKEND 	redis://:********@127.0.0.1:12345/2
CELERY_RESULT_SERIALIZER 	json
CELERY_TASK_SERIALIZER 	json
ONCE_DEFAULT_TIMEOUT 	3600
ONCE_REDIS_URL 	redis://:my_password@127.0.0.1:12345/3
```

**Comment by mher** [comment]
Flower shows all config options received from celery without modification.

In general, Celery removes passwords before replying to conf requests like in case of `BROKER_URL`. But Celery once is a third party library and `ONCE_REDIS_URL` is not a standard Celery option. I'd suggest to open a Celery issue to prevent sending non standard options or at least implement some mechanism to filter sensitive information.

As a workaround, you can disable conf responses from celery or override the default implemantation.
