### ISSUE TITLE
Flower leaks tracebacks on HTTP 500 in production mode

### ISSUE THREAD

**Issue by miedzinski** [mher/flower#691]
Currently flower leaks full tracebacks to any user on HTTP 500 when `debug` is `False`. It used to be worse; until #633 got merged, flower was leaking configuration as well. Still, this is unsafe, becase it gives potential attacker a lot of information. IMO unless `debug` is `True`, the app shouldn't show user anything more than simple HTTP 500.

**Comment by miedzinski** [comment]
My bad, I was running older flower version. #633 actually fixes this.

**Comment by miedzinski** [comment]
OTOH, the fix still isn't published to PyPI, but this is quite serious. Can we atleast get minor patch with #633? I don't feel safe running flower straight from `master` - is it stable?

**Comment by mher** [comment]
Flower 0.9.2 has been released!
