### ISSUE TITLE
Is a new release of flower planned

### ISSUE THREAD

**Issue by Darkheir** [mher/flower#692]
Hi folk,

Is there a new release of Flower planned ?
Because the last one is now more than a year old and I think that a lot of improvements have been done since.

**Comment by hassek** [comment]
I also noticed that pypi sometimes let's me install flower==1.0.0 and later it falls back to 0.9.1.

```
flower (0.9.1)               - Celery Flower
  INSTALLED: 1.0.0
  LATEST:    0.9.1
```

**Comment by tablet-mode** [comment]
This would really be great to know, we use flower for some of our monitoring and just installing stuff directly out of a git repo instead of pypi is not exactly something we want to do.

**Comment by mher** [comment]
Flower 0.9.2 has been released!
