### ISSUE TITLE
Return a result on failed task

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [mher/flower#696]
Hi,

I have an app that is using celery periodic tasks and coding it via class-based. I understand that to fill up the Result on the tasks page is you need to return a value like

`class PeriodicSet(PeriodicTask):
    run_every = timedelta(**{'seconds': 30})

    def run(self, **kwargs):
        return 'Hello World'`

But I can not return a result for failed task I tried the code below but nothing is returning
`class PeriodicSet(PeriodicTask):
    run_every = timedelta(**{'seconds': 30})

    def on_failure(self, exc, task_id, args, kwargs, einfo):
        return 'You Failed me'

    def run(self, **kwargs):
    	wrong_code
        return 'Hello World'`

So how can I return something on failed task? I can't find in the documentation the procedure to do this..

**Comment by mher** [comment]
This is not a flower question. Please try celery-users mailing list or stackoverflow
