### ISSUE TITLE
Celery inspect active shows two workers - Flower ui does not

### ISSUE THREAD

**Issue by rak19** [mher/flower#698]
When I run following I am able to see two workers. 

celery inspect active 

However, in the Dashboard section no workers are shown. 
<img width="889" alt="screen shot 2017-05-29 at 4 41 11 pm" src="https://cloud.githubusercontent.com/assets/3232585/26547649/b5859876-448d-11e7-8819-2bb8b3597367.png">

In tasks section I can see them as 2 consumers. 

<img width="709" alt="screen shot 2017-05-29 at 4 41 22 pm" src="https://cloud.githubusercontent.com/assets/3232585/26547659/c1008210-448d-11e7-8905-c9f5d2b0378d.png">

If I restart celery workers, they start appearing in dashboard.

**Comment by mher** [comment]
Please provide version info `flower --version`

**Comment by rak19** [comment]
flower --version
0.9.1
4.0.2 (latentcall)
Unknown Celery version

**Comment by ttyS15** [comment]
+1

Flower 0.9.2
Celery 4.1.0

Workers is lost time to time. Flower need restart to pick up a losing worker.

![2017-11-24_02-35-45](https://user-images.githubusercontent.com/1039574/33190699-ca496f84-d0c0-11e7-877d-0123b4409554.png)

![2017-11-24_02-34-47](https://user-images.githubusercontent.com/1039574/33190700-d1469e92-d0c0-11e7-839f-7168548e03fc.png)

**Comment by Bolik** [comment]
+1

**Comment by Greenev** [comment]
+1

**Comment by mher** [comment]
Inspect commands have been refactored. Please try the latest master version.
