### ISSUE TITLE
Github OAuth & url_prefix

### ISSUE THREAD

**Issue by prayerslayer** [mher/flower#703]
Hi,

thanks for this tool, it's really valuable to inspect what Celery is doing!

We run it with Github OAuth behind a reverse proxy and one minor issue is that after logging in, you're not redirected to the correct path where flower runs (eg `/flower`), but to root (`/`). You have to manually navigate to `/flower` afterwards.  I suspect it's caused by [this line](https://github.com/mher/flower/blob/6cc83ed3cd11b9886ad029c5aad54de12d991b3a/flower/views/auth.py#L65), but I might as well be guessing.

If you could give me some guidance I'm happy to help out with this.

**Comment by mher** [comment]
Replacing https://github.com/mher/flower/blob/6cc83ed3cd11b9886ad029c5aad54de12d991b3a/flower/views/auth.py#L65 with `next = self.get_argument('next', self.application.options.url_prefix or ‘/‘)` should fix the issue

**Comment by mher** [comment]
Feel free to open a pull request

**Comment by mher** [comment]
Fixed by #718
