### ISSUE TITLE
Flower overloading redis

### ISSUE THREAD

**Issue by neutralino1** [mher/flower#706]
Yesterday, our redis instance contained 20GB's worth of data stored in keys of the form `*.reply.celery.pidbox`.

It seems the solution is to disable remote control:
`app.conf.worker_enable_remote_control = False`

But then of course flower does not work anymore. What is the solution to this problem?

Happy to help if pointed in the right direct.

**Comment by mher** [comment]
You can use [--enable-events](http://flower.readthedocs.io/en/latest/config.html#enable-events) option to disable sending enable events to celery
