### ISSUE TITLE
Getting 500 for tasks

### ISSUE THREAD

**Issue by navyad** [mher/flower#714]
Getting 500 error without any info for `"http://127.0.0.1:5555/api/tasks"`

Although i have DEBUG=True.

![screen shot 2017-06-28 at 5 19 02 pm](https://user-images.githubusercontent.com/1172317/27635552-19e25620-5c25-11e7-835a-4d7706d4e305.png)

How to debug ?

**Comment by mher** [comment]
There should be a stack trace in the stderr

**Comment by mher** [comment]
No response, closing
