### ISSUE TITLE
Flower does not listen to broker_url celery setting from config file

### ISSUE THREAD

**Issue by lewistaylor** [mher/flower#715]
Unless I'm mistaken, the following configuration should work when running `flower --conf=/flower/conf/celeryconfig.py`, where the config file is located in the correct location.

```
# Celery override, adding both because --broker seems to work
# but celery docs ask for broker_url
broker = 'amqp://guest:guest@queue:5672//'
broker_url = 'amqp://guest:guest@queue:5672//'

# RabbitMQ management api
BROKER_URL = 'amqp://guest:guest@queue:5672//'

# Enable debug logging
logging = 'DEBUG'
```

However I see this output:
```
......
28/06/2017 13:34:25      File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 802, in connection
28/06/2017 13:34:25        self._connection = self._establish_connection()
28/06/2017 13:34:25      File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 757, in _establish_connection
28/06/2017 13:34:25        conn = self.transport.establish_connection()
28/06/2017 13:34:25      File "/usr/local/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
28/06/2017 13:34:25        conn.connect()
28/06/2017 13:34:25      File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 294, in connect
28/06/2017 13:34:25        self.transport.connect()
28/06/2017 13:34:25      File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 120, in connect
28/06/2017 13:34:25        self._connect(self.host, self.port, self.connect_timeout)
28/06/2017 13:34:25      File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 161, in _connect
28/06/2017 13:34:25        self.sock.connect(sa)
28/06/2017 13:34:25    ConnectionRefusedError: [Errno 111] Connection refused
28/06/2017 13:34:30[D 170628 12:34:30 events:133](B Failed to enable events: '[Errno 111] Connection refused'
```

The flower docs quote:
> Standard Celery configuration settings can be overridden in the configuration file. See Celery Configuration reference for a complete listing of all the available settings, and their default values.

This would therefore appear to be a bug, as running `flower --conf=/flower/conf/celeryconfig.py --broker=amqp://guest:guest@queue:5672//` works as expected.

**Comment by russoz** [comment]
Funnily enough, I don't see a `broker` option in the configuration file documentation:
https://flower.readthedocs.io/en/latest/config.html

Even though it mentions the CLI parameter, it does not describe the option in the file.

**Comment by gwsampso** [comment]
same problem

**Comment by mher** [comment]
broker config option should be passed through `--broker` option or via celery application

**Comment by NullYing** [comment]
> broker config option should be passed through `--broker` option or via celery application

I use Aliyun RabbitMQ, It need run the auth code to generate password, so I need load broker from config.
