### ISSUE TITLE
Websocket 403 error with cross origin request

### ISSUE THREAD

**Issue by JamesRamm** [mher/flower#716]
I am getting a 403 error when trying to open a websocket to flower. 

I have flower running on `localhost:5555`  and my web app trying to create the web socket on `localhost:5001`
The celery tasks are called via another api on port `5000`. 

I have seen https://github.com/mher/flower/issues/660 but can't see how to proceed?

My JS client code:

    const ws = new WebSocket('ws://localhost:5555/api/task/events/task-succeeded/');

**Comment by Kokozzi** [comment]
I think that same changes, appeared at #660 should be added to api/__init__ at `BaseWebSocketHandler` class
@ask

**Comment by mher** [comment]
Fixed by https://github.com/mher/flower/commit/92b837d882e127a91376d7e0642f9d06e75e3a47
