### ISSUE TITLE
Add Maintainers?

### ISSUE THREAD

**Issue by johnarnold** [mher/flower#722]
@mher 

Many people use flower. Flower is great. Thank you for flower.

Like any project, there are bugs.  There's a backlog of PRs for bugs.  There's also a backlog of PRs for new features, which is great too.   Unfortunately it seems that you are busy with other projects, as the commits are very few and far between.

I noticed on the README you left a "If you are interested in maintaining the project please contact."

I'll throw my hat in the ring to help maintain.  I'm already maintaining a merge branch https://github.com/johnarnold/flower/tree/msftint for our features and other's bugfixes, but I'd much rather help get things into the upstream.

Maybe others that are actively using flower and would like to help? Maybe someone else can join maintainers for some diversity / coverage?

Please let us know your thoughts on how we can keep this project alive.  Forking sucks :)

Thanks!
John

**Comment by mher** [comment]
Thanks for your contributions! Unfortunately not all pull requests are ready to be merged. Most of the fixes are not general enough. Merging such PRs will introduce new bugs.

If you are interested in contributing I'd be glad to help you. The project is open for all kind of contributions.

**Comment by johnarnold** [comment]
@mher I'm sorry you felt the need to close this.  You seem willing to help, but you went months and months without committing anything, even bug fixes, and no comments on PRs for a long time -- many months.  I really don't want you to think I'm being critical of you personally. I'm sure you're just busy.   For the sake of the flower app, it would really help to have additional maintainer(s). It doesn't have to be me.
