### ISSUE TITLE
Setting mode on unix_socket

### ISSUE THREAD

**Issue by pembo13** [mher/flower#725]
It would be very useful to set the mode on the socket, the default is 0600

I had to change `socket = bind_unix_socket(self.options.unix_socket)` to `socket = bind_unix_socket(self.options.unix_socket, mode=0o777)`  so that Nginx could read/write to the socket.

**Comment by saytik** [comment]
have  the  same  issue,  nginx  can't  get  flower  socket  with  600  and  i  can't change  socket permissions 
(for  examle uwsgi  have  chmod-socket  option)

**Comment by pembo13** [comment]
Looks like this is still a problem, how are people getting around this?

**Comment by pembo13** [comment]
This looks like it should be a simple fix, that's currently making a feature of Flower impossible to use.

**Comment by andreymal** [comment]
Yup, this is an absolutely necessary feature. Unix socket is useless without this. It's strange that this is still not implemented.

**Comment by pembo13** [comment]
Anything that can be done to accelerate this?

**Comment by mher** [comment]
I'd avoid introducing a new option. The mode can be set by parent directory. Unix sockets honor the permissions of parent directory.

**Comment by mher** [comment]
Modifying the default mode is also acceptable solution

**Comment by pembo13** [comment]
> The mode can be set by parent directory. Unix sockets honor the permissions of parent directory.

@mher that's almost definitely not what's happening in the real world. I wouldn't be here if it was that simple.

**Comment by HOSTED-POWER** [comment]
same problem here, no fix apparently yet? Need chmod 0777 for nginx

**Comment by pembo13** [comment]
Guys it's been almost 3 years... can we get this fixed?

**Comment by HOSTED-POWER** [comment]
indeed it would be a really nice addition to simply control this in the settings! :)

**Comment by pembo13** [comment]
I'd be happy to put in a pull request if the devs would state their preference.

**Comment by pembo13** [comment]
@mher thank you.

**Comment by HOSTED-POWER** [comment]
isn't there a typo? 0o777 ? Shouldn't it be 0777

**Comment by mher** [comment]
https://www.python.org/dev/peps/pep-3127/

`octal literals must now be specified with a leading "0o" or "0O" instead of "0";`

**Comment by HOSTED-POWER** [comment]
ok perfect, we're not Python developers haha :)
