### ISSUE TITLE
Get total count of tasks of each worker easily from http api

### ISSUE THREAD

**Issue by AdemKerenci** [mher/flower#730]
I am trying to get the total count of proceed tasks of each worker, I find a way with retrieving total count from api/workers but it is too costly(in terms of time) since I use more than 200 workers with a lot of job. 

I ask you that could you add a parameter to api/workers like tasks=1(get task information of workers) like status=1 in current api so that it will only return me worker name and proceeded task count of that worker.

If you also mind to return success, failed and retried information of tasks, it would be better.

**Comment by mher** [comment]
There are no plans to work on this feature at the moment until someone decides to contribute to the project.
