### ISSUE TITLE
format_task not applied to TaskView

### ISSUE THREAD

**Issue by kecorbin** [mher/flower#735]
This project is awesome!  I have a question which may be something simple I'm missing from the docs.  I'm using [format_task](http://flower.readthedocs.io/en/latest/config.html#format-task) to attempt prevent some sensitive args data from being displayed in the UI (and API)

From what I can tell, format_task is only applied to the [TasksDataTable](https://github.com/mher/flower/blob/master/flower/views/tasks.py#L51) not [TaskView](https://github.com/mher/flower/blob/master/flower/views/tasks.py#L20)
 
As a result, the sensitive information is removed from the tasks list, but not the task detail. 
Am I missing something?  

My flowerconfig.py looks like this:
```
from flower.utils.template import humanize
from ast import literal_eval

def format_task(task):
    task.args = literal_eval(task.args)[1]
    task.result = humanize(task.result, length=20)
    return task
```
Is there a simple way to remove args from being displayed altogether on the UI (and API as well)

**Comment by kecorbin** [comment]
FWIW, I was able to get my desired results like such: 
https://github.com/kecorbin/flower/commit/919012074a10ba2d0947b70ca3adfce571098176

Just curious if there is an easier way

**Comment by mher** [comment]
`format_task` is not currenly supported by `TaskViiew`. @kecorbin can you open a pool request? You can move the current implementation of `format_task` to `BaseHandler` and call it from `TaskView` and `TasksDataTable`

**Comment by kecorbin** [comment]
@mher The implementation of format_task in `TasksDataTable` seems slightly different as a tuple is received back from iter_tasks generator [here](https://github.com/mher/flower/blob/cf980df2b59fa2accdca7d8009d3e4ec8367ecd8/flower/views/tasks.py#L50).  

#748 implements `format_task` in `BaseHandler` but is now overriden by `TasksDataTable`
