### ISSUE TITLE
Revoking task from Flower UI successfull, but celery job continues to run

### ISSUE THREAD

**Issue by morphyno** [mher/flower#736]
I'm using Flower/Celery to orchestrate iperf jobs between a number of machines. I noticed when I revoke the job from Flow UI, the UI states the operation is successfull, but the job still runs in the background.

When I check the celery log, I see the following:

`[2017-09-15 12:05:26,543: INFO/MainProcess] Terminating b6e9961f-244c-4cf3-a830-cc363caf5d73 (15)
[2017-09-15 12:05:30,963: ERROR/MainProcess] Task framework.traff_tasks.traffictask[b6e9961f-244c-4cf3-a830-cc363caf5d73] raised unexpected: Terminated(15,)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 1678, in _set_terminated
    raise Terminated(-(signum or 0))
Terminated: 15
`

I'm running on Flower version 0.9.2 and celery 3.1.25

From the description of this [https://github.com/celery/celery/issues/2727](url), could this be a celery issue?

**Comment by johnarnold** [comment]
Suggest trying with celery 4.1.0 -- lots of fixes.

**Comment by morphyno** [comment]
Thanks, this seems to occur on 4.1.0 as well, and it seems broadcast queue is also broken on 4.1.0. I am currently using a custom function to stop tasks as a workaround. This does not seem to be a flower issue.
