### ISSUE TITLE
How to see celery periodic tasks on flower web?

### ISSUE THREAD

**Issue by skamsie** [mher/flower#740]
How to see the tasks that are running periodically? I assumed they would show up on the http://localhost:5555/worker/celery@my_machine#tab-tasks page, under "scheduled tasks", but they do not.

I have the following _tasks.py_ file

```
import random
from celery import Celery
from celery.schedules import crontab

app = Celery('tasks', broker='redis://localhost:6379/0')

@app.on_after_configure.connect
def setup_periodic_tasks(sender, **kwargs):
    sender.add_periodic_task(100, test.s(30000), name='every 100')

    sender.add_periodic_task(10, test.s(100), name='every 10')

    # Executes every Monday morning at 7:30 a.m.
    sender.add_periodic_task(
        crontab(hour=7, minute=30, day_of_week=1),
        test.s(40),
    )

@app.task
def test(x):
    return random.choice(range(x))
```

I run the service with:

`celery -A tasks worker --loglevel=info --beat -E`

And then flower with:

`celery -A tasks flower --port=5555`

The tasks are running correctly, I can see in the logs, also on flower web, the processed ones show up. However for scheduled I was expecting to see that there are tasks scheduled: one in 10 seconds, one in 100 seconds, and one on Monday morning, etc

Am I missing something?

<img width="1123" alt="screen shot 2017-09-25 at 17 30 39" src="https://user-images.githubusercontent.com/7014744/30816820-4eb18460-a217-11e7-9ea0-9f35a1e0f0a5.png">

**Comment by jheld** [comment]
@skamsie Unless I'm mistaken, `beat` will actually schedule the tasks (based on your requirements) at the time closest to the delta/cron that you have specified. That is, they aren't actually "schedule" in the traditional `celery` sense. They're sitting in `beat`'s internal scheduler logic and are only `enqueued` once `beat` sees that they need to be. Now, if your task in question _also_ happened to have been called/defined with an `eta` or `countdown` argument, then as soon as `beat` schedules them, they should appear in the `Scheduled` section.

**Comment by ShaheedHaque** [comment]
To expand on what jheld mentioned, it turns out that periodic != scheduled and I have opened [an issue against Beat for this](https://github.com/celery/django-celery-beat/issues/126)...
