### ISSUE TITLE
Add "worker.alive" via api/workers

### ISSUE THREAD

**Issue by morphyno** [mher/flower#745]
I'm writing a little client utility that talks directly to flower via REST. I would like to display whether workers are active or nonactive, much akin to the flower dashboard display of "online/offline". However, it seems "worker.alive" is not exposed in the JSON output of /api/workers. Right now, I have to query each worker directly to see they are online or offline, this is a very slow process for large number of workers (if I push simultaneous number of REST calls via pool, I can actually crash the flower server)

**Comment by mher** [comment]
There are no plans to work on this feature at the moment until someone decides to contribute to the project.
