### ISSUE TITLE
results of queued tasks not shown in monitor

### ISSUE THREAD

**Issue by craynic** [mher/flower#752]
celery backend is rabbitmq. result backend is redis.

steps:

1. stop all workers
2. apply a task
3. I can see a rise in "queued tasks"
4. start a worker, the worker executes the task
5. I can see a fall in "queued tasks", but no change in "succeeded tasks" or in "failed tasks"

celery==4.1.0
flower==0.9.2
rabbitmq 3.6.12-1
redis 4.0.2-1

**Comment by DomHudson** [comment]
Also having this issue with RabbitMQ queue and Django-db backend. The ajax requests are returning a `200` response but just with no data in. The dashboard shows correct stats but the monitoring graphs are empty.

![screenshot from 2017-11-24 14-56-52](https://user-images.githubusercontent.com/10864294/33215469-cd74f608-d127-11e7-9ff1-3a8f4c669e45.png)


![screenshot from 2017-11-24 14-57-02](https://user-images.githubusercontent.com/10864294/33215475-d11f94b6-d127-11e7-8045-0a344d624177.png)

**Comment by craynic** [comment]
Yes I also use django-db backend with Django 1.10.

**Comment by adampl** [comment]
Make sure that all workers, flower and rabbitmq use the same timezone. It's not enough to set the timezone in Django config, you also have to set the same timezone in the operating systems, and ensure the clocks are synchronized. Look for warnings about a "substantial drift" at the beginning of Flower logs.

**Comment by DomHudson** [comment]
Ah thank you very much. You're correct.

---

Indeed, this appears in my logs:
```
Substantial drift from ... may mean clocks are out of sync.  Current drift is 194 seconds. 
```

I confirmed the server had the incorrect date and resynced to the internet with
```
sudo ntpdate time.nist.gov
```

I then restarted flower and the charts all appear correctly now.

**Comment by craynic** [comment]
My environment has been destroyed so I could not verify this solution. Since @DomHudson has seen this fixed, I will close this issue. Thank you all.
