### ISSUE TITLE
Celery flower command hanging

### ISSUE THREAD

**Issue by Tecktron** [mher/flower#757]
So I don't know is this is a bug, an issue interacting with Django or something that's already been addressed in a future version, but I just wanted to let you know of my findings.

Basic celery setup on Django using django-results-backend with 'django-db' and Rabbitmq as broker, as  is listed in the celery docs. All on a local Xubuntu 17.10 machine running python 3.6, really nothing fancy.

If I try and run flower and celery together (in the various combinations listed), it seems to hang in the terminal with no output on the console. I can connect to flower on _localhost:5555_, but there are no workers listed:
`celery flower -A myproj`
`celery -A myproj flower`
`celery flower -A myproj worker`
`celery -A myproj flower worker`

If I run celery as such it works fine and I get display in the terminal and everything is fine:
`celery -A myproj worker`

If I then open another terminal and run flower as such, I get no feedback in the terminal (almost seems like it's hanging), but it works since I can hit the _localhost:5555_ and I can see the worker:
`flower -A myproj`

If I run flower without any params, I now get the feedback in the terminal as well:
`flower`

Sure, the obvious workaround is to run them separately (be nice not to have too), but seems a bit counter the documentation. I haven't tried adding anything complex or any custom settings yet, this was just my n00bee trial run and couldn't really find any reporting on it. 

If I'm missing something, would love to know what that is.

Cheers.

**Comment by Tecktron** [comment]
Also:
Trying to do anything like `--conf=myproj/flowerconfig.py` breaks with a `KeyError: 'default_modules'` which then goes on to cause a bunch more exceptions.
Passing `--broker_api` doesn't seem to do anything and always using the default (so I cannot change the rabbit user/pass?)

**Comment by shadiakiki1986** [comment]
Just my 2 cents, I ended up running them separately as well. After some thought, it turned out to be a better architecture to run them separately, because there could be multiple instances of the celery workers, but you will always only need one instance of flower.

**Comment by provinzkraut** [comment]
I'm still experiencing this problem after upgrading to Flower 2. I can't get any output when running with `celery --app=... flower`. Are there any updates on this?
