### ISSUE TITLE
Many messages in celeryev.

### ISSUE THREAD

**Issue by akiryliuk** [mher/flower#759]
Hello.
I am use python2 and Django=1.7
I am install flower 0.9.2 and i have problem.
When I start the flower for production. A queue of the kind celeryev.{xxxx-xxxx-xxxx-xxxx}. is created in the rabbit. 
There incoming messages come in the amount of 3000-4000 per second.
The problem is that the flower takes these messages in one thread and does not have time. One core of the processor in 100%

Can I somehow parallelize this process?
Or what other solutions?

**Comment by mher** [comment]
Those queues are being created by amqp backend. Consider using redis as a backend.
