### ISSUE TITLE
When an worker goes offline and than back online flower keep showing it as offline

### ISSUE THREAD

**Issue by seocam** [mher/flower#760]
If I reboot a server which is running workers flower won't show that those workers are back when the server is back online.

**Comment by seocam** [comment]
That does not happen when we are running flower, celery and redis using containers in docker but it does happen when we are running our software in Digital Ocean droplets.

Let me know if there are any other relevant information that could help.

**Comment by cloneluke** [comment]
I have seen this behavior also with celery 4.0.2 and redis 3.2.10

**Comment by echoocking** [comment]
same behavior with celery: 4.0.2, redis: 2.10.5
solve it by update kombu  and redis

pip install kombu --upgrade
pip install redis --upgrade
