### ISSUE TITLE
dashboard has display fail tasks but in the fail page none exists

### ISSUE THREAD

**Issue by yongchao88** [mher/flower#769]
![image](https://user-images.githubusercontent.com/11289655/34666747-c97c654e-f4a0-11e7-9c9c-a0a3112d25bc.png)

/tasks?state=FAILURE return empty table

**Comment by mher** [comment]
Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use StackOverflow.com for general usage questions instead.
