### ISSUE TITLE
Sorting in /api/tasks endpoint

### ISSUE THREAD

**Issue by thanterz** [mher/flower#773]
Hello,

I call /api/tasks?limit=x, but the results are not sorted by timestamp. How can i sort them by timestamp?

Thanks

**Comment by auvipy** [comment]
probably filtering is not supported for this. needs confirmation from @mher, but could you share some more detail?
better test case which is executable?

**Comment by mher** [comment]
flower doesn't sort tasks in `/api/tasks` https://github.com/mher/flower/blob/master/flower/api/tasks.py#L496
