### ISSUE TITLE
Task sorting by runtime incorrectly treats values as strings

### ISSUE THREAD

**Issue by MShekow** [mher/flower#782]
Hi,
ascending/descending sorting of the "runtime" column is not implemented correctly.

An example (how it is done by Flower 0.9.2)
```
...
1041.306
1042.945
1044.915
10442.742
1046.705
...
```
It's quite obvious that it treats runtimes as strings, while they should be treated as floats.

Regards!

**Comment by pbsphp** [comment]
Hi, @MShekow.
Fixed in #712.
