### ISSUE TITLE
Periodic state save to DB

### ISSUE THREAD

**Issue by ghedb** [mher/flower#803]
Currently the only time that the state is written to DB is on SIGTERM.

In a docker setup it can be pretty difficult to ensure that the signal is always received on shutdown. This also means that if something goes wrong, the state is lost.

It would be really useful if instead flower would at least periodically write to db.

**Comment by jienwha88** [comment]
Any updates on this? This is a really useful feature to persist the state instead of having to restart the server to get a backup state
