### ISSUE TITLE
worker status is offline,but it is working in fact.

### ISSUE THREAD

**Issue by leveryd** [mher/flower#806]
Firstly i run command `celery -A tasks status` to look up worker status,it shows

celery@a-1746838028-bddjl: OK
celery@a-1746838028-kd24k: OK
celery@a-1746838028-n4prl: OK
celery@VM_0_7_centos: OK
celery@VM-167-209-ubuntu: OK

Then i look up worker status on flower web ui, it shows that `celery@a-1746838028-bddjl` worker status is offline.

**Comment by eos-13** [comment]
Downgrading gevent to 1.4.0 solved the issue for me
