### ISSUE TITLE
'sql' broker is not supported

### ISSUE THREAD

**Issue by kororo** [mher/flower#808]
Hi there,

How do I set flower to use SQLAlchemy as broker? Once I executed command below, I got error:
'sql' broker is not supported

This is my configuration:
celery flower -A project_name --db=/data/app/flower.db --persistent=True --port=5001 --broker=postgresql+psycopg2://username:password@psql_host/database_name

Thanks

**Comment by rodrigc** [comment]
Try using a newer version of celery:

```
pip install --upgrade celery==4.2.0rc4
```

WIth that version, I was able to use a sql broker:

```
[I 180525 00:56:36 command:139] Visit me at http://0.0.0.0:5555
[I 180525 00:56:36 command:144] Broker: sqla+mysql://airflow:a123@192.168.99.100/airflow
[I 180525 00:56:36 command:147] Registered tasks: 
    [u'celery.accumulate',
     u'celery.backend_cleanup',
     u'celery.chain',
     u'celery.chord',
     u'celery.chord_unlock',
     u'celery.chunks',
     u'celery.group',
     u'celery.map',
     u'celery.starmap']
[I 180525 00:56:36 mixins:224] Connected to sqla+mysql://airflow:a123@192.168.99.100/airflow
```

**Comment by kororo** [comment]
@rodrigc Ah thanks! I will give a shot.

**Comment by rodrigc** [comment]
@kororo actually, I just tried it and seemed to have the same problem, even with with the latest versions of celery and kombu. :(

**Comment by jonashaag** [comment]
SQL brokers have long been deprecated in Celery and I don't think they're going to be supported in flower

**Comment by kororo** [comment]
Thanks all. Closing this ticket.

**Comment by VidJa** [comment]
> SQL brokers have long been deprecated in Celery and I don't think they're going to be supported in flower
I've been using sql brokers with Celery 4.2 using:
CELERY_BROKER_URL="sqla+postgresql://user:pass:dbhost5432/db"
CELERY_RESULT_BACKEND="db+postgresql://user:pass:dbhost5432/db"
without problems. great for small sites with low volumes of tasks running on low grade hardware (solar powered rPI's) where the overhead of running yet another service might be too much for memory limited devices. 
So yes, there still is a need for sql based brokers. (that said, for larger sites use rabbitMQ or Redis alike
