### ISSUE TITLE
Tasks and Monitor tab never show any content

### ISSUE THREAD

**Issue by jkkjonah** [mher/flower#809]
## Description

I started the Flower server on the same machine that my Celery workers live on, it seems to start and connect to Rabbitmq without any issues. When I navigate to the Flower page, everything seems to load fine: the "Dashboard" tab lists all my active workers and the "Broker" tab lists my broker correctly, however the "Tasks" tab only shows the table header w/ no content and the "Monitor" tab only shows the graph titles and no other content (not even empty graphs, it's just the headers and whitespace).

My question is how do I get my active/completed tasks to show up in the "Tasks" tab and how do I get the graphs to show up in the "Monitor" tab? 

Are there any additional debugging steps I should be taking (see **Things I've tried** section)?

## My setup:

- celery===3.1.25
- flower===0.9.2
- broker: RabbitMQ
- reverse-proxy: nginx
- run options:
    - `A myproj.celery:app` <-- Same value I use to run my workers
    - `port 5555` <-- Proxy-ing requests here seems to work
    - `broker=<rabbitmq_broker_url>`   <-- Flower debug log shows that it's able to connect, I also made sure the user has the right tags for rabbitmq management plugin
    - `broker_api=<rabbitmq_management_api_url>`  <-- I can wget this get information
    - `url_prefx=<my_prefix>`   <-- Browser shows all the static assets are being served properly, no load errors
    - `basic_auth=<uname>:<pwd>`  <-- Browser prompts me to enter this and I'm able to access the page w/ the username + pwd conbination
- I have many celery workers and queues all part of the same app. There's always a task being processed at all times, workers never have idle time.

## Things I've tried:

- I tried running flower in debug mode and I didn't see any errors, flower is able to connect to the broker and when I access the tasks page, the page and static assets are served without any drama
- On the flower host machine I'm able to `wget localhost:5555/api/tasks` and it returns a huge JSON file w/ tasks information
- On the celery host machine (same as flower machine) I'm able to `wget <rabbitmq_management_api_url>/api/queues` (and other API endpoints) and get data just fine
- I tried to add `CELERY_SEND_EVENTS = True; CELERY_SEND_TASK_SENT_EVENT = True` to my app settings
- Clearning browser cache

### Edits:
7/18/2018 - Tried clearing browser cache; Upgraded to celery 3.1.25

**Comment by donkopotamus** [comment]
Have you tried alternative browsers?  For example, I've observed the exact same issues in IE11, whereas Firefox will happily show the lists and charts.

**Comment by jkkjonah** [comment]
@donkopotamus I just tried your suggestion on the browsers I had on hand macOS + chrome, safari, firefox and they all behave the same

**Comment by RobotJiang** [comment]
@jkkjonah to clear browser cache, it works for me.

**Comment by zhangchenchen** [comment]
mark, same problem

**Comment by jkkjonah** [comment]
@RobotJiang unfortunately it still does not work for me

**Comment by sposs** [comment]
I've seen similar issues when flower would be started too early, i.e. before the workers are started. I run flower with supervisor. In that case, restarting flower solved the issue. I'm not sure is the 'priority' parameter in supervisor helps as I have autostart=True and some comment (old) on the supervisor forum was stating that the priority was ignored in that case. Anyway, in the worst case, I simply restart flower.

**Comment by mher** [comment]
Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use StackOverflow.com for general usage questions instead.
