### ISSUE TITLE
is flower dead?

### ISSUE THREAD

**Issue by ShalbafZadeh** [mher/flower#817]
@mher  flower is a great project and simply best solution for monitoring celery.
i know this is a open source software and it's not granted to be maintained
if you could shed light on state of project and development plans that would be great

your and other contributors effort is very appreciated

**Comment by mher** [comment]
The project is not in active development. Unfortunately I don't have time to work on it now but it will change in the future. I'm trying to merge ready pull requests. Please vote on important bugs and I will try fix them as soon as possible.
