### ISSUE TITLE
Elasticsearch history backend

### ISSUE THREAD

**Issue by jheld** [mher/flower#818]
@mher hello!

I'm working on a fork of flower which can use elasticsearch to pull the tasks history from, instead of specifically from the event state heap.

I can populate the tasks table, paginate, sort by all of the usual fields, and search by task name.

One of the major issues is that I'm having trouble configuring how to do determine when to or not to use elasticsearch search. For debugging & dev purposes (as a first draft), I want to be able to pass `?es=true` or not true on the URL parameter, and pass that into flower for it to pull from ES or from the usual code path. But, I'm having a problem finding out where to put that code on the JS-side. Could you lead me to the relevant places?

Is this going to end up being an issue with jQuery DataTable?

**Comment by johnarnold** [comment]
Maybe you're over-thinking this -- why not just have a configuration flag to enable elasticsearch for the 'cache' ?

We actually were playing around with separating out the whole event state heap and it's maintenance into a separate process, and access it over a socket.  Once you hit a certain scale point, event processing starts causing user experience issues, and it also seems kinda leaky / there are reliability issues at >1M tasks.

I'd be interested to see your implementation of the event state over elasticsearch, sounds promising.

**Comment by jheld** [comment]
Hey @johnarnold 

Agreed -- we have seen similar response/performance degradation on our system.

I was hoping to be able to switch the backend search implementation on a per-request basis. But if that's too challenging to accomplish in the current implementation, that's fine. I wanted it so I could compare time/performance benchmarks, without having to restart flower. My company has tried to use the persistence mode but we've had bad experience with it -- flower would fail to start because of reading the shelve.

I will open a PR to get some draft feedback. The sending to elasticsearch part will need to be refined for flower. Originally I wasn't sure if this would fit as a piece in flower proper, a flower subcommand, or some external script, but if flower is going to be using the index (configurable of course), then it I think it will be required to be part of flower in some scope. Given that, I've adjusted my initial implementation to call into the sender on event processing -- I'm sure this will be changed, but I wanted to show the general idea.

The schema mapping also will have to be put somewhere else. This really is a WIP.

Additionally, I'm not sure if it makes sense, but I could add in support for the dashboard page to pull from elasticsearch, too. Just not sure if that's the most wise thing for the project. History is one thing, but realtime dashboard -- let me know your thoughts.

**Comment by jheld** [comment]
#821 is the implementation for this issue.
