### ISSUE TITLE
Broker API (RabbitMQ) connection issues with password containing \ (backslash)

### ISSUE THREAD

**Issue by stojan-jovic** [mher/flower#820]
I'm running Flower on separate host in conjunction with RabbitMQ as my broker. This production instance of RabbitMQ, which user contains **\\** in password, makes problems to Flower's connection to broker's API.
This manifests in Flower's UI in the manner that everything works, except I have no any information on _Broker_ tab.

For demonstration purposes, here there are my RMQ credentials:
Usename: **my-user**
Password: **foo\Bar123**

When I started Flower using following command (I encoded my password because of **/** in it):
```
flower --port=5555 --broker=amqp://my-user:foo%5CBar123@localhost:5672// --broker_api=http://my-user:foo%5CBar123@localhost:15677/api/
```
I could not get details on _Broker_ tab (it's empty), followed by errors in the log (on every access to _Broker_ tab):

> [E 180723 13:34:15 broker:77] RabbitMQ management API call failed: HTTP 401: Unauthorized
> [E 180723 13:34:15 broker:78] Make sure RabbitMQ Management Plugin is enabled (rabbitmq-plugins enable rabbitmq_management)

Also, in RabbitMQ logs I have:

> 2018-07-23 13:34:15.711 [warning] <0.2212.0> HTTP access denied: user 'my-user' - invalid credentials

Found many similar issues, including [this one on StackOverflow](https://stackoverflow.com/questions/26637607/celery-and-flower-nothing-in-broker-tab) (which is the most relevant to my problem), but neither one provided solution that works for me (and yeah, my RabbitMQ Management Plugin is enabled).

After many hours of investigation, I figured out that problem is in the way how I provided password for broker's API - the only way to make it working with this kind of passwords is to leave empty credentials, i.e. **when I start Flower with command as follows everything working fine**:
```
flower --port=5555 --broker=amqp://my-user:foo%5CBar123@localhost:5672// --broker_api=http://localhost:15677/api/
```

What here happening is that Flower will implicitly take credentials provided for accessing broker itself (if we do not pass credentials explicitly to broker's API) and that's why this working.

But, this leads me to conclusion that Flower does not handles credentials in the URL at the same way for broker itself (`--broker`) and broker's API (`--broker_api`), so, this is probably a bug?!

I take a quick look at the Flower's source code for brokers (in my case, `RabbitMQ` class is interesting one), and probably there is some problem in `queues` method and how it handles credentials (using `urllib` and `urlparse` libs), but have no time for deeper research.

Important thing to mention is that everything working fine if I change my password so that there is no **\\** in it (regardless of whether we use the first or second command mention above).
Also, I faced this behavior with different users and different passwords (which contains **\\**).

My environment for Flower:
```
amqp (1.4.9)
anyjson (0.3.3)
Babel (2.3.4)
billiard (3.3.0.23)
celery (3.1.24)
flower (0.9.0)
kombu (3.0.36)
pip (8.1.2)
pytz (2016.7)
setuptools (18.2)
tornado (4.2)
```

RabbitMQ instance is version 3.7.6 (and it's on separate host, as I mentioned earlier).

**Comment by auvipy** [comment]
did you get any solution for this?

**Comment by stojan-jovic** [comment]
Not use `\` in password. :)
I think that it's a bug, so I do not think that there is some permanent solution. However, I had no time to further investigate (except this what I described in the first post).

**Comment by auvipy** [comment]
@mher looking for your insights

**Comment by mher** [comment]
@auvipy were you able to reproduce?

**Comment by nirvana-msu** [comment]
I've had exact same issue (in my case it was the character `#` in the password, properly URL-encoded). Leaving out credentials from `broker_api` entirely solved the problem - exactly as the first post suggests.
