### ISSUE TITLE
RabbitMQ management API call failed: Stream closed error on accessing Broker tab

### ISSUE THREAD

**Issue by viiicky** [mher/flower#830]
I am running flower by the command:
`celery flower --broker=amqp://<username>:<password>@localhost:5672/<virtualhostname> --broker_api=http://<username>:<password>@localhost:5672/api/`

I can see the tasks info, the worker info etc.
But as soon as I go to `/broker`, I see the error in console:
`RabbitMQ management API call failed: Stream closed`
and the UI remains blank with no data.

Interestingly whenever I go to `/monitor`, I see the same error in the console, however, after a couple of seconds graphs gets to load on the monitor page.

But for broker page nothing happens even after waiting.

The broker I am using is `RabbitMQ` and the management plugin is already enabled for the broker by the command:
`rabbitmq-plugins enable rabbitmq_management`

Why am I getting the Stream closed error for the broker page?

Associated stackoverflow question: https://stackoverflow.com/questions/51785636/how-to-see-broker-information-when-using-flower

**Comment by tlinhart** [comment]
@viiicky I've just posted the [answer](https://stackoverflow.com/questions/51785636/how-to-see-broker-information-when-using-flower/54822890#54822890) to SO question, you may check if it's relevant.
