### ISSUE TITLE
Flower produces invalid wheels

### ISSUE THREAD

**Issue by jaraco** [mher/flower#833]
Following on the heels of #674, flower has an additional issue where if a wheel is built on Python 2, it is invalid on Python 3, and vice-versa, due to the [conditionally-declared dependency on futures](https://github.com/mher/flower/blob/2f674aa4ed4f11243822869b70027c0b6f07a61c/setup.py#L49).

There are two possible approaches:

1. Remove the [universal wheel declaration](https://github.com/mher/flower/blob/2f674aa4ed4f11243822869b70027c0b6f07a61c/setup.cfg#L2), so that any wheels produced aren't considered compatible with both Python 2 and Python 3.

2. Use environment markers to declare the futures dependency on Python 2 only.

The former is less invasive, but the latter is probably preferable.

**Comment by eblume** [comment]
(Also posted in the PR)

Hi, this just found its way downstream to the `poetry` package manager, here: https://github.com/sdispater/poetry/issues/752

Any word on when this might go live?

**Comment by newearthmartin** [comment]
any idea when this will go live? 
I have to comment flower from my `requirements.txt` otherwise it breaks my python3 setup every time I do `pip install`
