### ISSUE TITLE
Add support of exporting metrics to Prometheus

### ISSUE THREAD

**Issue by Linux-oiD** [mher/flower#835]
**Prometheus** - one of the widespread monitoring solution. The key concept of it - scrapping metrics via HTTP.
**Flower** - de facto standard web management and monitoring tool for Celery.

There are some Prometheus metrics exporters for Celery but each of them require to run separate service for collect and expose metrics from broker.
Flower already has Monitor tab and will be great to have ability to export collected Celery's metrics via separate HTTP endpoint to Prometheus.

Prometheus text protocol description: https://prometheus.io/docs/instrumenting/exposition_formats/
Best practices for metrics naming: https://prometheus.io/docs/practices/naming/

**Comment by ssikyou** [comment]
This is great, any plan to supoort it?

**Comment by mher** [comment]
Added prometheus integration https://github.com/mher/flower/commit/145652715ba993c1ca116f3a001658ce7d2d0f4d

**Comment by Joe-Heffer-Shef** [comment]
This was added just as I was searching for this feature :D

**Comment by modbender** [comment]
No documentation on this.
