### ISSUE TITLE
--auto_refresh=False does not work

### ISSUE THREAD

**Issue by yaomengsi** [mher/flower#836]
Run flower `sh` script with followed line:
```bash
nohup flower --auto_refresh=False -A $PROJECT_NAME --url_prefix=flower &
```

But dashboard still auto refresh.

**Comment by zwg-zero** [comment]
Maybe you can try --auto-refresh=False

**Comment by ohyang326** [comment]
Me too, I use supervisor

**Comment by ohyang326** [comment]
any help? I still have the same problem
