### ISSUE TITLE
API not working when using reverse proxy

### ISSUE THREAD

**Issue by cdvv7788** [mher/flower#839]
Following the provided instructions, I set up my reverse proxy in nginx:

```
    location "/flower/" {
        rewrite ^/flower/(.*)$ /$1 break;
        proxy_pass http://localhost:5590;
        proxy_set_header Host $host;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        auth_basic "Restricted";
        auth_basic_user_file "/etc/nginx/.htpasswd";
    }
```

The app works as expected. However the api does not work at /flower/api/ (returns 404).
I am starting flower as follows:
`celery flower -A config --port=5590 --url_prefix=flower --address=localhost`

The app works correctly. Without the rewrite it stops working.
Do I need to do something else to enable the API? Am I missing some configuration?

**Comment by mher** [comment]
It is a limitation of the current reverse proxy implementation

**Comment by mher** [comment]
Try to update to the latest version. It should work with 0.9.5
