### ISSUE TITLE
Feature request: dashboard refresh

### ISSUE THREAD

**Issue by dejlek** [mher/flower#840]
We have Celery cluster on AWS that automatically scales up and down so quite often I have to restart Flower because it has too many offline Celery nodes in the dashboard.
It would really be useful if we could specify how often we want to remove offline nodes from the dashboard with something like `dashboard_refresh = 60  # (minutes)`

**Comment by bstiel** [comment]
I've added a new option and created a PR: https://github.com/mher/flower/pull/852.

**Comment by mher** [comment]
Implemented in https://github.com/mher/flower/pull/852
