### ISSUE TITLE
Flower can't connect to RabbitMQ over SSL

### ISSUE THREAD

**Issue by cabrinha** [mher/flower#843]
I'm starting flower with the following command:
```
flower --broker=amqps://user:password@rabbitmq_hostname:5671/vhost --broker_api=http://user:password@rabbitmq_hostname:15672/api/ --port=5555
```

Then, when I click on the "broker" tab, I get an error:

```
$ flower --broker=amqps://user:password@rabbitmq_hostname:5671/vhost --broker_api=http://user:password@rabbitmq_hostname:15672/api/ --port=5555
[I 180927 12:13:26 command:139] Visit me at http://localhost:5555
[I 180927 12:13:26 command:144] Broker: amqps://user:**@rabbitmq_hostname:5671/vhost
[I 180927 12:13:26 command:147] Registered tasks:
    [u'celery.accumulate',
     u'celery.backend_cleanup',
     u'celery.chain',
     u'celery.chord',
     u'celery.chord_unlock',
     u'celery.chunks',
     u'celery.group',
     u'celery.map',
     u'celery.starmap']
[I 180927 12:13:27 mixins:224] Connected to amqps://user:**@rabbitmq_hostname:5671/vhost
[W 180927 12:16:43 web:1667] 404 GET /broker (172.x.x.x): 'amqp' broker is not supported
```

The only thing that works for me is appending "?ssl=true" to the end of the broker URL

```
flower --broker=amqp://user:password@rabbitmq_hostname:5671/vhost?ssl=true
```

**Comment by michaelfresco** [comment]
Thanks Cabrinha! 

It took me a while to figure this one out! That last line you posted is really golden.

**Comment by jsnb** [comment]
Thank you! This was the problem I was having connecting to a amqp broker over ssl.

For others finding this thread I want to emphasize the change in the connection string is not only adding the **ssl=true** arg but also changing the transport scheme from **amqps** to **amqp**.

does not work:
```
flower --broker=amqps://user:password@rabbitmq_hostname:5671/vhost
```

works:
```
flower --broker=amqp://user:password@rabbitmq_hostname:5671/vhost?ssl=true
```

I had to dig in to see that `amqps` is not a valid scheme in the flower code here:
https://github.com/mher/flower/blob/master/flower/utils/broker.py#L241

**Comment by TildeWill** [comment]
@mher is there a reason Flower doesn't support the amqps protocol? Can it be added?
