### ISSUE TITLE
Can I restart a Celery worker with supplied --concurrency value.

### ISSUE THREAD

**Issue by viiicky** [mher/flower#846]
I have my worker already running with default `--concurrency` setting. i.e the number of processes is equal to the number of cores present in the memory:
`- *** --- * --- .> concurrency: 4 (prefork)`

`4` in my case. Is there a way, by which I can restart this worker instance setting the concurrency value as 1?

**Comment by mher** [comment]
You can increase the pool size without restarting the worker http://docs.celeryproject.org/en/latest/userguide/workers.html#autoscaling
