### ISSUE TITLE
WebPage Not Responding When Clicking the Worker name in WebUI

### ISSUE THREAD

**Issue by sshanmuga** [mher/flower#851]
In the web UI, While Clicking one of the Worker Name, WebUI does not take to the respective page rather it is unresponsive.

**Worker Name    | Status | Active | Processed | Failed | Succeeded | Retried | Load Average
celery@abc.com| online |    0      |        2        |     0     |      2           |      0     |  0.06, 0.1, 0.09
celery@bcd.com| online |    0      |        3        |     0     |      3           |      0     |  0.06, 0.1, 0.09**

**Using below packages** 
apache-airflow=1.10.0
Celery=4.1.1
librabbitmq=2.0.0

**flower log:**
```
[2018-10-31 09:09:34,563] {settings.py:174} INFO - setting.configure_orm(): Using pool settings. pool_size=5, pool_recycle=3600
[2018-10-31 09:09:34,983] {__init__.py:51} INFO - Using executor CeleryExecutor
[I 181031 09:09:35 command:139] Visit me at http://my-flower-host:5555
[I 181031 09:09:35 command:144] Broker: amqp://mquname:**@mqhost:5672/mqvhost
[I 181031 09:09:35 command:147] Registered tasks:
    [u'celery.accumulate',
     u'celery.backend_cleanup',
     u'celery.chain',
     u'celery.chord',
     u'celery.chord_unlock',
     u'celery.chunks',
     u'celery.group',
     u'celery.map',
     u'celery.starmap']
[I 181031 09:09:35 mixins:224] Connected to amqp://mquname:**@mqhost:5672/mqvhost
```

**Comment by jeffhu1** [comment]
+1

**Comment by kcrebound** [comment]
same problem, python 2.7, flower 0.9.2, celery 4.2.1 
on flower 0.9.1 it's work

**Comment by danielcwj16** [comment]
got the same problem here
flower 0.9.2
celery 4.2.1

**Comment by andyewen** [comment]
Same problem here and I've noticed if I navigate to `/api/workers` I just get an empty JSON object even though my worker appears in the dashboard UI.

**Comment by mher** [comment]
This issue is fixed in the master version
