### ISSUE TITLE
specify retry policy on async-apply api call

### ISSUE THREAD

**Issue by sloev** [mher/flower#858]
Hi i want to be able to specify retry policy like described [here](http://docs.celeryproject.org/en/latest/userguide/calling.html#calling-retry):

```
add.apply_async((2, 2), retry=True, retry_policy={
    'max_retries': 3,
    'interval_start': 0,
    'interval_step': 0.2,
    'interval_max': 0.2,
})
```

how can i do this with flower api `async-apply` when calling the api?

**Comment by jheld** [comment]
I think it is possible already.

For instance, to specify a countdown, you can add `"countdown": 35` to the JSON payload. All of the task invocation options sit as top level options, while args (for instance) are buried under `"args"`.
