### ISSUE TITLE
No links to workers / no tasks

### ISSUE THREAD

**Issue by jmdacruz** [mher/flower#860]
Environment:
* Celery 4.2.1
* Flower 0.9.2 & [1.0.0-dev](https://github.com/mher/flower/commit/3bcce81fce53064cbd0ba2797eb7933c77690fdc) (same symptom in both versions)
* Using `RabbitMQ` as broker and `memcached` as results backend
* Running workers and flower on separate docker containers (Kubernetes)

Behavior:
* The `Dashboard` tab shows the active workers, but there are two weird issues: 1) The workers are not "clickable" (that is, they have no links to the worker detail page), and 2) The `Status` column shows a value of `True` instead of the typical `online` (green) / `offline` (red)
  * I can manually build the URL for the worker's detail page (navigating to `/worker/{worker_name}` and the info is there, only the link is missing on the dashboard
![image](https://user-images.githubusercontent.com/1178370/49052377-69fc3d80-f1a0-11e8-857c-78b5328fcd27.png)
* The `Tasks` tab is empty, as if no tasks were executed. However, I can get the result of a task using the flower task API (if I know the task ID).

I don't see anything that looks suspicious on the flower logs (using both `--debug` and `--logging=debug`), but I might be missing something. I'm sure this is related to my environment or configuration, since I'm able to get this to work using plain `docker-compose` (following a recipe loosely based on https://github.com/tonywangcn/docker-cluster-with-celery-and-rabbitmq, just adding `memcached`). Any suggestions/pointers are much appreciated.

**Comment by liaoshuren** [comment]
I meet the same problem , any one can help us? thx

**Comment by puer633** [comment]
Mee,too

**Comment by sergei-maertens** [comment]
Same problem, I've managed to pin it down to the `--url_prefix` option. If I use that (which I'm doing because of my ingresses), the problems arise. Without that option, it works as expected.

Looks like some part of the JS is not running/executing when `--url_prefix` is used.

**Comment by jmdacruz** [comment]
Closing, as @sergei-maertens's recommendation works just fine: Trailing slashes on the `--url_prefix` parameter will break the UI, so they need to be avoided.
