### ISSUE TITLE
Redis broker monitors events in other dbs than broker

### ISSUE THREAD

**Issue by arthurio** [mher/flower#863]
I'm not sure if I'm missing something, but for some reason our flower instance seems to be able to monitor tasks from workers using a shared redis instance but not using the same db.

Setup
====
```
celery==3.1.17
flower==0.9.2
redis==2.9.1
```

We have multiple environments using each a different db on the same redis instance. Flower's broker is  `redis://localhost:6379/2`. 

Expected:
----------

I can see only data about the db 2.

Actual:
-------

In the dashboard tab, I can see workers not using that db.
In the tasks tab, I can see tasks that were enqueued in other dbs.

**Comment by pitikdmitry** [comment]
Hi, this setup works correct for me, I think you have a mistake somewhere.
I have this problem in connecting to sentinel and I can't solve it :( ex: sentinel://localhost:26379/2
