### ISSUE TITLE
when i deploy flower container "mher/flower" --persistent=True the container fails. my celery version-4.1.1

### ISSUE THREAD

**Issue by Lokcm** [mher/flower#873]
when i deploy flower container "mher/flower" --persistent=True the container fails. my celery version-4.1.1

**Comment by Lokcm** [comment]
But it works fine without persistent=True

**Comment by jheld** [comment]
Our team also had issues with persistent mode (flower crashing on startup).

In the end, we built in support for https://github.com/mher/flower/pull/821 . Work is still needed for it to be merged, but we rely on it daily and it works great. If this looks like a reasonable alternative, I can help write up setup/integration instructions.

**Comment by jheld** [comment]
Which version of python?

**Comment by mher** [comment]
Fixed in 0.9.5
