### ISSUE TITLE
Google+ deprecated: change urls

### ISSUE THREAD

**Issue by NotSqrt** [mher/flower#876]
Hello

Google+ gets deprecated.

Changes to do:
* replace `https://www.googleapis.com/plus/v1/people/me` by `https://www.googleapis.com/userinfo/v2/me` https://github.com/mher/flower/blob/29c8e6f4481bdeb2189ac1ef4b1f8b712d3397af/flower/views/auth.py#L50
* use tornado >=5.0 : https://github.com/tornadoweb/tornado/commit/f64d44197de0667754f3e3de5dd54709233a019d

probably other fixes are needed.

Thanks !

**Comment by NotSqrt** [comment]
Those modifications seem enough to make it work !

**Comment by chadawagner** [comment]
There was some reason flower did not work with tornado 5 (see #784)

**Comment by NotSqrt** [comment]
Oh, ok. My pull request adjusts the requirements from `tornado>=4.2.0,<6.0.0` to `tornado>=5.0.0,<6.0.0`, so tornado 5 was already allowed.

**Comment by chadawagner** [comment]
Oh great. Ok, sorry I didn't have time to check whether that had been fixed already. Thanks!
