### ISSUE TITLE
Babel Required?

### ISSUE THREAD

**Issue by cjwright83** [mher/flower#881]
Was just looking through the code and noticed that Babel only seems to be getting used once to format a time delta into the `us_EN` locale. Seems very little to be adding a weighty (26MB) i18n dependency. Is there any alternative?

https://github.com/mher/flower/blob/master/flower/utils/template.py#L45

**Comment by denizdogan** [comment]
We should easily be able to use [humanize](https://github.com/jmoiron/humanize) for this instead.
