### ISSUE TITLE
Any plans for a new release? 

### ISSUE THREAD

**Issue by marmccor** [mher/flower#883]
Hi folks, are there any plans for a new release of flower anytime soon? 

In particular, i'm interested in the following changes:
 - https://github.com/mher/flower/pull/842

We are running into issues when flower is installing a later tornato version (6.x), so the fix above should resolve that. 

I'd rather not install from master on production environments :)

**Comment by iROCKBUNNY** [comment]
Hopefully next week~ see https://github.com/mher/flower/issues/878#issuecomment-469195853

**Comment by mher** [comment]
A new flower version has been uploaded to pypi
