### ISSUE TITLE
Deploying on heroku

### ISSUE THREAD

**Issue by okomarov** [mher/flower#884]
Has anyone managed to deploy flower to Heroku and is willing to share the procfile settings? 

I am using:
```
flower:  celery -A project.app:celery_app flower --PORT=$FLOWER_PORT --broker=$BROKER_URL --basic_auth=$FLOWER_BASIC_AUTH
```

then try the `heroku.app.url:FLOWER_PORT` and it hangs there forever, as in not routed or firewalled.

**Comment by carlosfunk** [comment]
You can only have one web process in Heroku so I have a separate app with only celery, redis and flower in the requirements.txt, and the Procfile contains:

`web: flower --port=$PORT --broker="$BROKER_URL"`

I set `BROKER_URL` in the config to match the REDIS_URL of my app running Celery, along with the other `FLOWER_` setttings for authentication.

**Comment by okomarov** [comment]
Thanks for getting back. 

Additionally, I realized I can simply attach to any db from a local instance of flower which helps with debugging although it is not a solution for production.
