### ISSUE TITLE
Installing from PYPI and setup installs tornado 6.0.1

### ISSUE THREAD

**Issue by manmohana** [mher/flower#886]
When installing flower==0.9.2 from PYPI its installing tornado-6.0.1.
I see in the code base we have the condition to install tornado version less than 6.0.0.
When trying to install from git repo code base it seems to be fine.
Thanks.

**Comment by Kub-AT** [comment]
In requirements of release 0.9.2 there is "tornado>=4.2.0" 
https://github.com/mher/flower/blob/v0.9.2/requirements/default.txt

So you should add
tornado>=4.2.0,<6.0.0
in you project or install flower via git repo.

And maintainer of flower should release new flower with requirements fix but i don't see it coming.

**Comment by mher** [comment]
A new flower version has been uploaded to pypi
