### ISSUE TITLE
Is there a way to limit the number of redis connections

### ISSUE THREAD

**Issue by okomarov** [mher/flower#888]
Is there a way to limit the number of redis connections?

I am looking for an equivalent of celery's [redis_max_connections](http://docs.celeryproject.org/en/latest/userguide/configuration.html#redis-max-connections) or does flower inherit that when launched through celery?

My limits come from heroku which puts a max of 20 redis connections on the free redis instance.

**Comment by ilyakatz** [comment]
Curious about this too.

**Comment by mher** [comment]
flower uses celery inspect methods to get info from broker. Celery redis config option should work

**Comment by aparakian** [comment]
Hi.
Sorry to reopen this old issue but I wonder what setup did you guys end up using. I tried every possible celery option and I can't manage to reduce the number of redis clients used by flower. It keeps on using 23 clients and I have no idea what could help reduce this number.
Thanks for your help!

**Comment by thomaskoller** [comment]
Did anyone find a solution for this? Or is it no possible?

**Comment by bddppq** [comment]
I've run into the same situation, ended up solving the issue by doing this https://github.com/bddppq/flower/commit/87965e0aada3b6d99e201b38649f960d026ad43e
