### ISSUE TITLE
All options are ignored if passing "-l debug" as first option to flower

### ISSUE THREAD

**Issue by asfaltboy** [mher/flower#892]
This happened to me; and may happen easily to others who, like me, blindly copy pasted the options from another celery command... Here is a command that fails to set up on port 5556 (rather sets on port 5555)

```bash
$ celery -A myapp flower -l debug --port=5556 --basic_auth=user1:password 1

# in another shell
$ curl localhost:5556
curl: (7) Failed to connect to localhost port 5556: Connection refused
```

Clearly assignment to port 5556 was not happening (flower was listening 5555 here). And when I remove the `-l debug`, all is well again:

```bash
$ celery -A myapp flower --port=5556 --basic_auth=user1:password1

# in another shell
$ curl localhost:5556
Access denied
```

Interestingly enough, changing `-l debug` to something like `-l info` doesn't break the other options. I'm not sure `-l` is a valid shorthand for flower or not, according to `--help` only long options are valid...
Unfortunately I don't know enough about tornado.options, celery options or how flower users both of these to pass args. Luckily it is easy to reproduce.

Another thing I would fix while at this, is the ability to pass invalid options to flower, e.g:

```bash
$ celery -A myapp flower --foo=bar
```

The above probably causes many people frustration, and leads to bugs like this "-l debug" issue... I have a gut feeling that some other "this option doesn't work for me" bugs in this repo might could be related to this, so this could be an easy "combo" fix for whoever squashes it 🐛🐛🐛!!

**Comment by mher** [comment]
I'd recommend using `flower` command directly instead of `celery flower`
