### ISSUE TITLE
Monitor page: Graphs for 'Succeeded tasks', 'Failed tasks' and 'Task times' are empty 

### ISSUE THREAD

**Issue by charleshan** [mher/flower#897]
Reference: #257, #123

It looks like the Monitor page doesn't display the graphs for 'Succeeded tasks', 'Failed tasks' and 'Task times' if we use a timezone with celery and have flower on another machine.

`flowerconfig.py` with the following didn't solve the issue as hinted in the other ticket.
```
CELERY_ENABLE_UTC  = True
CELERY_TIMEZONE = 'Vancouver/America'
```

**Comment by yanwencheng** [comment]
i have the same problem
celery:4.4.0
flower:1.0.0

**Comment by mher** [comment]
Monitor page is deprecated, use Prometheus instead.
