### ISSUE TITLE
Flower displaying offline workers

### ISSUE THREAD

**Issue by calebbredlow** [mher/flower#900]
I'm seeing an issue where I have 6 workers, three online and 3 offline, the 3 online is to be expected, but what isn't expected are the offline ones, and the weird behavior I'm seeing is that some off the offline workers disappear, then reappear a few seconds later.   I've tried clicking on them to get their status, but get back the error that they don't exist.  Is there something I'm missing for the configuration?  I have another service that has flower celery all set up the same way and I'm not seeing this issue there.

**Comment by yogevyuval** [comment]
Happens to me as well.

**Comment by jheld** [comment]
I am uncertain why you're seeing flickering offline workers.

How often does this occur? Any debug and system info you'd be willing to share?

**Comment by jheld** [comment]
Unsure if related (we may need more info), but PR #852 may help your issue.
