### ISSUE TITLE
'Unknown worker' error with celery==4.3.0

### ISSUE THREAD

**Issue by volkerp** [mher/flower#909]
Flower shows the list of workers and their states in the dashboard, but clicking on one results in an _Unknown worker ..._ error.

dependencies when the error occurs
```
amqp==2.5.0
billiard==3.6.0.0
celery==4.3.0
kombu==4.6.1
redis==3.2.1
vine==1.3.0
```

dependencies when working correctly
```
amqp==2.2.2
billiard==3.5.0.3
celery==4.2.1
kombu==4.2.0
redis==3.2.1
vine==1.1.4
```

Regards

**Comment by volkerp** [comment]
Futher digging into the dependencies shows that kombu is the culprit. 
The error occurs when
```
kombu>=4.6.0
```

**Comment by Kub-AT** [comment]
The same here with kombu==4.6.1,
upgrade to 4.6.3 or downgrade to < 4.6 
helps to me

**Comment by rubimpassos** [comment]
Upgrading kombu to 4.6.3 solves this issue for me.
Thanks @Kub-AT

**Comment by Old-Su** [comment]
Downgrading kombu to 4.2.1 solves this problem.
Thanks. @Kub-AT

**Comment by GoTop** [comment]
Suddently, I got this 'Unknown worker' error in Flower too.

and when I run Flower in console,  it said "inspect method failed":
```
[I 190627 13:20:38 mixins:224] Connected to redis://localhost:6379//
[W 190627 13:20:44 control:44] 'stats' inspect method failed
[W 190627 13:20:44 control:44] 'active_queues' inspect method failed
[W 190627 13:20:44 control:44] 'registered' inspect method failed
[W 190627 13:20:44 control:44] 'scheduled' inspect method failed
[W 190627 13:20:44 control:44] 'active' inspect method failed
[W 190627 13:20:44 control:44] 'reserved' inspect method failed
[W 190627 13:20:44 control:44] 'revoked' inspect method failed
[W 190627 13:20:44 control:44] 'conf' inspect method failed
```
and it is my package version:
```
kombu 4.2.1
redis 2.10.6
celery 4.2.1
flower 0.9.3
```

**Comment by stormlifter** [comment]
I get this when using the Dockerfile, freshly pulled and then started the dockerfile and got the exact same set of errors
```
[I 190716 01:18:43 command:139] Visit me at http://localhost:8888
[I 190716 01:18:43 command:144] Broker: redis://redis:6379/0
[I 190716 01:18:43 command:147] Registered tasks: 
    ['celery.accumulate',
     'celery.backend_cleanup',
     'celery.chain',
     'celery.chord',
     'celery.chord_unlock',
     'celery.chunks',
     'celery.group',
     'celery.map',
     'celery.starmap']
[I 190716 01:18:43 mixins:224] Connected to redis://redis:6379/0
[W 190716 01:18:43 state:113] Substantial drift from celery@c2b1bafaf529 may mean clocks are out of sync.  Current drift is
    14400 seconds.  [orig: 2019-07-16 01:18:43.905048 recv: 2019-07-15 21:18:43.904256]
    
[W 190716 01:18:46 control:44] 'stats' inspect method failed
[W 190716 01:18:46 control:44] 'active_queues' inspect method failed
[W 190716 01:18:46 control:44] 'registered' inspect method failed
[W 190716 01:18:46 control:44] 'scheduled' inspect method failed
[W 190716 01:18:46 control:44] 'active' inspect method failed
[W 190716 01:18:46 control:44] 'reserved' inspect method failed
[W 190716 01:18:46 control:44] 'revoked' inspect method failed
[W 190716 01:18:46 control:44] 'conf' inspect method failed
```

**Comment by sknzl** [comment]
Getting same error here

```
[I 190820 13:20:38 mixins:229] Connected to 
 redis://localhost:6379//
[W 190820 13:20:41 control:44] 'stats' inspect method failed
[W 190820 13:20:41 control:44] 'active_queues' inspect method failed
[W 190820 13:20:41 control:44] 'registered' inspect method failed
[W 190820 13:20:41 control:44] 'scheduled' inspect method failed
[W 190820 13:20:41 control:44] 'active' inspect method failed
[W 190820 13:20:41 control:44] 'reserved' inspect method failed
[W 190820 13:20:41 control:44] 'revoked' inspect method failed
[W 190820 13:20:41 control:44] 'conf' inspect method failed
```

With following versions
```
kombu==4.6.4
redis==3.3.8
celery==4.3.0
flower==0.9.3
```

Any suggestions?

**Comment by xenozauros** [comment]
Got the same issue. 
Using docker. Redis brocker

```
kombu==4.6.3
redis==3.3.7
celery==4.3.0
flower==0.9.3
vine==1.3.0
```

**Comment by adv27** [comment]
I got the same problem, downgrading the `kombu` from `4.6.4` => `4.6.3` solve it

**Comment by Kub-AT** [comment]
https://github.com/celery/kombu/issues/1081

**Comment by elraro** [comment]
Hello,

how can i downgrade kombu? I don't find dependence

Thank you! Regards,

**Comment by cdknorow** [comment]
kombu 4.6.4 also seems to be breaking the app.control.inpsect() method for celery. It just doesn't find any workers at all. Downgrading fixes this.

**Comment by 363568233** [comment]
flower 0.9.3
celery 4.3.0
kombu 4.6.5  also has this issue

**Comment by metalshanked** [comment]
The issue seems to be fixed in the latest version of kombu 4.6.6

**Comment by frost-nzcr4** [comment]
Latest celery==4.4.0rc4, kombu==4.6.6 & flower@master a7f8837a9691a8de376989830b03c2daacf537b7 works again

**Comment by Hammit** [comment]
amqp==2.5.2
billiard==3.6.1.0
celery==4.3.0
flower==0.9.3
kombu==4.6.7
redis==3.2.1
vine==1.3.0

Working for me

**Comment by smsajjadzaidi** [comment]
I am facing this same unknown celery worker error
I tried downgrading kombu to 4.2.0 and upgrading it to 4.6.11 as well
But these did not work out for me
Current stack:
celery = 4.4.0
kombu = 4.6.11
redis = 3.3.11
flower==0.9.5
amqp==2.6.1
vine==1.3.0
billiard==3.6.1.0

**Comment by avlm** [comment]
downgrading didn't work for me either.
currently using:

celery==4.4.7
kombu==4.6.11
flower==0.9.7
amqp==2.6.1
billiard==3.6.3.0

**Comment by Praneethvvs** [comment]
I still see this  "Unknown worker" error. I am trying to use mher/flower docker image.  
`version: '3.7'

services:

  prediction:
    image: ${REGISTRY}:${TAG}
    restart: unless-stopped
    command:  uvicorn app.api.api_main:prediction_service_api --reload --workers 1 --host 0.0.0.0 --port 80
    ports:
      - 80:80
      
  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - 6379:6379
 
  notifier:
    image: ${REGISTRY}:${TAG}
    container_name: notifier
    command: celery -A app.celery_worker.celery worker --concurrency=1  --loglevel=info
    depends_on:
      - prediction
      - redis
      
  flower:
    image: mher/flower
    container_name: flower
    command: celery flower --persistent=True
    environment:
      - "CELERY_BROKER_URL=redis://redis:6379/0"
      - "FLOWER_PORT=8888"
    ports:
      - 8888:8888
    depends_on:
      - redis









`
