### ISSUE TITLE
Celery with cloudamqp

### ISSUE THREAD

**Issue by general03** [mher/flower#910]
I can't lanch the Floor server since I update my `broker` variable with url of my Cloudamqp Little Lemur instance
So I add the `broker_api` option but without success

I don't have any issue when I launch the server 
```
pipenv run celery flower \
    --app=project.taskapp \
    --broker="${CELERY_BROKER_URL}" \
    --broker_api="https://user:pwd@bulldog.rmq.cloudamqp.com:443/api" \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
```

Thanks

**Comment by mher** [comment]
cloudamqp support may help to debug the issue
