### ISSUE TITLE
celery backend configuration in flower

### ISSUE THREAD

**Issue by harsh2205** [mher/flower#912]
I'm using celery to monitor the queue . but I'm facing some issues related to the backend 
i am using flower , when celery is running , it works properly, but when restart celery it deletes the previous task history, I'm using mongo.

in Mongo db all data is stored but it will not be fetched again on flower web app

**Comment by jheld** [comment]
Flower currently stores its task history in RAM. PR #821 opts to let Elasticsearch be used behind the scenes. The result backend itself could use a separate PR to be able to grab the data from the result backend if it exists; there was a recent change to celery to be able to store extended task result info in the backend (args, kwargs, name, etc), but you'd have to use a recent version of celery to make that happen, regardless of a PR into flower.

My company uses PR #821 (I wrote it) extensively. It's the only way we've been able to make the history scale; the persistence mode didn't consistently work for us (broke on start up a lot), but even at scale the searching was very slow.

Would you be willing to make a PR into flower which uses the result backend if there is a flower RAM history miss? Limited history vs no history. The PR I've linked explicitly gets around it by using a separate store, beyond the result backend. The result backend also has its own expiration rules in place, so please keep that in mind -- history likely won't be there forever (regardless of culling/TTL that you may want in place), unless you told it never to expire.

**Comment by johnarnold** [comment]
@jheld  I wrote the PR into celery, and I wrote the PR for the backend lookups:
https://github.com/mher/flower/pull/772

Haven't had time to test against the latest celery, but it should work... My intention was to update #772 with additional metadata now available in the backend "extended results" as an option.

**Comment by jheld** [comment]
@johnarnold right! I couldn't find it. Thank you for posting.
