### ISSUE TITLE
Setting soft and hard time_limit through Flower dashboard does not work

### ISSUE THREAD

**Issue by levary** [mher/flower#919]
flower==0.9.3 (but also previous versions according to the code)
In POST request `/api/task/timeout/` body looks like:
```
workername: worker1
type: 300
```
but backend expected something like:
```
workername: worker1
soft: 300
```
or
```
workername: worker1
hard: 300
```
So backend always is setting "soft=None, hard=None"

**Comment by jheld** [comment]
Thank you for reporting this, and including the data format.

Would you have time to make this change?

**Comment by levary** [comment]
Yes, I can do this.
