### ISSUE TITLE
flower having issues with tornado==6.0.3

### ISSUE THREAD

**Issue by milind-shakya-sp** [mher/flower#921]
```
AttributeError: module 'tornado.web' has no attribute 'asynchronous'
```

It was working fine for tornado==5.1.1

**Comment by Kub-AT** [comment]
Yep
https://github.com/mher/flower/blob/v0.9.3/requirements/default.txt
`tornado>=4.2.0,<6.0.0`

https://github.com/mher/flower/issues/878
https://github.com/mher/flower/issues/886
https://github.com/mher/flower/issues/903
