### ISSUE TITLE
Flower doesn't bring task's full result

### ISSUE THREAD

**Issue by fatihhcelik** [mher/flower#932]
The problem is if the task's result is long, flower doesn't bring all of them. To solve this, I set the "resultrepr_maxsize" value very high number in celery and celery gives me full string of task result. But flower doesn't display all of it. You can refer this stackoverflow post that I opened. https://stackoverflow.com/questions/57973649/flower-doesnt-display-complete-result-string?noredirect=1#comment102386210_57973649

**Comment by mher** [comment]
Make sure flower uses the same celery configuration
