### ISSUE TITLE
0.9.3 fails to install

### ISSUE THREAD

**Issue by thenewguy** [mher/flower#935]
Collecting flower (from -r /path/to/requirements.txt (line 14))
  Downloading https://files.pythonhosted.org/packages/36/15/ed670b1f1fe14727f1564c9d98d7a917352ce8a0d88e87256be3c1e1190e/flower-0.9.3.tar.gz (1.3MB)
    Complete output from command python setup.py egg_info:
    error in flower setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-BCUq8Q/flower/
You are using pip version 18.1

**Comment by mher** [comment]
Looks like you are using an old pip version. Try to install with latest pip
