### ISSUE TITLE
FEATURE: Add health check for web server

### ISSUE THREAD

**Issue by scarbeau** [mher/flower#945]
## Use case
Running Flower behind ALB within AWS.

## Implementation

/flower/views/alive.py
```python
from __future__ import absolute_import

from ..views import BaseHandler


class HealthCheckHandler(BaseHandler):
    def get(self):
        self.set_status(200)
        self.write('OK')
```

/flower/urls.py
```python
(r"/alive", HealthCheckHandler),
```

/tests/views/test_alive.py
```python
from tests.unit import AsyncHTTPTestCase


class AliveTests(AsyncHTTPTestCase):
    def test_health_check(self):
        r = self.get('/alive')
        self.assertEqual(200, r.code)
```

**Comment by jordanmkoncz** [comment]
This is a feature that we currently need too. We're deploying a Django backend with Celery/Flower to AWS; we're using Fargate and ELB and as a result we need Flower to provide a healthcheck using HTTP on port 80.

**Comment by engin-bulut** [comment]
hey @jordanmkoncz We had the same problem. But, as you know all we need for the health check is one endpoint returns 200 response. We use `/api/workers` endpoint of flower as a health check path and it worked. Give it a try.

**Comment by mher** [comment]
You can use `/metrics` endpoint for health checks

**Comment by jordanmkoncz** [comment]
@mher can you please clarify? When I call `/metrics` or `/api/metrics` I get a 404, and https://github.com/mher/flower/blob/master/flower/static/swagger.json appears to have no mention of a "metrics" endpoint.

**Comment by mher** [comment]
`/metrics` endpoint https://github.com/mher/flower/blob/master/flower/urls.py#L79

**Comment by jordanmkoncz** [comment]
@mher thanks for the clarification. Looks like this has just been added recently to `master` and has not yet been included in any release. I assume this will be part of an upcoming `0.9.5` release, so I'll try it out then.

**Comment by pblankley** [comment]
I know this issue is closed, but for those of you who still have this problem (e.g. anyone who uses auth), you can use `/healthcheck` and that should work swimmingly for you :)

**Comment by OmarElsebaey001** [comment]
@pblankley you saved my day with this comment , using auth here , thanks a million
