### ISSUE TITLE
Flower displaying a single task at a time.

### ISSUE THREAD

**Issue by alekhrycaiko** [mher/flower#946]
Hi,

I've been noticing that Flower likes to show only a single task at a time (on the tasks tab). This occurs after running for some time. In my situation, I'm certain that there are many more tasks available then the single one displayed on this tab.

I'm not too sure as to why this is happening; but would like a fix so I can see what tasks are running. The only sure way for me to see tasks running currently, would be to actually restart Flower and then see the list of tasks it's processing. 

I'm currently running the following versions of kombu and celery for my workers
- celery 4.3.0 
- kombu 4.6.6

Flower is being run on the latest docker image provided by `mher`.

**Comment by mher** [comment]
Any idea how to reproduce it? Can you share a simple example which demonstrate the issue?
