### ISSUE TITLE
Apply task API doesn't wait for results as stated in documentation

### ISSUE THREAD

**Issue by pablotunon** [mher/flower#952]
I am working in an application running celery through rabbitmq (which seem to be properly configured).

At some point, it looked convenient to enhace our celery workers using flower, so they expose a REST API that we can interact with synchronously to invoke tasks through http and obtain results.

After several headaches, I achieved a point where flower returns something when the API call is made. But the result is "null" and the state is "pending". I'd like the call to stay blocked until the result is produced. It's worth saying that a call to "info" afterwards returns a runtime of "0.0003560459990694653", so I don't think it exceeded any timeout.

I don't know whether it's a configuration issue on my side, the expected behaviour or a bug. But the documentation clearly states "Execute a task by name and wait results" with an example where the result is given.

In case it's of any help, what caused me most headaches was to configure a "backend", I had to do it explicitly for the task, like this:

```
from celery.backends.rpc import RPCBackend
from myapp.workers.main import app as worker

@worker.task(name='mytask', backend=RPCBackend(app=worker))
def mytask():
    return "OK"
```

Thanks in advance!

**Comment by mher** [comment]
The backend should be configured in flower as well, not only in celery worker
