### ISSUE TITLE
kwargs and args should be valid json

### ISSUE THREAD

**Issue by matomesc** [mher/flower#974]
Currently when retrieving a task or a list of tasks, the `args` field is a string containing a tuple and `kwargs` (and `result` if a dict is returned) returns a string containing a dict. It should return valid json instead since it doesn't really make sense to embed python data structures as strings inside json since the response is already being parsed as json.

For instance this
```json
{
  "args": "(10, 20)",
  "kwargs": "{'a': 30, 'b': 40}",
  "result": "{'total': 100}"
}
```

Should be replaced with
```json
{
  "args": [10, 20],
  "kwargs": {"a": 30, "b": 40},
  "result": {"total": 100}
}
```

**Comment by mher** [comment]
`args` and `kwargs` are not always contain full arguments. Celery trims long arguments before sending to flower.
