### ISSUE TITLE
Add `--broker` argument to help

### ISSUE THREAD

**Issue by rileymcdowell** [mher/flower#975]
When someone uses redis as a broker for celery, they'll need to pass the `--broker` argument to flower when they start it up. If you don't already know this, you'll probably scan `flower --help` to determine what parameter to pass to get it to work.  A promising candidate, `--broker-api`, is available in the `--help` output. However, this isn't actually the right thing to make flower connect to redis as a broker. As far as I can tell, the `--broker` argument is not present in the command line help output for flower.

Expected output: `--broker` is briefly mentioned in `flower --help`. 

Flower version: 0.9.4

Did I overlook something, or is this [intentionally/unintentionally] missing?

**Comment by mher** [comment]
`--broker` is a celery command option. Flower doesn't implement it.
