### ISSUE TITLE
How to flush Flower's display data?

### ISSUE THREAD

**Issue by ohld** [mher/flower#976]
How to delete all the data that is shown at Flower Dashboard? Somehow Dokku (deployment platform, open-source version of Heroku) creates Celery workers with unique names each deploy.

In result, I have a lot of rows with old workers and I really would like to remove them from the dashboard.

I understand that the better solution would be just to fix the deployment and fix the worker names but still: it is possible to flush / clear the data that is displayed at Flower's dashboard? 

![image](https://user-images.githubusercontent.com/5613295/81731002-039fd380-9497-11ea-8353-dba4bfa22220.png)

I've tried  to `flushall` Redis data with no result. 

P.S. If you know howto fix the celery worker names to remove that random name generation, that would be really awesome.

**Comment by Minipada** [comment]
Also looking for a flush feature. Meanwhile, to set a name, use `-n <name>` when starting celery. See https://docs.celeryproject.org/en/stable/userguide/workers.html#starting-the-worker

**Comment by ohld** [comment]
@Minipada I've just tried your trick but still have some random hashes in worker names in Flower.
![image](https://user-images.githubusercontent.com/5613295/83921358-d4733e00-a786-11ea-937f-622cc7f00348.png) 

I run worker this way:
``` bash
celery worker -A app -l info -Q low_priority,default --autoscale 16,4 -n worker@%h
```

**Comment by ohld** [comment]
I thought that %h is some kind of hash value but no:
![image](https://user-images.githubusercontent.com/5613295/83921452-0ab0bd80-a787-11ea-9164-02152e5ca3f6.png)

**Comment by Minipada** [comment]
Exactly :+1: . This must be because you start it in a container I guess. I suggest you to give a hostname to your container to solve the issue.

**Comment by ohld** [comment]
@Minipada thanks! I’ll try that. I’m using Dokku (open source version of Heroku) probably there would be a solution to set the hostname for app and its workers

**Comment by jheld** [comment]
Please see if PR #852 solves the issue (it's not officially released but it does work/worthwhile for you to check out).

**Comment by ohld** [comment]
@Minipada TBH I have not found the way how to set up a hostname for dockers using dokku (while my domains are already attached to dokku so nginx route everything correctly, but still celery workers' name are random).

BUT

the latest PR solve my issue and I'm happy now with my 8 workers! 

![image](https://user-images.githubusercontent.com/5613295/84686058-ef427100-af43-11ea-92df-5aa59624bc2c.png)

I just added `FLOWER_PURGE_OFFLINE_WORKERS=10` to env.

**Comment by CleitonDeLima** [comment]
I have a question @ohld,
How is your procfile configured using flower?
