### ISSUE TITLE
Is the docker image updated?

### ISSUE THREAD

**Issue by nodesocket** [mher/flower#980]
We are using this docker image [mher/flower](https://hub.docker.com/r/mher/flower) has this been updated? Additionally, is there a way to tell which version of Flower we are running? I don't see it listed in the logs.

**Comment by mrfleap** [comment]
I've found that the docker image isn't updated often, instead I'm having docker build the image directly from this repo, you can learn more from [StackOverflow](https://stackoverflow.com/questions/26753030/how-to-build-docker-image-from-github-repository/39194765).

So, in my case, my Docker Compose file looks like this:
```
flower:
    build: https://github.com/mher/flower.git
    ....
```

It's not a great solution, but just a workaround.

**Comment by benjaminh** [comment]
@mrfleap When trying your solution, I get the following error complaining about python future module:

```
flower_1    | Traceback (most recent call last):                                                          │
flower_1    |   File "/usr/local/bin/flower", line 5, in <module>                                         │
flower_1    |     from flower.__main__ import main                                                        │
flower_1    |   File "/usr/local/lib/python3.8/site-packages/flower/__main__.py", line 4, in <module>     │
flower_1    |     from flower.command import FlowerCommand                                                │
flower_1    |   File "/usr/local/lib/python3.8/site-packages/flower/command.py", line 20, in <module>     │
flower_1    |     from .app import Flower                                                                 │
flower_1    |   File "/usr/local/lib/python3.8/site-packages/flower/app.py", line 15, in <module>         │
flower_1    |     from .urls import handlers                                                              │
flower_1    |   File "/usr/local/lib/python3.8/site-packages/flower/urls.py", line 9, in <module>         │
flower_1    |     from .api import tasks                                                                  │
flower_1    |   File "/usr/local/lib/python3.8/site-packages/flower/api/tasks.py", line 17, in <module>   │
flower_1    |     from celery.backends.base import DisabledBackend                                        │
flower_1    |   File "/usr/local/lib/python3.8/site-packages/celery/backends/base.py", line 10, in <module│
>                                                                                                         │
flower_1    |     from future.utils import raise_with_traceback                                           │
flower_1    | ModuleNotFoundError: No module named 'future' 
```

Do you think I should create a dedicated Dockerfile that specify to install future module ?

**Comment by mrfleap** [comment]
Unfortunately that's intended behavior. As of right now, flower is installing the latest version of Celery and Python 3.8 which does not work together (see https://github.com/celery/celery/issues/6153). If you need to get it working right now, you can absolutely use a custom Dockerfile that also installs the future module or you could fork Flower and change the Python or Celery version installed and use that fork instead. Until Celery is updated though, building from this git repo won't work.

**Comment by benjaminh** [comment]
Thx @mrfleap, I did use the Dockerfile in the repo and added a command to install future module with pip. Looks like this workaround does the job !

**Comment by mher** [comment]
I've pushed a new version to docker hum

**Comment by mher** [comment]
Use `docker run mher/flower --version` command to check flower version

**Comment by ushuz** [comment]
> I've pushed a new version to docker hub

@mher FYI, it's pretty easy to setup an automated process to keep Docker Hub image updated, either through:

- Docker Hub's [Automated Build](https://docs.docker.com/docker-hub/builds/)
- or, [GitHub Action](https://github.com/marketplace/actions/build-and-push-docker-images) provided by Docker

Both services are free to use.
