### ISSUE TITLE
CORS error when calling API

### ISSUE THREAD

**Issue by benjaminh** [mher/flower#982]
I try to fetch info on celery tasks using Flower http rest API.

Yet, I get CORS errors when I call it from my web client (everything works fine if I use postman):
`Cross-Origin Request Blocked: The Same Origin Policy disallows
reading the remote resource at http://localhost:5555/api/tasks. Reason: CORS header ‘Access-Control-Allow-Origin’ missing`

I didn't find how to set CORS policy for flower, any pointer ?

I'm using flower 0.9.4, and I run it using the Dockerfile within a docker-compose file.

**Comment by mher** [comment]
Fixed by https://github.com/mher/flower/pull/994
