### ISSUE TITLE
natural sorting for tables

### ISSUE THREAD

**Issue by waleedsamy** [mher/flower#983]
[Natural sorting](https://blog.codinghorror.com/sorting-for-humans-natural-sort-order/) of tables will look more human than the default ascii order of DataTables ([plugin available](https://github.com/DataTables/Plugins/blob/master/sorting/natural.js)).

If you have workers [celery@vm1, celery@vm2...celery@vm13]. sorting the workers will show 
```
  celery@vm1
  celery@vm10
  celery@vm11
  celery@vm12
  celery@vm13
  celery@vm2
  .
  .
  .
```
but I expect
```
 celery@vm1
 celery@vm2
 celery@vm3
 .
 .
 .
 celery@vm15
```

**Comment by mher** [comment]
Can you open a pull request?
