### ISSUE TITLE
How to extend flower endpoints?

### ISSUE THREAD

**Issue by masters3d** [mher/flower#986]
I understand that flower uses [tornado](https://www.tornadoweb.org/en/stable/web.html) to handle web request. 

Lets say I want to extend flower/tornato with other endpoints. Right now I am doing this by adding my class endpoint in the tasks.py file 
https://github.com/mher/flower/blob/bea199dd4c05ddb9a305a5936e6d992e90af7ec8/flower/api/tasks.py#L81

Is there a different way I can add these endpoints where I don't have to edit the source file? 

For example, how can I add my own handler to this list with out editing the package source code?
https://github.com/mher/flower/blob/bea199dd4c05ddb9a305a5936e6d992e90af7ec8/flower/urls.py#L30

```
import os
import time
from datetime import datetime

from celery import Celery

app = Celery("tasks",
             broker=os.environ.get('CELERY_BROKER_URL', 'redis://'),
             backend=os.environ.get('CELERY_RESULT_BACKEND', 'redis'))
app.conf.CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

// How do I gain access to flower internals here to extend the endpoints?

@app.task
def somCustomTask(x, y):
    return x + y

if __name__ == "__main__":
    app.start()
```

**Comment by jheld** [comment]
I don't think you can; that said `locust` was built in a way which allows it, so possibly! But unless there is some undocumented way in `flower`, this would have to have a PR for pluggable URL handler registration first.
