### ISSUE TITLE
Pagination support in API endpoint - /api/tasks

### ISSUE THREAD

**Issue by lukasmatta** [mher/flower#989]
Hello,
when using `/api/tasks/` endpoint, there is a possibility to set `limit=x` variable to limit the number of tasks retrieved. Is there any possibility to set `offset=y` variable in order to ignore first `y` tasks and show the other ones? This is necessary when implementing pagination on frontend.

**Comment by mher** [comment]
There are no plans to work on this feature at the moment until someone decides to contribute to the project.

**Comment by lukasmatta** [comment]
I think I can work on this. Will keep you posted.
