### ISSUE TITLE
monitor and broker is empty

### ISSUE THREAD

**Issue by iam-jay** [mher/flower#991]
I am running my flower like this 
`flower -A celery_app --port=8888`
<img width="1426" alt="Screenshot 2020-06-17 at 11 15 58 AM" src="https://user-images.githubusercontent.com/2466198/84860492-c24da580-b08c-11ea-99d1-c8f84f6e2622.png">
<img width="1440" alt="Screenshot 2020-06-17 at 11 16 15 AM" src="https://user-images.githubusercontent.com/2466198/84860499-c4176900-b08c-11ea-8cef-95a182913c9f.png">
<img width="1440" alt="Screenshot 2020-06-17 at 11 16 24 AM" src="https://user-images.githubusercontent.com/2466198/84860502-c4afff80-b08c-11ea-8509-07e486692f2c.png">
<img width="1440" alt="Screenshot 2020-06-17 at 11 16 40 AM" src="https://user-images.githubusercontent.com/2466198/84860506-c4afff80-b08c-11ea-9815-c09eadb194b9.png">

**Comment by zuihai** [comment]
I have the same problem

**Comment by mher** [comment]
Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use StackOverflow.com for general usage questions instead.
