### ISSUE TITLE
Upgrading ancient version of humanize

### ISSUE THREAD

**Issue by robvdl** [mher/flower#992]
I was using humanize in my own project and when I installed flower into the same virtualenv I ran into a package version clash where it wanted to downgrade humanize from 2.4.0 (2020) to 0.5.1 (2014).

Is there a particular reason to be pinning this to such an old version? Does it even need to be pinned or perhaps a version range could be used?

**Comment by robvdl** [comment]
By the way this is to do with the recent upgrade to flower 0.9.4, which has added the humanize library as a new depdedency but for some reason it's pinned to an old version from 2014 which is a little annoying.

**Comment by mher** [comment]
@robvdl feel free to open a pull request

**Comment by mher** [comment]
Fixed by #979
