### ISSUE TITLE
Directory permissions are lost in Dockerfile

### ISSUE THREAD

**Issue by gcolombeau** [mher/flower#999]
When using the docker image and the persistent mode, Flower cannot create the DB file due to a permission error.
This behavior was supposed to be fixed in the version 0.9.5 but I think it all comes down to where the volume is defined in the Dockerfile.
See  for example https://container42.com/2014/11/03/docker-indepth-volumes/

https://github.com/mher/flower/blob/59cd3b2be4eabb447bb71aa279394833bf28267e/Dockerfile#L20-L29

I believe the volume instruction should be declared after setting the directory owner. At the moment, it seems the run instruction is only applied **inside the volume** at build time, which is actually a no op, instead of in the container directory.

You can verify this by launching a new container and inspecting the ``/data`` directory which is still owned by root:
```shell
docker run -it --rm --entrypoint sh mher/flower
/data $ ls -al .
total 8
drwxr-xr-x    2 root     root          4096 Jul  3 14:49 .
drwxr-xr-x    1 root     root          4096 Jul 10 13:10 ..
```

**Comment by mher** [comment]
Thanks for opening the issue @gcolombeau. Feel free to open a pull request.

**Comment by mher** [comment]
Updated image was pushed to docker hub (docker pull mher/flower:latest)
